/* Generated by dx imports sync. */
/* Keep source files editable; regenerate after moves or export changes. */
export * from "./mobile-companion/companion-screen";
export * from "./icons/icon";

export const dxAutoImportMap = {
  "components": [
    {
      "kind": "component",
      "name": "FrameworkCompletenessItem",
      "source": "components/launch/framework-completeness.ts",
      "import_path": "@/components/launch/framework-completeness",
      "barrel_export": null,
      "exports": [
        "FrameworkCompletenessItem",
        "FrameworkCompletenessStatus",
        "dxMobileAppFrameworkCompleteness",
        "dxMobileAppFrameworkCompletenessScore",
        "dxMobileAppFrameworkCompletenessSummary",
        "frameworkCompletenessContract"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "FrameworkCompletenessItem",
        "FrameworkCompletenessStatus",
        "dxMobileAppFrameworkCompleteness",
        "dxMobileAppFrameworkCompletenessScore",
        "dxMobileAppFrameworkCompletenessSummary",
        "frameworkCompletenessContract"
      ],
      "type_exports": [
        "FrameworkCompletenessItem",
        "FrameworkCompletenessStatus"
      ]
    },
    {
      "kind": "component",
      "name": "DxMobileAuthScreen",
      "source": "components/mobile-auth/auth-screen.tsx",
      "import_path": "@/components/mobile-auth/auth-screen",
      "barrel_export": null,
      "exports": [
        "DxMobileAuthScreen"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "DxMobileAuthScreen"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "DxMobileCompanionScreen",
      "source": "components/mobile-companion/companion-screen.tsx",
      "import_path": "@/components/mobile-companion/companion-screen",
      "barrel_export": "./mobile-companion/companion-screen",
      "exports": [
        "DxMobileCompanionScreen"
      ],
      "default_export_name": null,
      "used_exports": [
        "DxMobileCompanionScreen"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "Icon",
      "source": "components/icons/icon.tsx",
      "import_path": "@/components/icons/icon",
      "barrel_export": "./icons/icon",
      "exports": [
        "Icon",
        "IconProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "Icon",
        "IconProps"
      ],
      "unused_exports": [],
      "type_exports": [
        "IconProps"
      ]
    },
    {
      "kind": "dx-icon",
      "name": "PackArrowRightIcon",
      "source": "components/icons/pack-arrow-right.tsx",
      "import_path": "@/components/icons/pack-arrow-right",
      "barrel_export": null,
      "exports": [
        "PackArrowRightIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackArrowRightIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackCheckIcon",
      "source": "components/icons/pack-check.tsx",
      "import_path": "@/components/icons/pack-check",
      "barrel_export": null,
      "exports": [
        "PackCheckIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackCheckIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "StatusCheckIcon",
      "source": "components/icons/status-check.tsx",
      "import_path": "@/components/icons/status-check",
      "barrel_export": null,
      "exports": [
        "StatusCheckIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "StatusCheckIcon"
      ],
      "type_exports": []
    }
  ],
  "composables": [],
  "utilities": [],
  "forgePackages": [
    {
      "packageId": "auth/better-auth",
      "source": "forge/auth/better-auth",
      "importPath": "@/forge/auth/better-auth",
      "exports": []
    },
    {
      "packageId": "www/minimal-starter",
      "source": "forge/www/minimal-starter",
      "importPath": "@/forge/www/minimal-starter",
      "exports": []
    }
  ],
  "styleHelpers": [
    {
      "name": "generated.css",
      "source": "styles/generated.css",
      "importPath": "@/styles/generated.css"
    },
    {
      "name": "theme.css",
      "source": "styles/theme.css",
      "importPath": "@/styles/theme.css"
    }
  ],
  "sourceHash": "blake3:d0aa75113f40a9355595ef8602abde9c8f93084fe134ba7c6ac513172ae7d1bf"
} as const;

export type DxAutoImportComponent = typeof dxAutoImportMap.components[number]["name"];
export type DxAutoImportComposable = typeof dxAutoImportMap.composables[number]["name"];
export type DxAutoImportUtility = typeof dxAutoImportMap.utilities[number]["name"];
export type DxAutoImportForgePackage = typeof dxAutoImportMap.forgePackages[number]["packageId"];
export type DxAutoImportStyleHelper = typeof dxAutoImportMap.styleHelpers[number]["name"];
