import {
  agentChartRequest,
  bulletReadiness,
  chartAdviceIntent,
  chartSkillCatalog,
  datasetPipeline,
  diagramWorkflow,
  funnelConversionStages,
  gaugeSignals,
  geoUsagePoints,
  geoUsageRegionShapes,
  geoUsageRegions,
  gptVisPromptRequest,
  graphCombos,
  graphEdges,
  graphModelEdges,
  graphNodes,
  heatmapCells,
  mobileChartTerms,
  packageAdoptionSignals,
  packageModeScores,
  packageReadiness,
  packageRelationFlows,
  packageSpread,
  pivotReadinessRows,
  proportionMix,
  qualityScores,
  radarCapabilities,
  receiptTrend,
  releaseWorkMix,
  runtimeProofs,
  sunburstPackages,
  treemapPackages,
  waterfallReleaseDeltas,
  weeklyActivity,
} from "./data";
import { chartSkillsGraph, createMcpRequestFlow } from "./agent-model";
import { diagramModelToGraph } from "./compiler/diagram-model";
import { f2CompactChart } from "./mobile-model";
import { antDesignColumn, antDesignProgress } from "./presets/ant-design-charts";
import { antDesignGraph } from "./presets/ant-design-graphs";
import { antDesignSankey, antDesignSunburst, antDesignTreemap } from "./presets/ant-design-plots-hierarchy";
import { antDesignBullet, antDesignDualAxes, antDesignGauge, antDesignHeatmap } from "./presets/ant-design-plots";
import { avaAdviceChart } from "./presets/ava";
import { dataSetFlowChart } from "./presets/dataset";
import { f2WordCloud } from "./presets/f2-wordcloud";
import { g2plotChord } from "./presets/g2plot-chord";
import { g2plotSankey, g2plotSunburst, g2plotTreemap } from "./presets/g2plot-hierarchy";
import { g2plotBullet, g2plotCartesian, g2plotFacet, g2plotHeatmap, g2plotHistogram } from "./presets/g2plot";
import { g2plotBox } from "./presets/g2plot-box";
import { g2plotFunnel } from "./presets/g2plot-funnel";
import { g2plotGauge, g2plotProgress, g2plotRingProgress, g2plotTiny } from "./presets/g2plot-mini";
import { g2plotPie, g2plotRadar, g2plotRose } from "./presets/g2plot-radial";
import { g2plotWaterfall } from "./presets/g2plot-waterfall";
import { gptVisPromptChart } from "./presets/gptvis";
import { l7CompositeLayers } from "./presets/l7";
import { l7plotChoropleth, l7plotMap } from "./presets/l7plot";
import { s2PivotSheet } from "./presets/s2";
import type { ChartCatalogItem, ChartFamily, ChartSpec, ChartTask } from "./spec";

const size = { width: 640, height: 380 } as const;

function chart(
  slug: string,
  title: string,
  family: ChartFamily,
  task: ChartTask,
  summary: string,
  spec: ChartSpec,
  extra?: Partial<Pick<ChartCatalogItem, "whenToUse" | "avoidWhen" | "dataShape" | "encodingNotes">>,
): ChartCatalogItem {
  return {
    slug,
    title,
    family,
    task,
    summary,
    whenToUse: extra?.whenToUse ?? "Use when the question is easier to answer by comparing encoded values than reading a raw table.",
    avoidWhen: extra?.avoidWhen ?? "Avoid when the data has no stable ordering, measurement unit, or interpretable grouping.",
    dataShape: extra?.dataShape ?? "Array of records with explicit fields used by the chart spec.",
    encodingNotes: extra?.encodingNotes ?? ["Fields are mapped to visual channels through a typed spec.", "The renderer compiles SVG scenes without npm packages."],
    spec,
  };
}

export const chartCatalog: ChartCatalogItem[] = [
  chart("bar-builds", "Weekly Activity Bar", "G2", "comparison", "A direct interval mark for build volume by day.", {
    id: "bar-builds",
    title: "Weekly activity",
    description: "Build throughput by weekday.",
    task: "comparison",
    family: "G2",
    ...size,
    data: weeklyActivity,
    marks: [{ id: "builds", type: "bar", encoding: { x: { field: "day", type: "ordinal", label: "Day" }, y: { field: "builds", type: "quantitative", label: "Builds" }, color: { field: "lane", type: "nominal" } } }],
    axes: [{ channel: "x" }, { channel: "y", grid: true }],
    legend: { channel: "color", title: "Lane" },
  }),
  chart("target-builds", "Build Target Rule", "G2", "comparison", "A bar chart with a compiled target rule mark.", {
    id: "target-builds",
    title: "Build target threshold",
    description: "Daily build volume with a source-owned horizontal target rule.",
    task: "comparison",
    family: "G2",
    ...size,
    data: weeklyActivity,
    marks: [
      { id: "target-build-bars", type: "bar", encoding: { x: { field: "day", type: "ordinal", label: "Day" }, y: { field: "builds", type: "quantitative", label: "Builds" }, color: { field: "lane", type: "nominal" } } },
      {
        id: "target-build-rule",
        type: "rule",
        transforms: [{ type: "group", groupBy: [], field: "target", as: "target", reducer: "max" }],
        encoding: { y: { field: "target", type: "quantitative", label: "Target" } },
        style: { stroke: "hsl(var(--chart-warning))", strokeWidth: 2 },
      },
    ],
    axes: [{ channel: "x" }, { channel: "y", grid: true }],
    legend: { channel: "color", title: "Lane" },
  }, {
    whenToUse: "Use when an operational target should stay visible against a measured series.",
    dataShape: "Rows contain the measured value and a repeated target field; a local group transform collapses the rule to one threshold row.",
    encodingNotes: ["The bar and rule marks share one chart spec but compile through separate mark paths.", "The rule mark uses its own y encoding and group transform instead of a pre-rendered line."],
  }),
  chart("line-receipts", "Receipt Trend Line", "G2", "trend", "A multi-series line chart for DX receipt scores.", {
    id: "line-receipts",
    title: "Receipt score trend",
    description: "Two receipt families improving over five review weeks.",
    task: "trend",
    family: "G2",
    ...size,
    data: receiptTrend,
    marks: [
      { id: "receipt-area", type: "area", encoding: { x: { field: "week", type: "ordinal" }, y: { field: "score", type: "quantitative" }, series: { field: "series", type: "nominal" } } },
      { id: "receipt-line", type: "line", encoding: { x: { field: "week", type: "ordinal", label: "Week" }, y: { field: "score", type: "quantitative", label: "Score" }, series: { field: "series", type: "nominal" } } },
      { id: "receipt-points", type: "point", encoding: { x: { field: "week", type: "ordinal" }, y: { field: "score", type: "quantitative" }, series: { field: "series", type: "nominal" } } },
    ],
    legend: { channel: "series", title: "Receipt" },
  }),
  chart("tiny-receipt-trend", "Tiny Receipt Trend", "G2Plot", "trend", "A G2Plot tiny area preset that compiles without axes or package runtime.", g2plotTiny({
    id: "tiny-receipt-trend",
    title: "Tiny receipt trend",
    description: "Compact receipt trend for dense dashboard surfaces.",
    task: "trend",
    data: receiptTrend,
    preset: "tiny-area",
    xField: "week",
    yField: "score",
    seriesField: "series",
  }), {
    whenToUse: "Use when a dense operational panel needs trend direction more than axis-heavy analysis.",
    dataShape: "Rows carry one ordinal x field, one quantitative y field, and an optional series field.",
    encodingNotes: ["The tiny adapter suppresses axes through the typed chart spec.", "The chart still compiles through the production area mark path."],
  }),
  chart("progress-source-readiness", "Source Readiness Progress", "G2Plot", "proportion", "A G2Plot progress preset lowered into the local gauge mark path.", g2plotProgress({
    id: "progress-source-readiness",
    title: "Source readiness progress",
    description: "Compact progress coverage with a target marker.",
    task: "proportion",
    data: gaugeSignals,
    valueField: "value",
    targetField: "target",
    labelField: "metric",
    valueFormat: "percent",
  })),
  chart("ring-progress-source-coverage", "Source Coverage Ring", "G2Plot", "proportion", "A G2Plot ring-progress preset for dense single-value cards.", g2plotRingProgress({
    id: "ring-progress-source-coverage",
    title: "Source-owned coverage ring",
    description: "Ring progress coverage with a target marker.",
    task: "proportion",
    data: gaugeSignals,
    valueField: "value",
    targetField: "target",
    labelField: "metric",
    valueFormat: "percent",
  })),
  chart("g2-view-grammar", "G2 View Grammar", "G2", "composition", "A source-owned view composition with child coordinate metadata.", {
    id: "g2-view-grammar",
    title: "G2 view grammar",
    description: "Two child chart specs compiled into one SVG scene with G2-style view regions.",
    task: "composition",
    family: "G2",
    ...size,
    data: [],
    marks: [],
    composition: {
      type: "view",
      children: [
        {
          id: "trend",
          title: "Receipt trend view",
          region: { x: 0, y: 0, width: 0.54, height: 1 },
          spec: {
            id: "g2-view-trend",
            title: "Receipt trend view",
            description: "Line and area marks compiled inside a child view.",
            task: "trend",
            family: "G2",
            width: 320,
            height: 320,
            data: receiptTrend,
            coordinate: { type: "cartesian" },
            marks: [
              { id: "view-receipt-area", type: "area", encoding: { x: { field: "week", type: "ordinal" }, y: { field: "score", type: "quantitative" }, series: { field: "series", type: "nominal" } } },
              { id: "view-receipt-line", type: "line", encoding: { x: { field: "week", type: "ordinal" }, y: { field: "score", type: "quantitative" }, series: { field: "series", type: "nominal" } } },
            ],
            legend: { channel: "series", title: "Receipt" },
          },
        },
        {
          id: "target",
          title: "Target coordinate view",
          region: { x: 0.58, y: 0, width: 0.42, height: 1 },
          spec: {
            id: "g2-view-target",
            title: "Target coordinate view",
            description: "Bar and rule marks compiled with transpose coordinate metadata.",
            task: "comparison",
            family: "G2",
            width: 260,
            height: 320,
            data: weeklyActivity,
            coordinate: { type: "transpose" },
            marks: [
              { id: "view-target-bars", type: "bar", encoding: { x: { field: "day", type: "ordinal", label: "Day" }, y: { field: "builds", type: "quantitative", label: "Builds" }, color: { field: "lane", type: "nominal" } } },
              { id: "view-target-rule", type: "rule", transforms: [{ type: "group", groupBy: [], field: "target", as: "target", reducer: "max" }], encoding: { y: { field: "target", type: "quantitative", label: "Target" } }, style: { stroke: "hsl(var(--chart-warning))", strokeWidth: 2 } },
            ],
            axes: [{ channel: "x" }, { channel: "y", grid: true }],
            legend: { channel: "color", title: "Lane" },
          },
        },
      ],
    },
  }, {
    dataShape: "Parent spec owns layout regions; child specs keep their own rows, marks, legends, and coordinate declarations.",
    encodingNotes: ["The compiler lowers each child view through the same production mark compilers.", "Scene elements carry view and coordinate metadata for DX checks and runtime inspection."],
  }),
  chart("stacked-release-work", "Stacked Release Work", "G2Plot", "composition", "A stackY transform for cumulative release work by lane.", g2plotCartesian({
    id: "stacked-release-work",
    title: "Release work stack",
    description: "Work hours stacked by lane for each release week.",
    task: "composition",
    data: releaseWorkMix,
    preset: "column",
    xField: "week",
    yField: "hours",
    xLabel: "Week",
    yLabel: "Hours",
    seriesField: "lane",
    isStack: true,
  }), {
    dataShape: "Rows contain one category, one series field, and one quantitative value; stackY computes cumulative y spans.",
    encodingNotes: ["The G2Plot column adapter lowers isStack into stackY metadata.", "The original value remains available for labels while y-domain uses the stack end."],
  }),
  chart("normalized-release-share", "Normalized Release Share", "G2Plot", "proportion", "A normalizeY transform for weekly lane share.", g2plotCartesian({
    id: "normalized-release-share",
    title: "Release work share",
    description: "Lane work normalized to a 100 percent stack for each week.",
    task: "proportion",
    data: releaseWorkMix,
    preset: "column",
    xField: "week",
    yField: "hours",
    xLabel: "Week",
    yLabel: "Share",
    valueFormat: "percent",
    seriesField: "lane",
    isPercent: true,
  })),
  chart("dodged-package-modes", "Dodged Package Modes", "G2Plot", "comparison", "A dodgeX transform for grouped package readiness modes.", g2plotCartesian({
    id: "dodged-package-modes",
    title: "Package readiness modes",
    description: "Source, runtime, and proof scores rendered as dodged bars.",
    task: "comparison",
    data: packageModeScores,
    preset: "column",
    xField: "package",
    yField: "score",
    yLabel: "Score",
    seriesField: "mode",
    isGroup: true,
  })),
  chart("faceted-runtime-proof", "Faceted Runtime Proof", "G2Plot", "relation", "A facet composition that compiles small multiples from one spec.", g2plotFacet({
    id: "faceted-runtime-proof",
    title: "Runtime proof facets",
    description: "Complexity and proof split by surface family.",
    task: "relation",
    data: runtimeProofs,
    preset: "facet",
    field: "family",
    columns: 3,
    label: "Family",
    child: {
      preset: "scatter",
      xField: "complexity",
      yField: "proof",
      xLabel: "Complexity",
      yLabel: "Proof",
      sizeField: "proof",
      colorField: "surface",
    },
  }), {
    dataShape: "One flat table with a facet field; composition splits rows into compiled sub-scenes.",
    encodingNotes: ["The G2Plot facet adapter lowers child scatter config into one composable chart spec.", "Sub-scene elements are translated with stable scene metadata instead of detached card stand-ins."],
  }),
  chart("plot-readiness", "Package Readiness Plot", "G2Plot", "comparison", "A source-owned column preset for package readiness.", g2plotCartesian({
    id: "plot-readiness",
    title: "Package readiness",
    description: "AntV package families translated into DX-owned readiness slices.",
    task: "comparison",
    data: packageReadiness,
    preset: "column",
    xField: "package",
    yField: "score",
    yLabel: "Score",
    colorField: "family",
  })),
  chart("scatter-runtime", "Runtime Proof Scatter", "G2Plot", "relation", "A source-owned scatter preset for implementation complexity and proof strength.", g2plotCartesian({
    id: "scatter-runtime",
    title: "Runtime proof matrix",
    description: "Complexity versus current source proof for chart surfaces.",
    task: "relation",
    data: runtimeProofs,
    preset: "scatter",
    xField: "complexity",
    yField: "proof",
    xLabel: "Complexity",
    yLabel: "Proof",
    sizeField: "proof",
    colorField: "family",
  })),
  chart("pie-product-mix", "Product Mix Pie", "G2Plot", "proportion", "A proportion view that compiles into deterministic SVG arcs.", g2plotPie({
    id: "pie-product-mix",
    title: "Visualization use cases",
    description: "Relative product scenarios for a charting framework.",
    task: "proportion",
    data: proportionMix,
    angleField: "value",
    colorField: "label",
  })),
  chart("rose-product-mix", "Product Mix Rose", "G2Plot", "proportion", "A rose-style radial preset for category share comparisons.", g2plotRose({
    id: "rose-product-mix",
    title: "Visualization rose",
    description: "Radial category share using existing proportion data.",
    task: "proportion",
    data: proportionMix,
    xField: "label",
    yField: "value",
    colorField: "label",
  })),
  chart("heatmap-lanes", "Lane Heatmap", "G2Plot", "distribution", "A matrix of source lanes and chart kernel tasks.", g2plotHeatmap({
    id: "heatmap-lanes",
    title: "Lane coverage heatmap",
    description: "A heatmap mark for matrix-style source proof coverage.",
    task: "distribution",
    data: heatmapCells,
    preset: "heatmap",
    xField: "task",
    yField: "lane",
    colorField: "value",
  })),
  chart("histogram-quality", "Quality Histogram", "G2Plot", "distribution", "A source-owned histogram preset that bins raw scores into counts.", g2plotHistogram({
    id: "histogram-quality",
    title: "Quality score distribution",
    description: "Raw score rows compiled through a local bin transform.",
    task: "distribution",
    data: qualityScores,
    preset: "histogram",
    binField: "score",
    binNumber: 7,
    min: 50,
    xLabel: "Score band",
    yLabel: "Packages",
  }), {
    whenToUse: "Use when raw numeric observations need a distribution view without introducing a package runtime.",
    dataShape: "Raw records with one quantitative field; the histogram adapter creates bin labels and count rows.",
    encodingNotes: ["The G2Plot histogram adapter lowers binNumber into a local bin transform.", "The rendered bars come from transformed rows, not pre-baked fixture counts."],
  }),
  chart("boxplot-package-spread", "Package Spread Boxplot", "G2Plot", "distribution", "A five-number summary preset for package quality spread.", g2plotBox({
    id: "boxplot-package-spread",
    title: "Package score spread",
    description: "Low, quartile, median, and high score summaries.",
    task: "distribution",
    data: packageSpread,
    xField: "package",
    lowField: "low",
    q1Field: "q1",
    medianField: "median",
    q3Field: "q3",
    highField: "high",
    yLabel: "Score",
  })),
  chart("radar-capabilities", "Capability Radar", "G2Plot", "comparison", "A radar chart for comparing DX and AntV-style capabilities.", g2plotRadar({
    id: "radar-capabilities",
    title: "Capability radar",
    description: "Grammar, theme, a11y, runtime, and receipt posture.",
    task: "comparison",
    data: radarCapabilities,
    xField: "axis",
    yField: "score",
    seriesField: "series",
  })),
  chart("bullet-readiness", "Readiness Bullet Chart", "G2Plot", "comparison", "A target-aware bullet preset for implementation readiness.", g2plotBullet({
    id: "bullet-readiness",
    title: "Readiness targets",
    description: "Current source proof compared with target bars.",
    task: "comparison",
    data: bulletReadiness,
    xField: "metric",
    valueField: "value",
    targetField: "target",
    valueLabel: "Current",
    targetLabel: "Target",
  })),
  chart("gauge-source-readiness", "Source Readiness Gauge", "G2Plot", "proportion", "A gauge preset for a single source-owned coverage signal.", g2plotGauge({
    id: "gauge-source-readiness",
    title: "Source-owned coverage",
    description: "One signal with a target marker.",
    task: "proportion",
    data: gaugeSignals,
    valueField: "value",
    targetField: "target",
    labelField: "metric",
    valueFormat: "percent",
  })),
  chart("funnel-chart-readiness", "Chart Readiness Funnel", "G2Plot", "flow", "A source-owned funnel preset for staged chart generation progress.", g2plotFunnel({
    id: "funnel-chart-readiness",
    title: "Chart readiness funnel",
    description: "Chart generation stages shaped by retained request counts.",
    task: "flow",
    data: funnelConversionStages,
    labelField: "stage",
    valueField: "count",
    valueFormat: "compact",
  }), {
    whenToUse: "Use when a staged process loses volume between well-defined steps.",
    dataShape: "Rows are ordered process stages with one quantitative retained-count field.",
    encodingNotes: ["The G2Plot funnel adapter lowers label and value fields into a dedicated funnel mark.", "The compiler renders trapezoid stages from source rows instead of static artwork."],
  }),
  chart("waterfall-release-delta", "Release Delta Waterfall", "G2Plot", "comparison", "A source-owned waterfall preset for cumulative release impact.", g2plotWaterfall({
    id: "waterfall-release-delta",
    title: "Release delta waterfall",
    description: "Positive and negative implementation deltas accumulated into a final proof total.",
    task: "comparison",
    data: waterfallReleaseDeltas,
    xField: "stage",
    yField: "delta",
    totalField: "total",
    xLabel: "Stage",
    yLabel: "Delta",
    valueFormat: "compact",
  }), {
    whenToUse: "Use when each stage changes a cumulative total and the final retained value matters.",
    dataShape: "Ordered rows carry one stage label, one signed delta, and an optional total flag.",
    encodingNotes: ["The adapter lowers signed deltas into a dedicated waterfall mark.", "The compiler calculates cumulative starts, ends, and connector lines from source rows."],
  }),
  chart("treemap-packages", "Package Treemap", "G2Plot", "proportion", "A treemap-like area allocation across visualization families.", g2plotTreemap({
    id: "treemap-packages",
    title: "Package surface area",
    description: "Relative complexity across visualization package families.",
    task: "proportion",
    data: treemapPackages,
    labelField: "label",
    valueField: "value",
  })),
  chart("sunburst-ecosystem", "Ecosystem Sunburst", "G2Plot", "proportion", "A parented hierarchy sunburst preset for AntV package coverage.", g2plotSunburst({
    id: "sunburst-ecosystem",
    title: "Ecosystem coverage rings",
    description: "AntV package areas arranged as parent-subdivided radial rings.",
    task: "proportion",
    data: sunburstPackages,
    labelField: "label",
    parentField: "parent",
    levelField: "level",
    valueField: "value",
  })),
  chart("sankey-package-relationships", "Package Relationship Sankey", "G2Plot", "flow", "A G2Plot sankey preset for weighted package relationship flow.", g2plotSankey({
    id: "sankey-package-relationships",
    title: "Package relationship flow",
    description: "Weighted AntV package relationships lowered into a local sankey scene.",
    task: "flow",
    data: packageRelationFlows,
    sourceField: "source",
    targetField: "target",
    weightField: "weight",
    sourceLabel: "Source",
    targetLabel: "Target",
    weightLabel: "Weight",
  }), {
    whenToUse: "Use when weighted relationships should be read as left-to-right flow.",
    dataShape: "Rows contain source, target, and weight fields matching G2Plot Sankey detail data.",
    encodingNotes: ["The adapter lowers sourceField, targetField, and weightField into the local sankey mark.", "The compiler renders Bezier flow paths and endpoint nodes from source rows."],
  }),
  chart("chord-package-flows", "Package Chord Flows", "G2Plot", "relation", "A G2Plot chord preset for weighted package relationships.", g2plotChord({
    id: "chord-package-flows",
    title: "Package relation chord",
    description: "Weighted AntV package relationships rendered with local chord ribbons.",
    task: "relation",
    data: packageRelationFlows,
    sourceField: "source",
    targetField: "target",
    weightField: "weight",
    sourceLabel: "Source",
    targetLabel: "Target",
    weightLabel: "Weight",
    nodeSort: "weight-desc",
  }), {
    whenToUse: "Use when directed relationships should be compared by both endpoint weight and circular adjacency.",
    dataShape: "Rows contain source, target, and weight fields; duplicate links are aggregated before layout.",
    encodingNotes: ["The G2Plot chord adapter lowers sourceField, targetField, and weightField into a dedicated chord mark.", "The compiler computes node arcs and ribbon paths from source rows without a package runtime."],
  }),
  chart("sankey-pipeline", "Data Pipeline Sankey", "MCP", "flow", "A source-owned flow scene for agent/chart generation paths.", createMcpRequestFlow({
    id: "sankey-pipeline",
    title: "Spec pipeline",
    description: "Agent chart request materialized as a local MCP-style flow.",
    request: agentChartRequest,
    skills: chartSkillCatalog,
  })),
  chart("graph-ecosystem", "Package Dependency Graph", "G6", "relation", "A graph scene that maps visualization package relationships.", {
    id: "graph-ecosystem",
    title: "Visualization ecosystem graph",
    description: "AntV-style package relationships expressed as DX graph data.",
    task: "relation",
    family: "G6",
    ...size,
    data: graphEdges,
    graph: {
      nodes: graphNodes,
      edges: graphModelEdges,
      combos: graphCombos,
      layout: { type: "combo-cluster" },
      behaviors: [{ type: "zoom-canvas" }, { type: "focus-node", focus: { nodeId: "G2", relationDepth: 1 } }, { type: "activate-relations", activation: { nodeId: "G2", relation: "preset layer" } }],
      plugins: [{ type: "legend", position: "top-right" }, { type: "tooltip", target: "selection" }],
    },
    marks: [{ id: "ecosystem", type: "graph", encoding: { source: { field: "source", type: "nominal" }, target: { field: "target", type: "nominal" } } }],
  }),
  chart("map-usage", "Geospatial Usage Map", "L7", "map", "A tokenized map scene for L7-style geospatial visualization.", l7CompositeLayers({
    id: "map-usage",
    title: "Usage by region",
    description: "Geospatial points over an abstract map plate.",
    data: geoUsagePoints,
    xField: "x",
    yField: "y",
    valueField: "value",
    labelField: "city",
    viewport: { center: [90, 24], zoom: 1.25, minZoom: 0, maxZoom: 8, pitch: 8, bearing: -6 },
    basemap: { type: "token-land", labels: true },
    legends: [{ channel: "size", title: "Usage volume", position: "bottom-right" }],
    heatmapLayer: { minZoom: 0, maxZoom: 2.4, autoFit: true, blend: "max", state: { active: true }, legend: { channel: "layer", title: "Heat density", position: "bottom-left" } },
    bubbleLayer: { minZoom: 1, maxZoom: 8, blend: "normal", state: { active: true, selected: true }, legend: { channel: "layer", title: "Demand bubbles", position: "bottom-left" } },
  })),
  chart("pivot-readiness", "Readiness Pivot Table", "S2", "table", "A heatmap pivot-table scene for multidimensional analysis.", s2PivotSheet({
    id: "pivot-readiness",
    title: "Family readiness pivot",
    description: "Quarter-by-family score grid.",
    data: pivotReadinessRows,
    rows: [{ field: "family", label: "Family", type: "nominal" }],
    columns: [{ field: "quarter", label: "Quarter", type: "ordinal" }],
    values: [{ field: "value", label: "Readiness", format: "number", reducer: "mean" }],
    sort: [{ target: "row", valueField: "value", order: "desc" }],
    drillDown: [{ field: "family", value: "G2", path: ["G2", "Q3"], expanded: true }],
  })),
  chart("mobile-sparkline", "Mobile Sparkline Strip", "F2", "mobile", "A compact mobile-first trend surface inspired by F2.", f2CompactChart({
    id: "mobile-sparkline",
    title: "Mobile activity strip",
    description: "Small-screen area and line marks for touch dashboards.",
    data: weeklyActivity,
    xField: "day",
    yField: "builds",
    xLabel: "Day",
    yLabel: "Builds",
    gestures: [{ type: "tap-tooltip" }, { type: "pan-x" }, { type: "pinch-zoom" }],
  })),
  chart("mobile-wordcloud", "Mobile Term Cloud", "F2", "mobile", "An F2 wordcloud extension rendered with deterministic DX text layout.", f2WordCloud({
    id: "mobile-wordcloud",
    title: "Mobile interaction terms",
    description: "Word-cloud mark for compact chart concepts and gesture vocabulary.",
    data: mobileChartTerms,
    wordField: "term",
    weightField: "weight",
  })),
  chart("x6-diagram-flow", "Editable Diagram Flow", "X6", "flow", "An X6-style diagram flow with ports, terminals, routing, and connector metadata.", {
    id: "x6-diagram-flow",
    title: "Diagram editor flow",
    description: "Ports and edges represented as typed X6-style diagram data.",
    task: "flow",
    family: "X6",
    ...size,
    data: diagramWorkflow.edges.map((edge) => ({ source: edge.source.cell, target: edge.target.cell, relation: edge.label ?? edge.id, value: 1 })),
    diagram: diagramWorkflow,
    graph: diagramModelToGraph(diagramWorkflow),
    marks: [{ id: "diagram-flow", type: "graph", encoding: { source: { field: "source", type: "nominal" }, target: { field: "target", type: "nominal" } } }],
  }),
  chart("l7plot-dot-map", "Map Plot Preset", "L7Plot", "map", "A dot-map preset card for configurable geospatial charts.", l7plotMap({
    id: "l7plot-dot-map",
    title: "Dot map preset",
    description: "L7Plot-style point map using local SVG and theme tokens.",
    data: geoUsagePoints,
    xField: "x",
    yField: "y",
    valueField: "value",
    labelField: "city",
    mapType: "point",
    viewport: { center: [90, 24], zoom: 1.25, minZoom: 0, maxZoom: 8, pitch: 8, bearing: -6 },
    basemap: { type: "graticule", labels: false },
    layerOptions: { minZoom: 0, maxZoom: 7, autoFit: true, state: { active: true }, legend: { channel: "layer", title: "City points", position: "bottom-left" } },
    legends: [{ channel: "size", title: "Point value", position: "bottom-right" }],
  })),
  chart("l7plot-region-readiness", "Region Readiness Choropleth", "L7Plot", "map", "A choropleth preset card for region-value map comparisons.", l7plotChoropleth({
    id: "l7plot-region-readiness",
    title: "Regional readiness",
    description: "L7Plot-style choropleth regions compiled as deterministic SVG paths.",
    data: geoUsageRegions,
    xField: "x",
    yField: "y",
    regionField: "region",
    valueField: "value",
    regions: geoUsageRegionShapes,
    viewport: { center: [88, 22], zoom: 1.2, minZoom: 0, maxZoom: 7, pitch: 6, bearing: -4 },
    basemap: { type: "token-land", labels: true },
    layerOptions: { minZoom: 0, maxZoom: 6.5, autoFit: true, blend: "normal", state: { active: true, selected: true }, legend: { channel: "layer", title: "Readiness regions", position: "bottom-left" } },
    legends: [{ channel: "color", title: "Readiness", position: "bottom-right" }],
  })),
  chart("graphin-investigation", "Graph Investigation App", "Graphin", "relation", "A Graphin-style knowledge graph card with node-detail intent.", {
    id: "graphin-investigation",
    title: "Knowledge graph",
    description: "Graph app shell data rendered by the same graph scene compiler.",
    task: "relation",
    family: "Graphin",
    ...size,
    data: graphEdges,
    graph: {
      nodes: graphNodes,
      edges: graphModelEdges,
      combos: graphCombos,
      layout: { type: "dagre-lite", rankDirection: "LR" },
      behaviors: [{ type: "drag-canvas" }, { type: "zoom-canvas" }, { type: "focus-node", focus: { nodeId: "G6", relationDepth: 2 } }, { type: "activate-relations", activation: { nodeId: "G6", relation: "graph renderer" } }],
      plugins: [{ type: "minimap" }, { type: "context-panel", position: "top-left", target: "selection" }, { type: "tooltip", target: "selection" }],
    },
    marks: [{ id: "knowledge-graph", type: "graph", encoding: { source: { field: "source", type: "nominal" }, target: { field: "target", type: "nominal" } } }],
  }),
  chart("renderer-capability", "Renderer Capability Matrix", "G", "relation", "A low-level renderer capability card inspired by the AntV G engine.", {
    id: "renderer-capability",
    title: "Renderer capability",
    description: "Renderer complexity and proof status for SVG, Canvas, and WebGL-like surfaces.",
    task: "relation",
    family: "G",
    ...size,
    data: runtimeProofs,
    marks: [{ id: "renderer-proof", type: "point", encoding: { x: { field: "complexity", type: "quantitative" }, y: { field: "proof", type: "quantitative" }, size: { field: "complexity", type: "quantitative" }, color: { field: "surface", type: "nominal" } } }],
  }),
  chart("dataset-pipeline", "DataSet Transform Pipeline", "DataSet", "flow", "A data-prep pipeline card for filter, aggregate, scale, and scene steps.", dataSetFlowChart({
    id: "dataset-pipeline",
    title: "Data transform pipeline",
    description: "Data-set style transforms rendered as flow edges.",
    dataset: datasetPipeline,
  })),
  chart("gptvis-recommendations", "GPT-Vis Recommendation Card", "GPTVis", "ai", "A GPT-Vis style recommendation summary scored by a local model.", gptVisPromptChart({
    id: "gptvis-recommendations",
    title: "Prompt-to-chart confidence",
    description: "Deterministic recommendation confidences; no remote model call.",
    request: gptVisPromptRequest,
  })),
  chart("chart-skills-org", "Chart Skills Org Map", "ChartSkills", "relation", "A chart-skills-style org/network graph scene.", chartSkillsGraph({
    id: "chart-skills-org",
    title: "Agent chart skills",
    description: "Chart generation skills mapped as graph relationships.",
    request: agentChartRequest,
    skills: chartSkillCatalog,
  })),
  chart("ant-design-plots-dual-axes", "Plots Dual-Axes Component", "AntDesignPlots", "comparison", "An Ant Design Plots-style dual-axis adapter without package imports.", antDesignDualAxes({
    id: "ant-design-plots-dual-axes",
    title: "Readiness and adoption",
    description: "Column readiness plus line adoption lowered into DX marks.",
    data: packageAdoptionSignals,
    xField: "package",
    columnField: "readiness",
    lineField: "adoption",
    columnLabel: "Readiness",
    lineLabel: "Adoption",
    seriesField: "family",
  })),
  chart("ant-design-plots-heatmap", "Plots Heatmap Component", "AntDesignPlots", "distribution", "An Ant Design Plots heatmap adapter lowered into DX heatmap marks.", antDesignHeatmap({
    id: "ant-design-plots-heatmap",
    title: "Lane coverage heatmap",
    description: "Ant Design Plots-style heatmap config with local source data.",
    data: heatmapCells,
    xField: "task",
    yField: "lane",
    colorField: "value",
  })),
  chart("ant-design-plots-bullet", "Plots Bullet Component", "AntDesignPlots", "comparison", "An Ant Design Plots bullet adapter with target-aware readiness rows.", antDesignBullet({
    id: "ant-design-plots-bullet",
    title: "Readiness bullet",
    description: "Ant Design Plots-style bullet config lowered to local target marks.",
    data: bulletReadiness,
    xField: "metric",
    valueField: "value",
    targetField: "target",
  })),
  chart("ant-design-plots-gauge", "Plots Gauge Component", "AntDesignPlots", "proportion", "An Ant Design Plots gauge adapter for single-signal progress.", antDesignGauge({
    id: "ant-design-plots-gauge",
    title: "Coverage gauge",
    description: "Ant Design Plots-style gauge config with a source-owned target marker.",
    data: gaugeSignals,
    valueField: "value",
    targetField: "target",
    labelField: "metric",
    valueFormat: "percent",
  })),
  chart("ant-design-plots-treemap", "Plots Treemap Component", "AntDesignPlots", "proportion", "An Ant Design Plots treemap adapter over local hierarchy marks.", antDesignTreemap({
    id: "ant-design-plots-treemap",
    title: "Plots treemap",
    description: "Ant Design Plots-style treemap config lowered to DX hierarchy tiles.",
    data: treemapPackages,
    labelField: "label",
    valueField: "value",
  })),
  chart("ant-design-plots-sunburst", "Plots Sunburst Component", "AntDesignPlots", "proportion", "An Ant Design Plots sunburst adapter over local hierarchy rings.", antDesignSunburst({
    id: "ant-design-plots-sunburst",
    title: "Plots sunburst",
    description: "Ant Design Plots-style sunburst config lowered to DX radial hierarchy rings.",
    data: sunburstPackages,
    labelField: "label",
    parentField: "parent",
    levelField: "level",
    valueField: "value",
  })),
  chart("ant-design-plots-sankey", "Plots Sankey Component", "AntDesignPlots", "flow", "An Ant Design Plots sankey adapter over local flow marks.", antDesignSankey({
    id: "ant-design-plots-sankey",
    title: "Plots sankey",
    description: "Ant Design Plots-style sankey config lowered to DX source-target-weight flow.",
    data: packageRelationFlows,
    sourceField: "source",
    targetField: "target",
    weightField: "weight",
  })),
  chart("ant-design-graphs-network", "Graphs Component Network", "AntDesignGraphs", "relation", "An Ant Design Graphs-style adapter backed by the local graph model.", antDesignGraph({
    id: "ant-design-graphs-network",
    title: "Component graph",
    description: "Ant Design Graphs-like component wrapper translated to DX graph metadata.",
    nodes: graphNodes,
    edges: graphModelEdges,
    combos: graphCombos,
    layout: { type: "combo-cluster" },
    behaviors: [{ type: "drag-node" }, { type: "zoom-canvas" }, { type: "focus-node", focus: { nodeId: "G2Plot", relationDepth: 1 } }, { type: "activate-relations", activation: { nodeId: "G2Plot", relation: "preset layer", edgeIds: ["edge-g2plot-g2"] } }],
    plugins: [{ type: "minimap" }, { type: "tooltip", target: "selection" }, { type: "legend", position: "top-right", target: "canvas" }],
  })),
  chart("ant-design-components", "React Wrapper Component Gallery", "AntDesignCharts", "comparison", "An Ant Design Charts-style component-wrapper catalog without React package imports.", antDesignColumn({
    id: "ant-design-components",
    title: "Component wrapper readiness",
    description: "One component, one config, translated into DX-owned chart cards.",
    data: packageReadiness,
    xField: "package",
    yField: "score",
    colorField: "family",
  })),
  chart("ant-design-chart-progress", "React Progress Component", "AntDesignCharts", "proportion", "An Ant Design Charts-style progress component backed by a DX gauge mark.", antDesignProgress({
    id: "ant-design-chart-progress",
    title: "Progress component readiness",
    description: "A component-wrapper progress card without importing Ant Design Charts.",
    data: gaugeSignals,
    valueField: "value",
    targetField: "target",
    labelField: "metric",
    valueFormat: "percent",
  })),
  chart("ai-recommendations", "AI Chart Recommendations", "AVA", "ai", "A local AVA-inspired recommendation card rendered as a chart.", avaAdviceChart({
    id: "ai-recommendations",
    title: "Recommended chart types",
    description: "Static local recommendation confidence, no remote AI dependency.",
    intent: chartAdviceIntent,
    maxRecommendations: 5,
  })),
];

export const chartTasks: Array<{ id: ChartTask; label: string; description: string }> = [
  { id: "comparison", label: "Comparison", description: "Rank and compare values across categories." },
  { id: "trend", label: "Trend", description: "Track change over ordered time or stages." },
  { id: "distribution", label: "Distribution", description: "Reveal spread, density, or matrix intensity." },
  { id: "proportion", label: "Proportion", description: "Show part-to-whole relationships." },
  { id: "relation", label: "Relation", description: "Explore links, networks, and correlations." },
  { id: "flow", label: "Flow", description: "Show movement through stages." },
  { id: "map", label: "Map", description: "Bind values to spatial position." },
  { id: "table", label: "Table", description: "Analyze multidimensional cells." },
  { id: "mobile", label: "Mobile", description: "Compact charts for touch surfaces." },
  { id: "ai", label: "AI", description: "Recommend and generate chart specs." },
  { id: "composition", label: "Composition", description: "Stack, dodge, normalize, and facet views." },
];

export type EcosystemCoverageStatus = "Implemented" | "Adapter" | "Model" | "Reference";

export type EcosystemFamily = {
  family: ChartFamily;
  packageName: string;
  source: string;
  dxBoundary: string;
  coverageStatus: EcosystemCoverageStatus;
  sourceProof: string;
  interactionProof: string;
};

export const ecosystemFamilies: EcosystemFamily[] = [
  { family: "G2", packageName: "@antv/g2", source: "inspirations/antv/G2", dxBoundary: "Grammar, marks, scales, axes, SVG scenes", coverageStatus: "Implemented", sourceProof: "G2 source folders: mark, transform, scale, coordinate, interaction, theme.", interactionProof: "Scene compiler emits keyboard-readable marks and runtime hit targets." },
  { family: "G2Plot", packageName: "@antv/g2plot", source: "inspirations/antv/G2Plot", dxBoundary: "Source-owned preset adapters and config lowering", coverageStatus: "Implemented", sourceProof: "G2Plot plot folders and adaptors are mapped through local preset factories.", interactionProof: "Preset configs lower into shared scene nodes and tooltip/select runtime metadata." },
  { family: "F2", packageName: "@antv/f2", source: "inspirations/antv/F2", dxBoundary: "Mobile/touch chart patterns and wordcloud extension marks", coverageStatus: "Adapter", sourceProof: "F2 package references include compact charts plus f2-wordcloud extensions.", interactionProof: "Mobile viewport and gesture metadata are retained in the chart spec." },
  { family: "S2", packageName: "@antv/s2", source: "inspirations/antv/S2", dxBoundary: "Pivot and heatmap table surfaces", coverageStatus: "Model", sourceProof: "S2 core/react/ssr/vue packages are represented by typed pivot metadata.", interactionProof: "Sort, drill, totals, hierarchy, and cell-hover interactions are source-owned." },
  { family: "G6", packageName: "@antv/g6", source: "inspirations/antv/G6", dxBoundary: "Graph scene and network catalog", coverageStatus: "Model", sourceProof: "G6 graph and extension packages are mapped into local graph models.", interactionProof: "Graph behaviors, plugins, focus state, and layouts are preserved as metadata." },
  { family: "X6", packageName: "@antv/x6", source: "inspirations/antv/X6", dxBoundary: "Diagram editor concepts and ports", coverageStatus: "Model", sourceProof: "X6 editor concepts are represented by typed diagram nodes, ports, and terminals.", interactionProof: "Connector routing and selection metadata lower into graph-compatible scene state." },
  { family: "L7", packageName: "@antv/l7", source: "inspirations/antv/L7", dxBoundary: "Map scene model and geospatial cards", coverageStatus: "Model", sourceProof: "L7 core, map, layers, scene, source, and renderer packages are tracked.", interactionProof: "Viewport, basemap, projection, layer styling, and feature interactions are typed." },
  { family: "L7Plot", packageName: "@antv/l7plot", source: "inspirations/antv/L7Plot", dxBoundary: "Geospatial preset chart cards", coverageStatus: "Adapter", sourceProof: "L7Plot component, l7plot, and composite-layer packages are referenced.", interactionProof: "Dot map, choropleth, and composite layer presets compile into map scene metadata." },
  { family: "Graphin", packageName: "@antv/graphin", source: "inspirations/antv/Graphin", dxBoundary: "Graph app shell and side-panel patterns", coverageStatus: "Model", sourceProof: "Graphin, gi-sdk, and core asset packages are mapped to graph app surfaces.", interactionProof: "Node-detail intent and focused relation state are part of the source-owned graph card." },
  { family: "G", packageName: "@antv/g", source: "inspirations/antv/G", dxBoundary: "Renderer capability matrix", coverageStatus: "Reference", sourceProof: "G renderer packages cover lite, canvas, svg, webgl, plugins, and math utilities.", interactionProof: "Renderer support is exposed through capability rows instead of runtime package imports." },
  { family: "DataSet", packageName: "@antv/data-set", source: "inspirations/antv/data-set", dxBoundary: "Data transform and pipeline helpers", coverageStatus: "Implemented", sourceProof: "DataSet source is represented by local view, transform, and pipeline helpers.", interactionProof: "Pipeline stages produce materialized flow rows and chart-ready derived data." },
  { family: "AVA", packageName: "@antv/ava", source: "inspirations/antv/AVA", dxBoundary: "Source-owned chart advice scoring and explanations", coverageStatus: "Adapter", sourceProof: "AVA analyze/suggest/visualize flows are mapped to a local advice model.", interactionProof: "Recommendation rows include intent, confidence, rationale, and selected state." },
  { family: "GPTVis", packageName: "@antv/gpt-vis", source: "inspirations/antv/GPT-Vis", dxBoundary: "Prompt-to-tool routing, syntax emission, and DX spec generation without package imports", coverageStatus: "Adapter", sourceProof: "GPT-Vis registry and vis syntax are represented by the local chart router.", interactionProof: "Prompt routes emit recommendations, syntax, materialized rows, and generated chart specs." },
  { family: "MCP", packageName: "@antv/mcp-server-chart", source: "inspirations/antv/mcp-server-chart", dxBoundary: "Agent chart request catalog", coverageStatus: "Reference", sourceProof: "MCP chart server package is represented by local agent request flow data.", interactionProof: "Agent request nodes and skill dependencies compile into graph flow metadata." },
  { family: "ChartSkills", packageName: "@antv/chart-visualization-skills", source: "inspirations/antv/chart-visualization-skills", dxBoundary: "Agent chart skills and org-chart examples", coverageStatus: "Reference", sourceProof: "Chart visualization skills and harness packages are mapped to skill graph rows.", interactionProof: "Skill dependencies produce deterministic graph edges and chart workflow summaries." },
  { family: "AntDesignCharts", packageName: "@ant-design/charts", source: "inspirations/antv/ant-design-charts", dxBoundary: "Component wrapper catalog without package imports", coverageStatus: "Adapter", sourceProof: "Ant Design charts packages include charts, plots, graphs, and util packages.", interactionProof: "Component-style configs lower into DX-owned chart specs without React package imports." },
  { family: "AntDesignPlots", packageName: "@ant-design/plots", source: "inspirations/antv/ant-design-charts/packages/plots", dxBoundary: "Plots component configs lowered into DX marks", coverageStatus: "Adapter", sourceProof: "Ant Design plots source has components, core, hooks, context, and interface layers.", interactionProof: "Plot component options lower into the same mark and coordinate scene contracts." },
  { family: "AntDesignGraphs", packageName: "@ant-design/graphs", source: "inspirations/antv/ant-design-charts/packages/graphs", dxBoundary: "Graphs component configs lowered into DX graph models", coverageStatus: "Adapter", sourceProof: "Ant Design graphs package source is mapped to local graph component adapters.", interactionProof: "Graph component configs retain layout, node, edge, and interaction semantics." },
];

export const featuredChartSlugs = ["line-receipts", "stacked-release-work", "faceted-runtime-proof", "pivot-readiness", "sunburst-ecosystem"] as const;

export function getChartBySlug(slug: string): ChartCatalogItem {
  const item = chartCatalog.find((entry) => entry.slug === slug);
  if (!item) {
    throw new Error(`Unknown chart catalog slug: ${slug}`);
  }

  return item;
}
