export const dxBetterAuthForgePackage = {
  packageId: "auth/better-auth",
  officialName: "Authentication",
  aliases: [
    "authentication",
    "better-auth",
    "auth/betterauth",
    "auth/better-auth-next",
  ],
  upstreamPackage: "better-auth",
  upstreamVersion: "1.6.11",
  sourceMirror: "G:\\WWW\\inspirations\\better-auth",
  docsPath: "docs/packages/authentication.md",
  provenance: {
    repository: "https://github.com/better-auth/better-auth",
    sourceSubpath: "packages/better-auth",
    packageJson:
      "G:\\WWW\\inspirations\\better-auth\\packages\\better-auth\\package.json",
    version: "1.6.11",
  },
  sourceSurface: [
    "betterAuth from better-auth",
    "createAuthClient from better-auth/react",
    "toNextJsHandler and nextCookies from better-auth/next-js",
    "auth.api.getSession({ headers }) for server-side session reads",
    "auth.api.listSessions and auth.api.revokeSession helpers",
    "authClient.listSessions() and authClient.revokeSession() client actions",
    "authClient.signIn.social() helper for Google provider launches",
    "authClient.listAccounts(), linkSocial(), unlinkAccount(), and getAccessToken() helpers",
    "authClient.updateUser() and authClient.changeEmail() helpers",
    "authClient.deleteUser() guarded account deletion helper",
    "authClient.signIn.email() and authClient.signUp.email() helpers",
    "authClient.requestPasswordReset(), resetPassword(), changePassword(), and sendVerificationEmail() helpers",
    "BetterAuthOptions database adapter boundary",
  ],
  dependencies: [
    {
      name: "better-auth",
      version: "^1.6.11",
      required: true,
    },
    {
      name: "next",
      version: "^14.0.0 || ^15.0.0 || ^16.0.0",
      required: false,
    },
  ],
  requiredEnv: [
    "BETTER_AUTH_SECRET",
    "BETTER_AUTH_URL",
    "BETTER_AUTH_TRUSTED_ORIGINS",
    "NEXT_PUBLIC_BETTER_AUTH_URL",
  ],
  optionalEnv: [
    "BETTER_AUTH_APP_NAME",
    "BETTER_AUTH_EMAIL_PASSWORD_ENABLED",
    "GOOGLE_CLIENT_ID",
    "GOOGLE_CLIENT_SECRET",
  ],
  appOwnedBoundaries: [
    "Database adapter and migration policy",
    "Session lifetime, cookie, trusted-origin, and revocation policy",
    "OAuth provider credentials, callback URLs, and consent copy",
    "Email delivery, verification, password reset, and account deletion hooks",
    "Profile field policy, account linking UX, and token storage policy",
  ],
  receiptPaths: {
    package: ".dx/forge/receipts/auth-better-auth.json",
    dashboard: ".dx/forge/docs/launch-companions/auth-session-status.md",
    templateReadiness: ".dx/forge/template-readiness/launch-readiness-bundle.json",
  },
  dxCheckVisibility: {
    schema: "dx.forge.package.dx_check_visibility",
    currentStatus: "present",
    statuses: [
      "present",
      "stale",
      "missing-receipt",
      "blocked",
      "unsupported-surface",
    ],
    receiptPath:
      "examples/template/.dx/forge/receipts/auth-better-auth.json",
    monitoredSurfaces: [
      "authentication-account-workflow",
      "authentication-session-status",
    ],
  },
  dashboardUsage: {
    launchRoute: "examples/template/app/page.tsx",
    launchShell: "examples/template/template-shell.tsx",
    sessionStatus: "examples/template/auth-session-status.tsx",
    componentMarker: "better-auth-account-dashboard-workflow",
    sessionStatusMarker: "better-auth-session-status-panel",
    emailSignUpMarker: "data-dx-auth-interaction=\"email-sign-up\"",
    boundaryReviewMarker: "data-dx-auth-interaction=\"mark-boundary-reviewed\"",
    networkGateMarker: "data-dx-auth-network-state",
    emailSignUpHelper: "signUpDxBetterAuthEmail(input)",
  },
  exportedFiles: [
    "auth/better-auth/options.ts",
    "auth/better-auth/server.ts",
    "auth/better-auth/client.ts",
    "auth/better-auth/email-password.ts",
    "auth/better-auth/social.ts",
    "auth/better-auth/accounts.ts",
    "auth/better-auth/profile.ts",
    "auth/better-auth/account-deletion.ts",
    "auth/better-auth/account-security.ts",
    "auth/better-auth/route.ts",
    "auth/better-auth/session.ts",
    "auth/better-auth/session-management.ts",
    "auth/better-auth/dashboard.ts",
    "auth/better-auth/metadata.ts",
    "auth/better-auth/.env.example",
    "auth/better-auth/README.md",
  ],
  materializedFiles: [
    "auth/better-auth/options.ts",
    "auth/better-auth/server.ts",
    "auth/better-auth/client.ts",
    "auth/better-auth/email-password.ts",
    "auth/better-auth/social.ts",
    "auth/better-auth/accounts.ts",
    "auth/better-auth/profile.ts",
    "auth/better-auth/account-deletion.ts",
    "auth/better-auth/account-security.ts",
    "auth/better-auth/route.ts",
    "auth/better-auth/session.ts",
    "auth/better-auth/session-management.ts",
    "auth/better-auth/dashboard.ts",
    "auth/better-auth/metadata.ts",
    "auth/better-auth/.env.example",
  ],
  discovery: {
    dxAdd: "dx add authentication --write",
    nextRouteHelper: "createDxBetterAuthRouteHandlers(auth)",
    serverSessionHelper: "getDxBetterAuthSession(auth)",
    sessionManagementHelper: "listDxBetterAuthSessions(auth)",
    emailPasswordHelper: "signInDxBetterAuthEmail(input)",
    socialSignInHelper: "signInDxBetterAuthSocial(input)",
    accountLinkingHelper: "linkDxBetterAuthSocialAccount(input)",
    profileHelper: "updateDxBetterAuthUserProfile(input)",
    accountDeletionHelper: "deleteDxBetterAuthAccount(input)",
    accountSecurityHelper: "requestDxBetterAuthPasswordReset(input)",
    clientSessionActions: "listSessions()",
    clientFactory: "createDxAuthClient()",
  },
} as const;

export type DxBetterAuthForgePackage = typeof dxBetterAuthForgePackage;
