/* Generated by dx imports sync. */
/* Source-owned IDE contract for DX WWW auto-imports. */

declare module "#components" {
  export { Icon } from "../../components/icons/icon";
  export type { IconProps } from "../../components/icons/icon";
}

declare module "#imports" {
  export { Icon } from "../../components/icons/icon";
  export type { IconProps } from "../../components/icons/icon";
  export { LandingPageContent } from "../../lib/forge/www/landing-page";
}

declare global {
  const Icon: typeof import("../../components/icons/icon")["Icon"];
  const LandingPageContent: typeof import("../../lib/forge/www/landing-page")["LandingPageContent"];
}

export {};
