/* Generated by dx imports sync. */
/* Source-owned IDE contract for DX WWW auto-imports. */

declare module "#components" {
  export { DxMobileCompanionScreen } from "../../components/mobile-companion/companion-screen";
  export { Icon } from "../../components/icons/icon";
  export type { IconProps } from "../../components/icons/icon";
}

declare module "#imports" {
  export { DxMobileCompanionScreen } from "../../components/mobile-companion/companion-screen";
  export { Icon } from "../../components/icons/icon";
  export type { IconProps } from "../../components/icons/icon";
}

declare global {
  const DxMobileCompanionScreen: typeof import("../../components/mobile-companion/companion-screen")["DxMobileCompanionScreen"];
  const Icon: typeof import("../../components/icons/icon")["Icon"];
}

export {};
