export type DxStudioEditOperation =
  | "insert_component"
  | "move_reorder_section"
  | "update_design_token"
  | "update_text_content"
  | "insert_icon_media";

export type DxStudioEditableSurface = {
  id: string;
  selector: string;
  sourceFile: string;
  materializedFile: string;
  packageIds: readonly string[];
  operations: readonly DxStudioEditOperation[];
  interactionSelectors?: readonly string[];
  stateMarkers?: readonly string[];
  receiptPath?: string;
  layoutPolicy: "responsive-design-system-grid";
  absolutePositioning: false;
  noNodeModulesRequired: true;
};

export type DxStudioEditContract = {
  schema: "dx.studio.launch_edit_contract";
  route: "/";
  sourceManifestFile: "examples/template/dx-studio-edit-contract.ts";
  materializedManifestFile: "components/template-app/dx-studio-edit-contract.ts";
  sourceOwned: true;
  noNodeModulesRequired: true;
  layoutPolicy: "responsive-design-system-grid";
  absolutePositioning: false;
  tokenScopeMarker: "data-dx-token-scope";
  operations: readonly {
    operation: DxStudioEditOperation;
    label: string;
    selector: string;
    sourceFile: string;
    responsivePolicy: "use-existing-grid-and-design-tokens";
    writesFiles: true;
    requiresNodeModules: false;
    requiresServerRestart: false;
    requiresPackageInstall: false;
  }[];
  editableSurfaces: readonly DxStudioEditableSurface[];
  surfaces: readonly DxStudioEditableSurface[];
};

export const launchStudioEditOperations = [
  {
    operation: "insert_component",
    label: "Insert a Forge-backed proof component",
    selector: '[data-dx-insert-slot="proof-card-grid"]',
    sourceFile: "examples/template/template-shell.tsx",
    responsivePolicy: "use-existing-grid-and-design-tokens",
    writesFiles: true,
    requiresNodeModules: false,
    requiresServerRestart: false,
    requiresPackageInstall: false,
  },
  {
    operation: "move_reorder_section",
    label: "Move or reorder launch sections",
    selector: '[data-dx-section]',
    sourceFile: "examples/template/template-shell.tsx",
    responsivePolicy: "use-existing-grid-and-design-tokens",
    writesFiles: true,
    requiresNodeModules: false,
    requiresServerRestart: false,
    requiresPackageInstall: false,
  },
  {
    operation: "update_design_token",
    label: "Update launch design tokens",
    selector: '[data-dx-token-scope="template"]',
    sourceFile: "examples/template/template-shell.tsx",
    responsivePolicy: "use-existing-grid-and-design-tokens",
    writesFiles: true,
    requiresNodeModules: false,
    requiresServerRestart: false,
    requiresPackageInstall: false,
  },
  {
    operation: "update_text_content",
    label: "Update launch text or content",
    selector: "[data-dx-editable-text]",
    sourceFile: "examples/template/template-shell.tsx",
    responsivePolicy: "use-existing-grid-and-design-tokens",
    writesFiles: true,
    requiresNodeModules: false,
    requiresServerRestart: false,
    requiresPackageInstall: false,
  },
  {
    operation: "insert_icon_media",
    label: "Insert a source-owned icon or media slot",
    selector: "[data-dx-media-slot]",
    sourceFile: "examples/template/template-shell.tsx",
    responsivePolicy: "use-existing-grid-and-design-tokens",
    writesFiles: true,
    requiresNodeModules: false,
    requiresServerRestart: false,
    requiresPackageInstall: false,
  },
] as const satisfies DxStudioEditContract["operations"];

const motionDashboardInteractionSelectors = [
  '[data-dx-motion-interaction="advance-stage"]',
  '[data-dx-motion-interaction="reverse-order"]',
  '[data-dx-motion-interaction="move-stage-previous"]',
  '[data-dx-motion-interaction="move-stage-next"]',
  '[data-dx-motion-interaction="reset-proof"]',
  '[data-dx-motion-interaction="toggle-reduced-motion"]',
] as const;

const motionDashboardStateMarkers = [
  "data-dx-motion-state",
  "data-dx-motion-progress",
  "data-dx-motion-order",
  "data-dx-motion-order-available",
  "data-dx-motion-keyboard-reorder",
  "data-dx-motion-keyboard-state",
  "data-dx-motion-preference-storage",
  "data-dx-motion-storage-key",
  "data-dx-motion-reduced",
] as const;

const motionDashboardReceiptPath =
  "examples/template/.dx/forge/receipts/2026-05-22-animation-motion-dashboard-workflow.json" as const;

const dxCheckPanelStateMarkers = [
  "data-dx-check-panel",
  "data-dx-check-command",
  "data-dx-check-receipt-path",
  "data-dx-check-schema",
  "data-dx-check-score-max",
  "data-dx-zed-panel-schema",
  "data-dx-check-view-model-schema",
  "data-dx-check-view-model-status",
  "data-dx-check-score-state",
  "data-dx-check-empty-state",
  "data-dx-check-bucket-count",
  "data-dx-check-package-lane-count",
  "data-dx-check-style-evidence-count",
  "data-dx-check-style-evidence-row",
  "data-dx-check-style-evidence-status",
  "data-dx-check-style-evidence-receipt-path",
  "data-dx-check-style-evidence-fixture-path",
  "data-dx-check-style-evidence-zed",
  "data-dx-check-style-evidence-class-count",
  "data-dx-check-style-evidence-selector-class-count",
  "data-dx-check-style-evidence-selector-class-examples",
  "data-dx-check-style-evidence-state-alias-count",
  "data-dx-check-style-evidence-state-alias-examples",
  "data-dx-check-style-evidence-full-autoprefixer-parity",
  "data-dx-check-style-evidence-full-tailwind-postcss-output-parity",
  "data-dx-check-style-evidence-drift",
  "data-dx-check-style-evidence-drift-state",
  "data-dx-check-style-evidence-drift-loader",
  "data-dx-check-style-evidence-drift-helper",
  "data-dx-check-style-evidence-drift-states",
  "data-dx-style-package-panel",
  "data-dx-style-package-panel-read-model",
  "data-dx-style-package-panel-drift-state",
  "data-dx-style-package-panel-drift-status",
  "data-dx-style-package-panel-drift-mismatch-fields",
  "data-dx-style-package-panel-readiness-receipt",
  "data-dx-style-package-ownership-read-model",
  "data-dx-style-package-ownership-packages",
  "data-dx-style-package-ownership-generated-classes",
  "data-dx-style-package-ownership-unsupported-classes",
  "data-dx-check-package-lane-template",
  "data-dx-check-package-lane-row",
  "data-dx-check-package-lane-status",
  "data-dx-check-package-lane-receipt-status",
  "data-dx-check-package-lane-name",
  "data-dx-check-package-lane-upstream-package",
  "data-dx-check-package-lane-source-mirror",
  "data-dx-check-package-lane-receipt-path",
  "data-dx-check-package-lane-dx-style-status",
  "data-dx-style-surface",
  "data-dx-token-scope",
  "data-dx-check-package-lane-hash-refresh-status",
  "data-dx-check-package-lane-hash-refresh-helper",
  "data-dx-check-package-lane-hash-refresh-json-command",
  "data-dx-check-package-lane-hash-refresh-zed",
  "data-dx-check-package-lane-hash-refresh-tracked-files",
  "data-dx-check-package-lane-hash-refresh-stale-files",
  "data-dx-check-package-lane-hash-refresh-missing-files",
  "data-dx-check-package-lane-hash-refresh-current-file-list",
  "data-dx-check-package-lane-hash-refresh-stale-file-list",
  "data-dx-check-package-lane-hash-refresh-missing-file-list",
  "data-dx-check-package-lane-hash-refresh-stale-mirror-file-list",
  "data-dx-check-package-lane-hash-refresh-missing-mirror-file-list",
  "data-dx-check-package-lane-hash-refresh-current-metric",
  "data-dx-check-package-lane-hash-refresh-stale-metric",
  "data-dx-check-package-lane-hash-refresh-missing-metric",
  "data-dx-check-blocker-count",
  "data-dx-check-warning-count",
  "data-dx-check-quick-fix-count",
  "data-dx-check-last-run",
] as const;

const forgeSafetyArchiveStateMarkers = [
  "data-dx-safety-archive-contract",
  "data-dx-forge-status-surface",
  "data-dx-zed-surface",
  "data-dx-safety-archive-operation",
  "data-dx-safety-archive-state",
  "data-dx-safety-archive-safe-delete",
  "data-dx-safety-archive-package-count",
  "data-dx-safety-archive-covered-packages",
  "data-dx-safety-archive-missing-packages",
  "data-dx-safety-archive-rollback-coverage",
  "data-dx-safety-archive-receipt-count",
  "data-dx-safety-archive-directory",
  "data-dx-safety-archive-boundary",
  "data-dx-safety-archive-runbook-source",
  "data-dx-safety-archive-runbook-fixture",
  "data-dx-safety-archive-runbook-guard",
  "data-dx-safety-archive-runbook-command",
  "data-dx-safety-archive-runbook-policy",
] as const;

export const launchStudioEditableSurfaces = [
  {
    id: "hero-section",
    selector: '[data-dx-section="hero"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: ["animation/motion", "3d/launch-scene"],
    operations: ["move_reorder_section", "update_design_token", "update_text_content"],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "launch-hero",
    selector: '[data-dx-component="launch-hero"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: ["i18n/next-intl", "animation/motion"],
    operations: [
      "update_text_content",
      "update_design_token",
      "insert_icon_media",
    ],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "dx-check-health-panel",
    selector: '[data-dx-component="dx-check-health-panel"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: [
      "shadcn/ui/button",
      "reactive/store",
      "payments/stripe-js",
      "db/drizzle-sqlite",
      "validation/zod",
      "forms/react-hook-form",
      "automations/n8n",
      "i18n/next-intl",
      "supabase/client",
      "instantdb/react",
      "api/trpc",
      "ai/vercel-ai",
      "wasm/bindgen",
      "3d/launch-scene",
      "content/fumadocs-next",
    ],
    operations: ["move_reorder_section", "update_text_content"],
    interactionSelectors: [
      '[data-dx-check-command="dx check --latest-receipt --json"]',
      '[data-dx-check-panel="latest-receipt"]',
    ],
    stateMarkers: dxCheckPanelStateMarkers,
    receiptPath: ".dx/receipts/check/check-latest.json",
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "forge-safety-archive-status",
    selector: '[data-dx-component="forge-safety-archive-status"]',
    sourceFile: "tools/launch/runtime-template/pages/index.html",
    materializedFile: "pages/index.html",
    packageIds: ["migration/static-site"],
    operations: ["move_reorder_section", "update_text_content"],
    stateMarkers: forgeSafetyArchiveStateMarkers,
    receiptPath: ".dx/forge/receipts/safety",
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "next-intl-dashboard-locale-workflow",
    selector: '[data-dx-component="next-intl-dashboard-locale-workflow"]',
    sourceFile: "examples/template/next-intl-dashboard-locale.tsx",
    materializedFile: "components/template-app/next-intl-dashboard-locale.tsx",
    packageIds: ["i18n/next-intl"],
    operations: [
      "move_reorder_section",
      "update_design_token",
      "update_text_content",
      "insert_icon_media",
    ],
    interactionSelectors: [
      '[data-dx-intl-action="switch-dashboard-locale"]',
      '[data-dx-intl-action="prepare-dashboard-intl-receipt"]',
      '[data-dx-intl-action="preview-localized-route"]',
      '[data-dx-intl-action="review-alternate-link"]',
      '[data-dx-intl-copy-target="format-preview"]',
      '[data-dx-intl-copy-target="price-preview"]',
      "[data-dx-intl-locale-option]",
      "[data-dx-intl-copy-target]",
      "[data-dx-intl-readiness-copy]",
    ],
    stateMarkers: [
      "[data-dx-dashboard-copy-locale]",
      "[data-dx-intl-receipt-state]",
      "[data-dx-intl-receipt-locale]",
      "[data-dx-intl-receipt-route]",
      "[data-dx-intl-receipt-number-source]",
      "[data-dx-intl-alternate-links]",
      "[data-dx-intl-alternate-locale]",
      "[data-dx-intl-alternate-href]",
      "[data-dx-intl-hreflang]",
      "[data-dx-intl-locale-prefix]",
      "[data-dx-intl-format-preview]",
      "[data-dx-intl-format-source-api]",
      "[data-dx-intl-format-time-zone]",
      "[data-dx-intl-number-preview]",
      "[data-dx-intl-number-source-api]",
      "[data-dx-intl-number-currency]",
    ],
    receiptPath:
      "examples/template/.dx/forge/receipts/2026-05-22-i18n-next-intl-dashboard-locale.json",
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "next-intl-dashboard-message-contract",
    selector: '[data-dx-intl-message-namespace="LaunchDashboard"]',
    sourceFile:
      "examples/template/next-intl-dashboard-locale-contract.ts",
    materializedFile:
      "components/template-app/next-intl-dashboard-locale-contract.ts",
    packageIds: ["i18n/next-intl"],
    operations: ["update_text_content"],
    interactionSelectors: [
      "[data-dx-intl-copy-target]",
      "[data-dx-intl-readiness-copy]",
    ],
    stateMarkers: [
      "data-dx-intl-message-namespace",
      "data-dx-dashboard-copy-locale",
      "data-dx-intl-route-preview",
      "data-dx-intl-plan-label",
      "data-dx-intl-support-sla",
      "data-dx-intl-alternate-links",
      "data-dx-intl-alternate-locale",
      "data-dx-intl-alternate-href",
      "data-dx-intl-hreflang",
      "data-dx-intl-locale-prefix",
      "data-dx-intl-format-preview",
      "data-dx-intl-format-source-api",
      "data-dx-intl-format-time-zone",
      "data-dx-intl-number-preview",
      "data-dx-intl-number-source-api",
      "data-dx-intl-number-currency",
    ],
    receiptPath:
      "examples/template/.dx/forge/receipts/2026-05-22-i18n-next-intl-dashboard-locale.json",
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "proof-card-grid",
    selector: '[data-dx-insert-slot="proof-card-grid"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: [
      "auth/better-auth",
      "state/zustand",
      "tanstack/query",
      "validation/zod",
      "forms/react-hook-form",
      "payments/stripe-js",
      "supabase/client",
      "db/drizzle-sqlite",
      "instantdb/react",
      "content/fumadocs-next",
      "content/react-markdown",
      "automations/n8n",
    ],
    operations: ["insert_component", "move_reorder_section", "update_text_content"],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "shadcn-dashboard-controls",
    selector: '[data-dx-component="shadcn-dashboard-controls"]',
    sourceFile: "examples/template/shadcn-dashboard-controls.tsx",
    materializedFile: "components/template-app/shadcn-dashboard-controls.tsx",
    packageIds: [
      "shadcn/ui/button",
      "shadcn/ui/badge",
      "shadcn/ui/card",
      "shadcn/ui/field",
      "shadcn/ui/input",
      "shadcn/ui/textarea",
      "shadcn/ui/item",
      "shadcn/ui/separator",
    ],
    operations: ["move_reorder_section", "update_design_token", "update_text_content"],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "connected-capability-map",
    selector: '[data-dx-component="launch-connected-capability-map"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: [
      "auth/better-auth",
      "state/zustand",
      "tanstack/query",
      "forms/react-hook-form",
      "validation/zod",
      "payments/stripe-js",
      "3d/launch-scene",
      "animation/motion",
      "content/fumadocs-next",
      "content/react-markdown",
      "automations/n8n",
      "supabase/client",
      "db/drizzle-sqlite",
      "instantdb/react",
      "api/trpc",
    ],
    operations: ["insert_component", "move_reorder_section", "update_text_content"],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "supabase-account-data-dashboard",
    selector: '[data-dx-section="account-data-dashboard"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: ["supabase/client", "api/trpc", "wasm/bindgen"],
    operations: [
      "insert_component",
      "move_reorder_section",
      "update_text_content",
      "insert_icon_media",
    ],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "supabase-profile-workflow",
    selector: '[data-dx-component="supabase-profile-workflow"]',
    sourceFile: "examples/template/supabase-profile-workflow.tsx",
    materializedFile: "components/template-app/supabase-profile-workflow.tsx",
    packageIds: ["supabase/client"],
    operations: [
      "move_reorder_section",
      "update_text_content",
      "insert_icon_media",
    ],
    interactionSelectors: [
      '[data-dx-supabase-action="load-profile-fixture"]',
      '[data-dx-supabase-action="prepare-profile-upsert"]',
    ],
    stateMarkers: [
      "data-dx-supabase-config-status",
      "data-dx-supabase-receipt-state",
      "data-dx-supabase-profile-field",
      "data-dx-supabase-profile-loaded",
    ],
    receiptPath:
      "examples/template/.dx/forge/receipts/2026-05-22-supabase-client-dashboard-workflow.json",
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "supabase-schema-query-workflow",
    selector: '[data-dx-component="supabase-schema-query-workflow"]',
    sourceFile: "examples/template/data-status.tsx",
    materializedFile: "components/template-app/data-status.tsx",
    packageIds: ["supabase/client", "db/drizzle-sqlite"],
    operations: [
      "move_reorder_section",
      "update_text_content",
      "insert_icon_media",
    ],
    interactionSelectors: [
      '[data-dx-supabase-action="run-local-schema-query"]',
      "[data-dx-supabase-query-operation]",
      "[data-dx-supabase-receipt-path]",
    ],
    stateMarkers: [
      "data-dx-supabase-query-state",
      "data-dx-supabase-query-operation",
      "data-dx-supabase-table",
      "data-dx-supabase-row",
    ],
    receiptPath:
      "examples/template/.dx/forge/receipts/2026-05-22-supabase-client-dashboard-workflow.json",
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "better-auth-account-dashboard-workflow",
    selector: '[data-dx-component="better-auth-account-dashboard-workflow"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: ["auth/better-auth"],
    operations: [
      "insert_component",
      "move_reorder_section",
      "update_text_content",
      "insert_icon_media",
    ],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "state-query-proof",
    selector: '[data-dx-section="motion-metrics"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: ["state/zustand", "tanstack/query", "animation/motion"],
    operations: ["move_reorder_section", "update_design_token", "update_text_content"],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "tanstack-query-dashboard-data",
    selector: '[data-dx-component="tanstack-query-dashboard-data-workflow"]',
    sourceFile: "examples/template/query-cache-status.tsx",
    materializedFile: "components/template-app/query-cache-status.tsx",
    packageIds: ["tanstack/query"],
    operations: [
      "move_reorder_section",
      "update_design_token",
      "update_text_content",
      "insert_icon_media",
    ],
    interactionSelectors: [
      '[data-dx-query-action="refresh-dashboard-data"]',
      '[data-dx-query-dashboard-queue="package-readiness"]',
    ],
    stateMarkers: [
      "data-dx-query-dashboard-source",
      "data-dx-query-dashboard-queue",
      "data-dx-query-package-id",
      "data-dx-query-package-role",
      "data-dx-query-package-status",
    ],
    receiptPath:
      "examples/template/.dx/forge/receipts/2026-05-22-tanstack-query-dashboard-data.json",
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "launch-dashboard-state-workflow",
    selector: '[data-dx-component="launch-dashboard-state-workflow"]',
    sourceFile: "examples/template/state-zustand-dashboard.tsx",
    materializedFile: "components/template-app/state-zustand-dashboard.tsx",
    packageIds: ["state/zustand"],
    operations: [
      "move_reorder_section",
      "update_design_token",
      "update_text_content",
      "insert_icon_media",
    ],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "launch-dashboard-state-shell",
    selector: '[data-dx-component="launch-dashboard-state-shell"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: ["state/zustand"],
    operations: [
      "move_reorder_section",
      "update_design_token",
      "update_text_content",
    ],
    interactionSelectors: [
      '[data-dx-zustand-action="set-dashboard-density"]',
      '[data-dx-zustand-action="select-dashboard-focus"]',
      '[data-dx-zustand-action="toggle-command-hints"]',
      '[data-dx-zustand-action="save-dashboard-settings"]',
      '[data-dx-zustand-action="reset-dashboard-settings"]',
      '[data-dx-zustand-action="rehydrate-dashboard-settings"]',
    ],
    stateMarkers: [
      "data-dx-zustand-dashboard-density",
      "data-dx-zustand-dashboard-focus",
      "data-dx-zustand-command-hints",
      "data-dx-zustand-dashboard-saved-at",
      "data-dx-zustand-hydration-event",
      "data-dx-zustand-rehydrate-state",
    ],
    receiptPath:
      "examples/template/.dx/forge/receipts/2026-05-22-state-zustand-dashboard-workflow.json",
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "better-auth-session-status-panel",
    selector: '[data-dx-component="better-auth-session-status-panel"]',
    sourceFile: "examples/template/auth-session-status.tsx",
    materializedFile: "components/template-app/auth-session-status.tsx",
    packageIds: ["auth/better-auth"],
    operations: ["move_reorder_section", "update_text_content", "insert_icon_media"],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "motion-dashboard-workflow",
    selector: '[data-dx-component="launch-motion-dashboard-workflow"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: ["animation/motion"],
    operations: [
      "move_reorder_section",
      "update_design_token",
      "update_text_content",
      "insert_icon_media",
    ],
    interactionSelectors: motionDashboardInteractionSelectors,
    stateMarkers: motionDashboardStateMarkers,
    receiptPath: motionDashboardReceiptPath,
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "motion-interaction-proof",
    selector: '[data-dx-component="motion-interaction-proof"]',
    sourceFile: "examples/template/motion-interaction-proof.tsx",
    materializedFile: "components/template-app/motion-interaction-proof.tsx",
    packageIds: ["animation/motion"],
    operations: ["move_reorder_section", "update_design_token", "update_text_content"],
    interactionSelectors: motionDashboardInteractionSelectors,
    stateMarkers: [
      ...motionDashboardStateMarkers,
      "data-dx-motion-policy-status",
    ],
    receiptPath: motionDashboardReceiptPath,
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "wasm-compute-dashboard-workflow",
    selector: '[data-dx-component="launch-wasm-compute-dashboard-workflow"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: ["wasm/bindgen"],
    operations: [
      "move_reorder_section",
      "update_text_content",
      "insert_icon_media",
    ],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "scene-rendering-proof",
    selector: '[data-dx-media-slot="launch-scene"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: ["3d/launch-scene", "animation/motion"],
    operations: ["update_design_token", "insert_icon_media"],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "form-validation-proof",
    selector: '[data-dx-component="form-zod-proof"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: ["forms/react-hook-form", "validation/zod"],
    operations: ["move_reorder_section", "update_text_content"],
    interactionSelectors: [
      '[data-dx-zod-settings-action="load-invalid"]',
      '[data-dx-zod-settings-action="load-valid"]',
      '[data-dx-zod-settings-action="validate"]',
      "[data-dx-zod-settings-field]",
      '[data-dx-zod-dashboard-receipt-api="createDxDashboardSettingsReceipt"]',
    ],
    stateMarkers: [
      "data-dx-zod-settings-state",
      "data-dx-zod-settings-issues",
      "data-dx-zod-settings-output",
      "data-dx-zod-settings-submitted",
      "data-dx-zod-dashboard-field-state",
      "data-dx-zod-dashboard-field-error",
    ],
    receiptPath:
      "examples/template/.dx/forge/receipts/2026-05-22-validation-zod-dashboard-settings.json",
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "launch-billing-checkout-workflow",
    selector: '[data-dx-component="launch-billing-checkout-workflow"]',
    sourceFile: "examples/template/payments-status.tsx",
    materializedFile: "components/template-app/payments-status.tsx",
    packageIds: ["payments/stripe-js"],
    operations: [
      "insert_component",
      "move_reorder_section",
      "update_text_content",
    ],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "automation-dashboard-workflow",
    selector: '[data-dx-component="launch-automation-dashboard-workflow"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: ["automations/n8n"],
    operations: ["move_reorder_section", "update_text_content"],
    interactionSelectors: [
      '[data-dx-automation-safe-action="prepare-dry-run-receipt"]',
      '[data-dx-automation-safe-action="prepare-zed-run-handoff"]',
      "[data-dx-automation-intent-input]",
      "[data-dx-automation-receipt-intent]",
      "[data-dx-automation-run-receipt-intent]",
      "[data-dx-automation-credential-schema]",
      "[data-dx-automation-required-env]",
      "[data-dx-automation-workflow-node-readiness]",
    ],
    stateMarkers: [
      "data-dx-automation-dashboard-state",
      "data-dx-automation-selected-connector",
      "data-dx-automation-credential-schema",
      "data-dx-automation-auth-kind",
      "data-dx-automation-credential-type",
      "data-dx-automation-required-env",
      "data-dx-automation-workflow-node-readiness",
      "data-dx-automation-usable-as-tool",
      "data-dx-automation-receipt-intent",
      "data-dx-automation-run-receipt-intent",
      "data-dx-automation-run-receipt-path",
    ],
    receiptPath: "G:/Dx/.dx/receipts/automations/launch-release-notification.json",
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "automation-mission-summary",
    selector: '[data-dx-component="launch-automation-mission-summary"]',
    sourceFile: "examples/template/automation-mission-summary.tsx",
    materializedFile: "components/template-app/automation-mission-summary.tsx",
    packageIds: ["automations/n8n"],
    operations: ["move_reorder_section", "update_text_content"],
    interactionSelectors: [
      '[data-dx-component="launch-automation-dashboard-workflow"]',
      '[data-dx-automation-safe-action="prepare-dry-run-receipt"]',
      '[data-dx-automation-safe-action="prepare-zed-run-handoff"]',
    ],
    stateMarkers: [
      "data-dx-automation-dashboard-state",
      "data-dx-automation-selected-connector",
      "data-dx-automation-workflow-node-readiness",
      "data-dx-automation-workflow-status",
      "data-dx-automation-auth-kinds",
      "data-dx-automation-credential-types",
      "data-dx-automation-required-env",
    ],
    receiptPath: "G:/Dx/.dx/receipts/automations/launch-release-notification.json",
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "instantdb-dashboard-workflow",
    selector: '[data-dx-component="launch-instantdb-dashboard-workflow"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: ["instantdb/react"],
    operations: ["move_reorder_section", "update_text_content", "insert_icon_media"],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "database-backend-proof",
    selector: '[data-dx-component="database-backend-proof"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: [
      "supabase/client",
      "db/drizzle-sqlite",
      "instantdb/react",
      "api/trpc",
    ],
    operations: ["move_reorder_section", "update_text_content"],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "launch-drizzle-data-workflow",
    selector: '[data-dx-component="launch-drizzle-data-workflow"]',
    sourceFile: "examples/template/drizzle-query-proof.tsx",
    materializedFile: "components/template-app/drizzle-query-proof.tsx",
    packageIds: ["db/drizzle-sqlite"],
    operations: ["move_reorder_section", "update_text_content"],
    interactionSelectors: [
      '[data-dx-drizzle-action="select-read-model"]',
      '[data-dx-drizzle-action="preview-query-plan"]',
      '[data-dx-drizzle-action="apply-read-model"]',
      '[data-dx-dashboard-target="mission-control-database"]',
    ],
    stateMarkers: [
      "data-dx-drizzle-status",
      "data-dx-drizzle-read-model",
      "data-dx-drizzle-query-plan-id",
      "data-dx-backend-status",
      "data-dx-backend-detail",
      "data-dx-drizzle-receipt-path",
      "data-dx-drizzle-receipt-state",
      "data-dx-drizzle-runtime-dependencies",
    ],
    receiptPath: "examples/template/.dx/forge/receipts/2026-05-22-db-drizzle-sqlite-dashboard-workflow.json",
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "launch-trpc-api-dashboard-workflow",
    selector: '[data-dx-component="launch-trpc-api-dashboard-workflow"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: ["api/trpc"],
    operations: [
      "move_reorder_section",
      "update_text_content",
      "insert_icon_media",
    ],
    interactionSelectors: [
      '[data-dx-trpc-action="check-health"]',
      '[data-dx-trpc-action="prepare-launch-event"]',
      '[data-trpc-interaction="health-query"]',
      '[data-trpc-interaction="local-launch-event-mutation"]',
    ],
    stateMarkers: [
      "data-dx-trpc-workflow",
      "data-dx-trpc-action",
      "data-trpc-interaction",
      "data-trpc-mutation-state",
      "data-dx-trpc-receipt-state",
      "data-dx-trpc-request-id",
    ],
    receiptPath: "examples/template/.dx/forge/receipts/2026-05-22-api-trpc-dashboard-workflow.json",
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "launch-dashboard-state-workflow",
    selector: '[data-dx-component="launch-dashboard-state-workflow"]',
    sourceFile: "examples/template/state-zustand-dashboard.tsx",
    materializedFile: "components/template-app/state-zustand-dashboard.tsx",
    packageIds: ["state/zustand"],
    operations: [
      "move_reorder_section",
      "update_design_token",
      "update_text_content",
    ],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "trpc-launch-health-workflow",
    selector: '[data-dx-component="trpc-launch-health-workflow"]',
    sourceFile: "examples/template/trpc-launch-health.tsx",
    materializedFile: "components/template-app/trpc-launch-health.tsx",
    packageIds: ["api/trpc"],
    operations: ["move_reorder_section", "update_text_content"],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "docs-help-changelog-workflow",
    selector: '[data-dx-component="launch-fumadocs-docs-workflow"]',
    sourceFile: "examples/template/docs-status.tsx",
    materializedFile: "components/template-app/docs-status.tsx",
    packageIds: ["content/fumadocs-next", "content/react-markdown"],
    operations: [
      "insert_component",
      "move_reorder_section",
      "update_text_content",
      "insert_icon_media",
    ],
    interactionSelectors: [
      '[data-dx-fumadocs-action="safe-local-route-preview"]',
      "[data-dx-fumadocs-page-option]",
      '[data-dx-fumadocs-rendered-markdown="active-page"]',
      '[data-dx-fumadocs-changelog="launch-docs"]',
    ],
    stateMarkers: [
      "data-dx-fumadocs-selected-page",
      "data-dx-fumadocs-rendered-route",
      "data-dx-fumadocs-local-response",
      "data-dx-fumadocs-receipt-route",
      "data-dx-fumadocs-toc-count",
      "data-dx-fumadocs-missing-config",
      "data-dx-docs-openapi-code-usage",
      "data-dx-docs-openapi-proxy",
    ],
    receiptPath:
      "examples/template/.dx/forge/receipts/2026-05-22-content-fumadocs-dashboard-workflow.json",
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  {
    id: "package-catalog",
    selector: '[data-dx-section="package-catalog"]',
    sourceFile: "examples/template/template-shell.tsx",
    materializedFile: "components/template-app/template-shell.tsx",
    packageIds: ["shadcn/ui/item"],
    operations: ["move_reorder_section", "update_text_content"],
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
] as const satisfies readonly DxStudioEditableSurface[];

export const launchStudioEditContract = {
  schema: "dx.studio.launch_edit_contract",
  route: "/",
  sourceManifestFile: "examples/template/dx-studio-edit-contract.ts",
  materializedManifestFile: "components/template-app/dx-studio-edit-contract.ts",
  sourceOwned: true,
  noNodeModulesRequired: true,
  layoutPolicy: "responsive-design-system-grid",
  absolutePositioning: false,
  tokenScopeMarker: "data-dx-token-scope",
  operations: launchStudioEditOperations,
  editableSurfaces: launchStudioEditableSurfaces,
  surfaces: launchStudioEditableSurfaces,
} as const satisfies DxStudioEditContract;

export function dxStudioEditContractSummary() {
  return {
    schema: launchStudioEditContract.schema,
    operations: launchStudioEditContract.operations.length,
    surfaces: launchStudioEditContract.editableSurfaces.length,
    noNodeModulesRequired: launchStudioEditContract.noNodeModulesRequired,
  };
}
