import {
  templateCatalogSummary,
  launchPackageCatalog,
  launchPackageRoleSummary,
} from "./package-catalog";
import {
  aiSdkPackageVisibility,
  authenticationPackageVisibility,
  automationConnectorsPackageVisibility,
  backendPlatformClientPackageVisibility,
  dataFetchingCachePackageVisibility,
  databaseOrmPackageVisibility,
  documentationSystemPackageVisibility,
  formsPackageVisibility,
  internationalizationPackageVisibility,
  launchForgePackageRows,
  markdownMdxContentPackageVisibility,
  motionAnimationPackageVisibility,
  paymentsPackageVisibility,
  readLaunchForgePackageStatus,
  reactiveStorePackageVisibility,
  realtimeAppDatabasePackageVisibility,
  stateManagementPackageVisibility,
  threeDSceneSystemPackageVisibility,
  typeSafeApiPackageVisibility,
  uiComponentsPackageVisibility,
  validationSchemasPackageVisibility,
  webAssemblyBridgePackageVisibility,
} from "./forge-package-status-read-model";

const receiptBackedStatus = readLaunchForgePackageStatus();

export const launchForgePackageStatus = {
  schema: "dx.www.template.forge_package_status",
  generatedBy: "examples/template/forge-package-status.ts",
  readModelSource: "examples/template/forge-package-status-read-model.ts",
  packageStatusReceipt: ".dx/forge/package-status.json",
  packageLock: ".dx/forge/package-lock.json",
  packageLockState: receiptBackedStatus.packageLock.state,
  packageLockGenerator: "examples/template/forge-package-lock.ts",
  packageSourceManifest: receiptBackedStatus.packageLock.manifestPath,
  packageAddReceipts: receiptBackedStatus.packages
    .map((packageEntry) => packageEntry.packageReceiptPath)
    .filter((receiptPath): receiptPath is string => Boolean(receiptPath)),
  packageCaches: receiptBackedStatus.cache.manifests.map((manifestPath) =>
    manifestPath.replace(/\/manifest\.json$/, ""),
  ),
  packageSource: "launchPackageCatalog",
  packagePolicy: receiptBackedStatus.packagePolicy,
  noNodeModulesRequired: receiptBackedStatus.noNodeModulesRequired,
  lockedPackageCount: receiptBackedStatus.dashboardSummary.lockedPackageCount,
  lockedPackageNames: receiptBackedStatus.dashboardSummary.lockedPackageNames,
  lockedMediaAssetCount: receiptBackedStatus.dashboardSummary.mediaAssetCount,
  vcsStatus: receiptBackedStatus.vcsStatus,
  remoteStatus: receiptBackedStatus.remoteStatus,
  remoteObjectHeadHealth: receiptBackedStatus.remoteObjectHeadHealth,
  mediaStatus: receiptBackedStatus.mediaStatus,
  safetyArchiveStatus: receiptBackedStatus.safetyArchive,
  configuredRemoteCount: receiptBackedStatus.dashboardSummary.remoteCount,
  remoteObjectHeadHealthBlockingCount:
    receiptBackedStatus.dashboardSummary.remoteObjectHeadHealthBlockingCount,
  dxCheckMetrics: receiptBackedStatus.dxCheckMetrics,
  zedReceiptSurfaces: receiptBackedStatus.zedReceiptSurfaces,
  packageLaneVisibility: receiptBackedStatus.packageLaneVisibility,
  uiComponentsVisibility: uiComponentsPackageVisibility,
  stateManagementVisibility: stateManagementPackageVisibility,
  dataFetchingCacheVisibility: dataFetchingCachePackageVisibility,
  reactiveStoreVisibility: reactiveStorePackageVisibility,
  databaseOrmVisibility: databaseOrmPackageVisibility,
  realtimeAppDatabaseVisibility: realtimeAppDatabasePackageVisibility,
  markdownMdxContentVisibility: markdownMdxContentPackageVisibility,
  documentationSystemVisibility: documentationSystemPackageVisibility,
  validationSchemasVisibility: validationSchemasPackageVisibility,
  authenticationVisibility: authenticationPackageVisibility,
  internationalizationVisibility: internationalizationPackageVisibility,
  typeSafeApiVisibility: typeSafeApiPackageVisibility,
  aiSdkVisibility: aiSdkPackageVisibility,
  formsVisibility: formsPackageVisibility,
  paymentsVisibility: paymentsPackageVisibility,
  backendPlatformClientVisibility: backendPlatformClientPackageVisibility,
  automationConnectorsVisibility: automationConnectorsPackageVisibility,
  webAssemblyBridgeVisibility: webAssemblyBridgePackageVisibility,
  threeDSceneSystemVisibility: threeDSceneSystemPackageVisibility,
  motionAnimationVisibility: motionAnimationPackageVisibility,
  receiptBackedStatus,
  summary: templateCatalogSummary(),
  roleSummary: launchPackageRoleSummary(),
  packageRows: launchForgePackageRows(),
  packages: launchPackageCatalog.map((item) => ({
    packageId: item.packageId,
    role: item.role,
    maturity: item.maturity,
    command: item.command,
    requiredEnv: item.requiredEnv ?? [],
    receiptPaths: item.receiptPaths ?? [],
    sourceMirror: item.sourceMirror ?? null,
    exportedFiles: item.exportedFiles ?? [],
    appOwnedBoundaries: item.appOwnedBoundaries,
  })),
} as const;

export type LaunchForgePackageStatus = typeof launchForgePackageStatus;
