import {
  templateCatalogSummary,
  launchPackageCatalog,
  requiredLaunchEnv,
} from "./package-catalog";
import { launchForgePackageStatus } from "./forge-package-status";

export const launchRouteMaterializedFiles = [
  "app/page.tsx",
  "components/template-app/template-route-contract.ts",
  "components/template-app/dx-studio-edit-contract.ts",
  "components/template-app/shadcn-dashboard-controls-contract.tsx",
  "components/template-app/shadcn-dashboard-controls.tsx",
  "components/template-app/automations-status.tsx",
  "components/template-app/automation-mission-summary.tsx",
  "components/template-app/automations/automations-metadata.ts",
  "components/template-app/motion-interaction-proof.tsx",
  "components/template-app/template-shell.tsx",
  "components/template-app/template-dashboard-nav.tsx",
  "components/template-app/template-lead-form.tsx",
  "components/template-app/auth-session-status.tsx",
  "components/template-app/ai-chat-status.tsx",
  "components/template-app/data-status.tsx",
  "lib/supabase/profile-workflow.ts",
  "components/template-app/supabase-profile-workflow.tsx",
  "components/template-app/drizzle-query-proof.tsx",
  "components/template-app/payments-status.tsx",
  "components/template-app/docs-status.tsx",
  "components/template-app/instantdb-status.tsx",
  "components/template-app/wasm-interop-status.tsx",
  "components/template-app/zod-validation-status.tsx",
  "components/template-app/zod-dashboard-settings.tsx",
  "components/template-app/icon-status.tsx",
  "components/template-app/next-intl-dashboard-locale-contract.ts",
  "components/template-app/next-intl-dashboard-locale.tsx",
  "components/template-app/next-intl-status.tsx",
  "components/template-app/query-cache-status.tsx",
  "components/template-app/query-dashboard-read-model.ts",
  "components/template-app/forge-package-status.ts",
  "components/template-app/forge-package-status-read-model.ts",
  "components/template-app/preview-style-package-panel-read-model.ts",
  "components/template-app/preview-style-package-ownership-read-model.ts",
  "components/template-app/forge-golden-path-contract.ts",
  "components/template-app/forge-golden-path-panel.tsx",
  "components/template-app/forge-safety-archive-contract.ts",
  "components/template-app/forge-safety-archive-runbook.ts",
  "components/template-app/forge-safety-archive-panel.tsx",
  "components/template-app/forge-remote-head-health-contract.ts",
  "components/template-app/forge-remote-head-health-panel.tsx",
  "components/template-app/package-catalog.ts",
  "components/template-app/template-surface-registry.ts",
  "components/template-app/framework-completeness.ts",
  "components/template-app/react-markdown-preview.tsx",
  "components/template-app/state-zustand-counter.tsx",
  "components/template-app/state-zustand-dashboard.tsx",
  "components/template-app/trpc-launch-contract.ts",
  "components/template-app/trpc-launch-health.tsx",
  "components/scene/launch-scene.tsx",
  "lib/scene/index.ts",
  "lib/scene/types.ts",
  "lib/scene/preset.ts",
  "lib/scene/interaction.ts",
  "lib/scene/dashboard-workflow.ts",
  "lib/scene/dashboard-controls.ts",
  "lib/scene/frame-sample.ts",
  "lib/scene/capability-report.ts",
  "lib/scene/viewport-report.ts",
  "lib/scene/bounds-report.ts",
  "lib/scene/raycast-report.ts",
  "lib/scene/preview-readiness.ts",
  "lib/scene/performance-monitor.ts",
  "lib/scene/renderer-handoff.ts",
  "lib/scene/r3f-renderer-adapter.ts",
  "lib/scene/webgl-runtime.ts",
  "lib/scene/metadata.ts",
  "lib/scene/README.md",
  "components/template-app/template-console.tsx",
  "server/templateCatalog.ts",
  "components/ui/button.tsx",
  "components/ui/slot.tsx",
  "components/ui/README.md",
  "lib/utils.ts",
  "lib/forge/state/zustand/index.ts",
  "lib/forge/state/zustand/vanilla.ts",
  "lib/forge/state/zustand/react.ts",
  "lib/forge/state/zustand/traditional.ts",
  "lib/forge/state/zustand/middleware.ts",
  "lib/forge/state/zustand/devtools.ts",
  "lib/forge/state/zustand/immer.ts",
  "lib/forge/state/zustand/redux.ts",
  "lib/forge/state/zustand/ssr-safe.ts",
  "lib/forge/state/zustand/shallow.ts",
  "lib/forge/state/zustand/persist.ts",
  "lib/forge/state/zustand/metadata.ts",
  "lib/forge/state/zustand/README.md",
  "tools/launch/runtime-template/assets/favicon.svg",
  ".dx/forge/source-manifest.json",
  ".dx/forge/package-lock.json",
  ".dx/forge/package-status.json",
  ".dx/forge/receipts/remotes/www-template-r2-head-health.json",
  ".dx/forge/receipts/packages/shadcn-ui-button.json",
  ".dx/forge/receipts/packages/state-zustand.json",
  ".dx/forge/cache/shadcn-ui-button/0.1.0/manifest.json",
  ".dx/forge/cache/shadcn-ui-button/0.1.0/components/ui/button.tsx",
  ".dx/forge/cache/shadcn-ui-button/0.1.0/components/ui/slot.tsx",
  ".dx/forge/cache/shadcn-ui-button/0.1.0/components/ui/README.md",
  ".dx/forge/cache/shadcn-ui-button/0.1.0/lib/utils.ts",
  ".dx/forge/cache/state-zustand/5.0.13-dx.10/manifest.json",
  ".dx/forge/cache/state-zustand/5.0.13-dx.10/lib/forge/state/zustand/index.ts",
  ".dx/forge/cache/state-zustand/5.0.13-dx.10/lib/forge/state/zustand/vanilla.ts",
  ".dx/forge/cache/state-zustand/5.0.13-dx.10/lib/forge/state/zustand/react.ts",
  ".dx/forge/cache/state-zustand/5.0.13-dx.10/lib/forge/state/zustand/traditional.ts",
  ".dx/forge/cache/state-zustand/5.0.13-dx.10/lib/forge/state/zustand/middleware.ts",
  ".dx/forge/cache/state-zustand/5.0.13-dx.10/lib/forge/state/zustand/devtools.ts",
  ".dx/forge/cache/state-zustand/5.0.13-dx.10/lib/forge/state/zustand/immer.ts",
  ".dx/forge/cache/state-zustand/5.0.13-dx.10/lib/forge/state/zustand/redux.ts",
  ".dx/forge/cache/state-zustand/5.0.13-dx.10/lib/forge/state/zustand/ssr-safe.ts",
  ".dx/forge/cache/state-zustand/5.0.13-dx.10/lib/forge/state/zustand/shallow.ts",
  ".dx/forge/cache/state-zustand/5.0.13-dx.10/lib/forge/state/zustand/persist.ts",
  ".dx/forge/cache/state-zustand/5.0.13-dx.10/lib/forge/state/zustand/metadata.ts",
  ".dx/forge/cache/state-zustand/5.0.13-dx.10/lib/forge/state/zustand/README.md",
  ".dx/forge/receipts/2026-05-22-i18n-next-intl-dashboard-locale.json",
  ".dx/forge/receipts/auth-better-auth.json",
  ".dx/forge/receipts/2026-05-22-content-fumadocs-dashboard-workflow.json",
  ".dx/forge/receipts/2026-05-22-ai-vercel-ai-launch-assistant.json",
  ".dx/forge/receipts/2026-05-22-automation-connectors-launch-workflow.json",
  ".dx/forge/receipts/2026-05-22-animation-motion-dashboard-workflow.json",
  ".dx/forge/receipts/2026-05-22-forms-dashboard-workflow.json",
  ".dx/forge/receipts/2026-05-22-tanstack-query-dashboard-data.json",
  ".dx/forge/receipts/2026-05-22-state-zustand-dashboard-workflow.json",
  ".dx/forge/receipts/2026-05-22-api-trpc-dashboard-workflow.json",
  ".dx/forge/receipts/2026-05-22-instantdb-realtime-dashboard.json",
  ".dx/forge/receipts/2026-05-22-db-drizzle-sqlite-dashboard-workflow.json",
  ".dx/forge/receipts/2026-05-22-wasm-bindgen-dashboard-workflow.json",
  ".dx/forge/receipts/3d-launch-scene-dashboard-workflow.json",
  ".dx/forge/template-readiness/launch-route.json",
  ".dx/forge/template-readiness/launch-readiness-bundle.json",
] as const;

export const templateRouteContract = {
  route: "/",
  routeAliases: [],
  title: "DX WWW Template",
  description: "Composed DX-WWW dashboard shell with package catalog readiness.",
  sourceRouteFile: "examples/template/app/page.tsx",
  materializedRouteFile: "app/page.tsx",
  sourceComponentFile: "examples/template/template-shell.tsx",
  materializedComponentFile: "components/template-app/template-shell.tsx",
  studioEditContract: {
    schema: "dx.studio.launch_edit_contract",
    sourceFile: "examples/template/dx-studio-edit-contract.ts",
    materializedFile: "components/template-app/dx-studio-edit-contract.ts",
    sourceGuard: "dx run --test .\\benchmarks\\dx-studio-preview-manifest.test.ts",
    operations: [
      "insert_component",
      "move_reorder_section",
      "update_design_token",
      "update_text_content",
      "insert_icon_media",
    ],
    selectorPolicy: "stable-data-dx-selectors-source-owned-files-only",
    layoutPolicy: "responsive-design-system-grid",
    absolutePositioning: false,
    noNodeModulesRequired: true,
  },
  templateSurfaceRegistry: {
    schema: "dx.www.template_surface_registry",
    sourceFile: "examples/template/template-surface-registry.ts",
    materializedFile: "components/template-app/template-surface-registry.ts",
    sourceSelector: '[data-dx-component="template-worker-registry"]',
    route: "/",
    noNodeModulesRequired: true,
    packageWorkerPolicy:
      "package lanes add source-owned surfaces to TemplateShell through declared slots, receipts, env boundaries, and stable data-dx selectors",
  },
  frameworkCompleteness: {
    schema: "dx.www.framework_completeness",
    sourceFile: "examples/template/framework-completeness.ts",
    materializedFile: "components/template-app/framework-completeness.ts",
    lanes: [
      "routing-parity",
      "server-client-model",
      "dev-experience",
      "production-template",
      "package-ecosystem",
    ],
    publicAuthoring: "tsx-first",
    packagePolicy: "forge-first-no-node_modules",
    stylePolicy: "dx-style-generated-css",
  },
  sourceSmokeCommand: "dx run --test .\\benchmarks\\template-shell.test.ts",
  motionProofSourceGuard: "dx run --test .\\benchmarks\\motion-launch-proof.test.ts",
  motionMaterializedLaunchGuard:
    "dx run --test .\\benchmarks\\motion-launch-materialized.test.ts",
  motionRuntimeInteractionGuard:
    "dx run --test .\\benchmarks\\motion-runtime-interaction.test.ts",
  sceneDashboardWorkflowGuard:
    "dx run --test .\\benchmarks\\launch-scene-dashboard-workflow.test.ts",
  runtimeVerification: "pending-governed-runtime-pass",
  runtimeVerificationRequiresExplicitPermission: true,
  runtimeVerificationRequest: {
    approvalStatus: "requires-explicit-permission",
    automationDefault: "skip-runtime-build-preview",
    expectedEvidence: [
      "governed-runtime-route-response",
      "production-contract-route-proof",
      "final-launch-evidence-receipt",
    ],
    noExecution: true,
  },
  templateReadinessReceipt: {
    packageId: "dx-www/template-shell",
    variant: "next-familiar",
    file: ".dx/forge/template-readiness/launch-route.json",
    receiptGlob: ".dx/forge/receipts/*-dx-www-template-shell--variant-next-familiar.json",
    docsFile: ".dx/forge/docs/dx-www-template-shell--variant-next-familiar.md",
    status: "source-materialized-runtime-pending",
    runtimeVerificationRequiresExplicitPermission: true,
  },
  launchReadinessBundle: {
    schema: "dx.launch.readiness_bundle",
    file: ".dx/forge/template-readiness/launch-readiness-bundle.json",
    templateReadinessReceipt: ".dx/forge/template-readiness/launch-route.json",
    packageReceiptCommand: "dx forge packages --json",
    sourcePackageGuard: "dx run --test .\\benchmarks\\launch-package-slices.test.ts",
    runtimeGate: "pending-governed-runtime-pass",
    noExecution: true,
  },
  forgePackageStatus: launchForgePackageStatus,
  packageWorkflowReceipts: {
    formsDashboardWorkflow: {
      schema: "dx.forge.package_dashboard_workflow_receipt",
      packageId: "forms/react-hook-form",
      officialPackageName: "Forms",
      file: "examples/template/.dx/forge/receipts/2026-05-22-forms-dashboard-workflow.json",
      route: "/",
      component: "template-lead-form",
      dashboardWorkflow: "forms-launch-lead",
      productSurface: "launch-lead-capture",
      sourceFile: "examples/template/template-lead-form.tsx",
      shellSourceFile: "examples/template/template-shell.tsx",
      runtimeSourceFile: "examples/template/app/page.tsx",
      materializedFile: "components/template-app/template-lead-form.tsx",
      materializedReceiptFile:
        ".dx/forge/receipts/2026-05-22-forms-dashboard-workflow.json",
      requiredEnv: [],
      selectedSurfaces: [
        "form-provider",
        "registered-fields",
        "controlled-fields",
        "field-arrays",
        "zod-style-resolver",
        "template-lead-form",
      ],
      appOwnedBoundaries: [
        "Dependency installation",
        "Validation rules and copy",
        "Accessibility review",
        "Submit handlers",
        "Spam protection",
        "Persistence",
        "Authorization",
        "Governed browser runtime proof",
      ],
      dataDxMarkers: [
        "data-dx-package",
        "data-dx-component",
        "data-dx-edit-id",
        "data-dx-edit-kind",
        "data-dx-editable",
        "data-dx-insert-slot",
      ],
      dxCheckVisibility: [
        "present",
        "stale",
        "missing receipt",
        "blocked",
        "unsupported surface",
      ],
      sourceGuard: "dx run --test .\\benchmarks\\forms-react-hook-form-package-doc.test.ts",
      noExecution: true,
    },
    automationConnectorsLaunchWorkflow: {
      schema: "dx.forge.package_dashboard_workflow_receipt",
      packageId: "automations/n8n",
      officialPackageName: "Automation Connectors",
      file: "examples/template/.dx/forge/receipts/2026-05-22-automation-connectors-launch-workflow.json",
      route: "/",
      component: "launch-automation-dashboard-workflow",
      dashboardWorkflow: "automation-release-receipt",
      productSurface: "launch-automation-connectors",
      sourceFile: "examples/template/automations-status.tsx",
      missionSummarySourceFile:
        "examples/template/automation-mission-summary.tsx",
      metadataSourceFile:
        "examples/template/automations/automations-metadata.ts",
      shellSourceFile: "examples/template/template-shell.tsx",
      runtimePageSourceFile: "tools/launch/runtime-template/pages/index.html",
      runtimeScriptFile: "tools/launch/runtime-template/assets/launch-runtime.ts",
      materializedFile: "components/template-app/automations-status.tsx",
      materializedMissionSummaryFile:
        "components/template-app/automation-mission-summary.tsx",
      materializedMetadataFile:
        "components/template-app/automations/automations-metadata.ts",
      materializedReceiptFile:
        ".dx/forge/receipts/2026-05-22-automation-connectors-launch-workflow.json",
      requiredEnv: [
        "SLACK_BOT_TOKEN",
        "SLACK_SIGNING_SECRET",
        "NOTION_API_KEY",
        "DX_AUTOMATIONS_OPERATOR_APPROVAL",
      ],
      selectedSurfaces: [
        "connector-catalog",
        "credential-readiness",
        "redacted-run-receipt",
        "launch-dashboard-workflow",
        "starter-dashboard-workflow",
        "zed-run-handoff",
      ],
      appOwnedBoundaries: [
        "Credential storage and provider secrets",
        "Operator approval for live workflow execution",
        "Provider webhook registration",
        "Live n8n worker runtime",
        "Governed browser runtime proof",
      ],
      dataDxMarkers: [
        "data-dx-package",
        "data-dx-component",
        "data-dx-dashboard-workflow",
        "data-dx-automation-workflow",
        "data-dx-automation-dashboard-state",
        "data-dx-automation-credential-schema",
        "data-dx-automation-required-env",
        "data-dx-automation-receipt-intent",
        "data-dx-automation-run-receipt-intent",
        "data-dx-automation-run-receipt-path",
        "data-dx-check-package-lane-row",
        "data-dx-check-package-lane-receipt-path",
        "data-dx-style-surface",
        "data-dx-token-scope",
      ],
      dxCheckVisibility: [
        "present",
        "stale",
        "missing-receipt",
        "blocked",
        "unsupported-surface",
      ],
      sourceGuard:
        "dx run --test .\\benchmarks\\automations-generated-starter-receipt.test.ts",
      noExecution: true,
    },
    betterAuthDashboardWorkflow: {
      schema: "dx.forge.package_dashboard_workflow_receipt",
      packageId: "auth/better-auth",
      file: "examples/template/.dx/forge/receipts/auth-better-auth.json",
      route: "/",
      component: "better-auth-account-dashboard-workflow",
      dashboardWorkflow: "login-session-account",
      productSurface: "account-access",
      sourceFile: "examples/template/auth-session-status.tsx",
      shellSourceFile: "examples/template/template-shell.tsx",
      runtimeSourceFile: "examples/template/app/page.tsx",
      runtimeScriptFile: "tools/launch/runtime-template/assets/launch-runtime.ts",
      materializedFile: "components/template-app/auth-session-status.tsx",
      materializedReceiptFile: ".dx/forge/receipts/auth-better-auth.json",
      requiredEnv: ["BETTER_AUTH_SECRET", "BETTER_AUTH_URL"],
      providerEnv: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
      credentialState: "missing-config",
      dataDxMarkers: [
        "data-dx-package",
        "data-dx-component",
        "data-dx-dashboard-workflow",
        "data-dx-auth-dashboard-workflow",
        "data-dx-auth-interaction",
        "data-dx-auth-network-state",
        "data-dx-auth-session-source",
        "data-dx-auth-boundary-review",
        "data-dx-auth-boundary-review-state",
        "data-dx-auth-provider",
        "data-dx-auth-provider-state",
        "data-dx-auth-missing-provider",
        "data-dx-auth-receipt-path",
      ],
      sourceGuard: "dx run --test .\\benchmarks\\better-auth-dashboard-workflow.test.ts",
      noExecution: true,
    },
    tanstackQueryDashboardData: {
      schema: "dx.forge.package_dashboard_workflow_receipt",
      packageId: "tanstack/query",
      file: "examples/template/.dx/forge/receipts/2026-05-22-tanstack-query-dashboard-data.json",
      route: "/",
      component: "tanstack-query-dashboard-data-workflow",
      dashboardWorkflow: "query-backed-dashboard-data",
      sourceFile: "examples/template/query-cache-status.tsx",
      readModelSourceFile: "examples/template/query-dashboard-read-model.ts",
      shellSourceFile: "examples/template/template-shell.tsx",
      runtimeSourceFile: "examples/template/app/page.tsx",
      runtimeScriptFile: "tools/launch/runtime-template/assets/launch-runtime.ts",
      materializedFile: "components/template-app/query-cache-status.tsx",
      materializedReceiptFile:
        ".dx/forge/receipts/2026-05-22-tanstack-query-dashboard-data.json",
      requiredEnv: [],
      dataDxMarkers: [
        "data-dx-package",
        "data-dx-component",
        "data-dx-dashboard-workflow",
        "data-dx-product-surface",
        "data-dx-query-dashboard-source",
        "data-dx-query-dashboard-queue",
        "data-dx-query-dashboard-package-count",
        "data-dx-query-dashboard-role-count",
        "data-dx-query-package-id",
        "data-dx-query-package-role",
        "data-dx-query-package-status",
        "data-dx-query-action",
        "data-dx-query-safe-action",
        "data-dx-query-result-status",
      ],
      sourceGuard: "dx run --test .\\benchmarks\\tanstack-query-slice.test.ts",
      noExecution: true,
    },
    zustandDashboardStateWorkflow: {
      schema: "dx.forge.package_dashboard_workflow_receipt",
      packageId: "state/zustand",
      file: "examples/template/.dx/forge/receipts/2026-05-22-state-zustand-dashboard-workflow.json",
      route: "/",
      component: "launch-dashboard-state-shell",
      dashboardWorkflow: "ui-state-persistence",
      productSurface: "launch-dashboard-controls",
      sourceFile: "examples/template/state-zustand-dashboard.tsx",
      shellSourceFile: "examples/template/template-shell.tsx",
      runtimeSourceFile: "examples/template/app/page.tsx",
      runtimeScriptFile: "tools/launch/runtime-template/assets/launch-runtime.ts",
      materializedFile: "components/template-app/state-zustand-dashboard.tsx",
      materializedReceiptFile:
        ".dx/forge/receipts/2026-05-22-state-zustand-dashboard-workflow.json",
      requiredEnv: [],
      dataDxMarkers: [
        "data-dx-package",
        "data-dx-component",
        "data-dx-dashboard-workflow",
        "data-dx-zustand-store",
        "data-dx-zustand-persist-key",
        "data-dx-zustand-action",
        "data-dx-zustand-hydration-event",
        "data-dx-zustand-rehydrate-state",
      ],
      sourceGuard: "dx run --test .\\benchmarks\\zustand-slice.test.ts",
      noExecution: true,
    },
    launchSceneDashboardWorkflow: {
      schema: "dx.forge.package_dashboard_workflow_receipt",
      packageId: "3d/launch-scene",
      file: "examples/template/.dx/forge/receipts/3d-launch-scene-dashboard-workflow.json",
      route: "/",
      component: "launch-scene-dashboard-workflow",
      dashboardWorkflow: "scene-visual-ops",
      productSurface: "visual-operations-dashboard",
      sourceFile: "examples/template/launch-scene.tsx",
      shellSourceFile: "examples/template/template-shell.tsx",
      runtimeSourceFile: "examples/template/app/page.tsx",
      runtimeScriptFile: "tools/launch/runtime-template/assets/launch-runtime.ts",
      materializedFile: "components/scene/launch-scene.tsx",
      materializedReceiptFile:
        ".dx/forge/receipts/3d-launch-scene-dashboard-workflow.json",
      requiredEnv: [],
      dataDxMarkers: [
        "data-dx-package",
        "data-dx-component",
        "data-dx-dashboard-workflow",
        "data-dx-product-surface",
        "data-dx-scene-action",
        "data-dx-scene-quality-profile",
        "data-dx-scene-material-palette",
        "data-dx-scene-camera-rig",
        "data-dx-scene-frame-sample",
        "data-dx-scene-capability-report",
        "data-dx-scene-capability-status",
        "data-dx-scene-viewport-report",
        "data-dx-scene-viewport-status",
        "data-dx-scene-bounds-report",
        "data-dx-scene-bounds-status",
        "data-dx-scene-raycast-report",
        "data-dx-scene-raycast-status",
        "data-dx-scene-workflow-active",
        "data-dx-scene-workflow-receipt-state",
      ],
      sourceGuard: "dx run --test .\\benchmarks\\launch-scene-dashboard-workflow.test.ts",
      noExecution: true,
    },
    trpcTypedApiDashboard: {
      schema: "dx.forge.package_dashboard_workflow_receipt",
      packageId: "api/trpc",
      file: "examples/template/.dx/forge/receipts/2026-05-22-api-trpc-dashboard-workflow.json",
      route: "/",
      component: "launch-trpc-api-dashboard-workflow",
      dashboardWorkflow: "typed-api-readiness",
      productSurface: "account-data-dashboard",
      contractSourceFile: "examples/template/trpc-launch-contract.ts",
      sourceFile: "examples/template/trpc-launch-health.tsx",
      shellSourceFile: "examples/template/template-shell.tsx",
      runtimeSourceFile: "examples/template/app/page.tsx",
      runtimeScriptFile: "tools/launch/runtime-template/assets/launch-runtime.ts",
      materializedContractFile: "components/template-app/trpc-launch-contract.ts",
      materializedFile: "components/template-app/trpc-launch-health.tsx",
      routeContract: "/api/trpc/health",
      requiredEnv: [],
      dataDxMarkers: [
        "data-dx-package",
        "data-dx-component",
        "data-dx-dashboard-card",
        "data-dx-dashboard-workflow",
        "data-dx-trpc-workflow",
        "data-dx-trpc-action",
        "data-trpc-interaction",
      ],
      sourceGuard: "dx run --test .\\benchmarks\\trpc-forge-slice.test.ts",
      noExecution: true,
    },
    nextIntlDashboardLocale: {
      schema: "dx.forge.package_dashboard_workflow_receipt",
      packageId: "i18n/next-intl",
      file: "examples/template/.dx/forge/receipts/2026-05-22-i18n-next-intl-dashboard-locale.json",
      route: "/",
      component: "next-intl-dashboard-locale-workflow",
      sourceFile: "examples/template/next-intl-dashboard-locale.tsx",
      contractFile:
        "examples/template/next-intl-dashboard-locale-contract.ts",
      materializedContractFile:
        "components/template-app/next-intl-dashboard-locale-contract.ts",
      runtimeSourceFile: "examples/template/app/page.tsx",
      runtimeScriptFile: "tools/launch/runtime-template/assets/launch-runtime.ts",
      dashboardWorkflow: "locale-copy-boundary",
      dataDxMarkers: [
        "data-dx-package",
        "data-dx-component",
        "data-dx-dashboard-card",
        "data-dx-dashboard-copy-locale",
        "data-dx-intl-dashboard-workflow",
        "data-dx-intl-message-namespace",
        "data-dx-intl-action",
        "data-dx-intl-alternate-links",
        "data-dx-intl-alternate-locale",
        "data-dx-intl-alternate-href",
        "data-dx-intl-hreflang",
        "data-dx-intl-locale-prefix",
        "data-dx-intl-format-preview",
        "data-dx-intl-format-source-api",
        "data-dx-intl-format-time-zone",
        "data-dx-intl-number-preview",
        "data-dx-intl-number-source-api",
        "data-dx-intl-number-currency",
        "data-dx-intl-locale-option",
        "data-dx-intl-locale-selected",
        "data-dx-intl-copy-target",
        "data-dx-intl-readiness-copy",
        "data-dx-intl-plan-label",
        "data-dx-intl-support-sla",
        "data-dx-intl-route-preview",
        "data-dx-intl-receipt-state",
        "data-dx-intl-receipt-locale",
        "data-dx-intl-receipt-route",
        "data-dx-intl-receipt-number-source",
      ],
      sourceGuard: "dx run --test .\\benchmarks\\next-intl-dashboard-workflow.test.ts",
      noExecution: true,
    },
    fumadocsDocsDashboardWorkflow: {
      schema: "dx.forge.package_dashboard_workflow_receipt",
      packageId: "content/fumadocs-next",
      file: "examples/template/.dx/forge/receipts/2026-05-22-content-fumadocs-dashboard-workflow.json",
      route: "/",
      component: "launch-fumadocs-docs-workflow",
      dashboardWorkflow: "docs-help-changelog",
      productSurface: "dashboard-help-content",
      sourceFile: "examples/template/docs-status.tsx",
      shellSourceFile: "examples/template/template-shell.tsx",
      runtimeSourceFile: "examples/template/app/page.tsx",
      runtimeScriptFile: "tools/launch/runtime-template/assets/launch-runtime.ts",
      materializedFile: "components/template-app/docs-status.tsx",
      materializedReceiptFile:
        ".dx/forge/receipts/2026-05-22-content-fumadocs-dashboard-workflow.json",
      requiredEnv: ["DX_FUMADOCS_OPENAPI_ALLOWED_ORIGINS"],
      dataDxMarkers: [
        "data-dx-package",
        "data-dx-component",
        "data-dx-dashboard-workflow",
        "data-dx-dashboard-card",
        "data-dx-product-surface",
        "data-dx-fumadocs-dashboard-target",
        "data-dx-fumadocs-interaction",
        "data-dx-fumadocs-action",
        "data-dx-fumadocs-page-option",
        "data-dx-fumadocs-rendered-markdown",
        "data-dx-fumadocs-changelog",
        "data-dx-fumadocs-rendered-route",
        "data-dx-fumadocs-selected-page",
        "data-dx-fumadocs-toc-count",
        "data-dx-fumadocs-local-response",
        "data-dx-fumadocs-receipt-route",
        "data-dx-fumadocs-missing-config",
        "data-dx-docs-openapi-code-usage",
        "data-dx-docs-openapi-proxy",
      ],
      sourceGuard: "dx run --test .\\benchmarks\\fumadocs-dashboard-workflow.test.ts",
      noExecution: true,
    },
    vercelAiLaunchAssistant: {
      schema: "dx.forge.package_dashboard_workflow_receipt",
      packageId: "ai/vercel-ai",
      file: "examples/template/.dx/forge/receipts/2026-05-22-ai-vercel-ai-launch-assistant.json",
      route: "/",
      component: "launch-ai-assistant-dashboard-workflow",
      dashboardWorkflow: "prompt-action-provider-readiness",
      sourceFile: "examples/template/ai-chat-status.tsx",
      shellSourceFile: "examples/template/template-shell.tsx",
      materializedFile: "components/template-app/ai-chat-status.tsx",
      routeContract: "/api/ai/chat",
      requiredEnv: ["AI_PROVIDER_API_KEY"],
      optionalEnv: ["AI_GATEWAY_API_KEY"],
      dataDxMarkers: [
        "data-dx-component",
        "data-dx-dashboard-workflow",
        "data-dx-ai-route-contract",
        "data-dx-ai-action",
        "data-dx-ai-action-state",
        "data-dx-ai-config-state",
        "data-dx-ai-local-response",
        "data-dx-ai-prompt-state",
        "data-dx-ai-request-id",
      ],
      sourceGuard: "dx run --test .\\benchmarks\\vercel-ai-launch-visible-proof.test.ts",
      noExecution: true,
    },
    instantDbRealtimeDashboard: {
      schema: "dx.forge.package_dashboard_workflow_receipt",
      packageId: "instantdb/react",
      file: "examples/template/.dx/forge/receipts/2026-05-22-instantdb-realtime-dashboard.json",
      route: "/",
      component: "instantdb-runtime-dashboard-workflow",
      dashboardWorkflow: "realtime-data-readiness",
      sourceFile: "examples/template/instantdb-status.tsx",
      shellSourceFile: "examples/template/template-shell.tsx",
      runtimeSourceFile: "examples/template/app/page.tsx",
      runtimeScriptFile: "tools/launch/runtime-template/assets/launch-runtime.ts",
      materializedFile: "components/template-app/instantdb-status.tsx",
      requiredEnv: ["NEXT_PUBLIC_INSTANT_APP_ID"],
      dataDxMarkers: [
        "data-dx-package",
        "data-dx-component",
        "data-dx-dashboard-workflow",
        "data-dx-instant-readiness",
        "data-dx-instant-action",
        "data-dx-instant-required-env",
        "data-dx-instant-local-receipt",
      ],
      sourceGuard: "dx run --test .\\benchmarks\\instantdb-dashboard-workflow.test.ts",
      noExecution: true,
    },
    drizzleSqliteDashboard: {
      schema: "dx.forge.package_dashboard_workflow_receipt",
      packageId: "db/drizzle-sqlite",
      file: "examples/template/.dx/forge/receipts/2026-05-22-db-drizzle-sqlite-dashboard-workflow.json",
      route: "/",
      component: "launch-drizzle-data-workflow",
      dashboardWorkflow: "sqlite-read-model",
      productSurface: "launch-data-dashboard",
      missionControlTarget: "mission-control-database",
      sourceFile: "examples/template/drizzle-query-proof.tsx",
      shellSourceFile: "examples/template/template-shell.tsx",
      runtimeSourceFile: "examples/template/app/page.tsx",
      runtimeScriptFile: "tools/launch/runtime-template/assets/launch-runtime.ts",
      materializedFile: "components/template-app/drizzle-query-proof.tsx",
      requiredEnv: [],
      dataDxMarkers: [
        "data-dx-package",
        "data-dx-component",
        "data-dx-dashboard-workflow",
        "data-dx-dashboard-target",
        "data-dx-source",
        "data-dx-drizzle-action",
        "data-dx-drizzle-query-plan-id",
        "data-dx-drizzle-sql-preview",
        "data-dx-drizzle-receipt-path",
        "data-dx-drizzle-receipt-state",
        "data-dx-drizzle-runtime-dependencies",
        "data-dx-backend-status",
        "data-dx-backend-detail",
      ],
      sourceGuard: "dx run --test .\\benchmarks\\drizzle-launch-proof.test.ts",
      noExecution: true,
    },
    wasmBindgenLocalComputeDashboard: {
      schema: "dx.forge.package_dashboard_workflow_receipt",
      packageId: "wasm/bindgen",
      file: "examples/template/.dx/forge/receipts/2026-05-22-wasm-bindgen-dashboard-workflow.json",
      route: "/",
      component: "launch-wasm-compute-dashboard-workflow",
      dashboardWorkflow: "local-compute-readiness",
      productSurface: "launch-dashboard",
      previewManifestSurface: "launch-runtime-wasm-compute-dashboard",
      sourceFile: "examples/template/wasm-interop-status.tsx",
      shellSourceFile: "examples/template/template-shell.tsx",
      runtimeSourceFile: "examples/template/app/page.tsx",
      runtimeScriptFile: "tools/launch/runtime-template/assets/launch-runtime.ts",
      materializedFile: "components/template-app/wasm-interop-status.tsx",
      materializedReceiptFile:
        ".dx/forge/receipts/2026-05-22-wasm-bindgen-dashboard-workflow.json",
      requiredEnv: [],
      dataDxMarkers: [
        "data-dx-package",
        "data-dx-component",
        "data-dx-dashboard-card",
        "data-dx-dashboard-workflow",
        "data-dx-dashboard-metric",
        "data-dx-wasm-action",
        "data-dx-wasm-add-result",
        "data-dx-wasm-bindgen-status",
        "data-dx-wasm-mime-status",
      ],
      sourceGuard: "dx run --test .\\benchmarks\\wasm-bindgen-slice.test.ts",
      noExecution: true,
    },
    motionDashboardWorkflow: {
      schema: "dx.forge.package_dashboard_workflow_receipt",
      packageId: "animation/motion",
      file: "examples/template/.dx/forge/receipts/2026-05-22-animation-motion-dashboard-workflow.json",
      route: "/",
      component: "launch-motion-dashboard-workflow",
      dashboardWorkflow: "motion-panel-orchestration",
      productSurface: "launch-dashboard",
      sourceFile: "examples/template/template-shell.tsx",
      proofSourceFile: "examples/template/motion-interaction-proof.tsx",
      runtimeSourceFile: "examples/template/app/page.tsx",
      runtimeScriptFile: "tools/launch/runtime-template/assets/launch-runtime.ts",
      runtimeStyleFile: "examples/template/styles/globals.css",
      materializedFile: "components/template-app/motion-interaction-proof.tsx",
      requiredEnv: [],
      dataDxMarkers: [
        "data-dx-package",
        "data-dx-component",
        "data-dx-dashboard-workflow",
        "data-dx-motion-interaction",
        "data-dx-motion-stage",
        "data-dx-motion-order",
        "data-dx-motion-order-available",
        "data-dx-motion-order-direction",
        "data-dx-motion-keyboard-reorder",
        "data-dx-motion-keyboard-state",
        "data-dx-motion-preference-storage",
        "data-dx-motion-storage-key",
        "data-dx-motion-policy",
        "data-dx-motion-reduced",
        "data-dx-dashboard-motion-reduced",
      ],
      sourceGuard: "dx run --test .\\benchmarks\\motion-dashboard-workflow.test.ts",
      materializedGuard: "dx run --test .\\benchmarks\\motion-launch-materialized.test.ts",
      runtimeGuard: "dx run --test .\\benchmarks\\motion-runtime-interaction.test.ts",
      noExecution: true,
    },
  },
  launchEvidencePacket: {
    schema: "dx.launch.evidence_packet",
    file: ".dx/forge/release/launch-evidence-packet.json",
    command: "dx forge launch-evidence-packet --project <path> --json",
    readinessBundle: ".dx/forge/template-readiness/launch-readiness-bundle.json",
    runtimeEvidenceReview: ".dx/forge/runtime/final-launch-evidence-review.json",
    noExecution: true,
  },
  launchEvidenceOperatorIndex: {
    schema: "dx.launch.evidence_operator_index",
    file: ".dx/forge/release/launch-evidence-operator-index.json",
    command: "dx forge launch-evidence-operator-index --project <path> --json",
    packet: ".dx/forge/release/launch-evidence-packet.json",
    noExecution: true,
  },
  launchEvidenceStatusTimeline: {
    schema: "dx.launch.evidence_status_timeline",
    file: ".dx/forge/release/launch-evidence-status-timeline.json",
    command: "dx forge launch-evidence-status-timeline --project <path> --json",
    operatorIndex: ".dx/forge/release/launch-evidence-operator-index.json",
    freshnessSource: "filesystem-metadata",
    noExecution: true,
  },
  launchEvidenceHandoffDigest: {
    schema: "dx.launch.evidence_handoff_digest",
    file: ".dx/forge/release/launch-evidence-handoff-digest.md",
    command: "dx forge launch-evidence-handoff-digest --project <path> --write",
    statusTimeline: ".dx/forge/release/launch-evidence-status-timeline.json",
    operatorIndex: ".dx/forge/release/launch-evidence-operator-index.json",
    releasePacket: ".dx/forge/release/launch-evidence-packet.json",
    format: "markdown",
    zedOpenable: true,
    noExecution: true,
  },
  launchEvidenceReleaseChecklist: {
    schema: "dx.launch.evidence_release_checklist",
    file: ".dx/forge/release/launch-evidence-release-checklist.json",
    command: "dx forge launch-evidence-release-checklist --project <path> --write",
    handoffDigest: ".dx/forge/release/launch-evidence-handoff-digest.md",
    statusTimeline: ".dx/forge/release/launch-evidence-status-timeline.json",
    releasePacket: ".dx/forge/release/launch-evidence-packet.json",
    noExecution: true,
  },
  launchEvidenceShareManifest: {
    schema: "dx.launch.evidence_share_manifest",
    file: ".dx/forge/release/launch-evidence-share-manifest.json",
    command: "dx forge launch-evidence-share-manifest --project <path> --write",
    releaseChecklist: ".dx/forge/release/launch-evidence-release-checklist.json",
    handoffDigest: ".dx/forge/release/launch-evidence-handoff-digest.md",
    statusTimeline: ".dx/forge/release/launch-evidence-status-timeline.json",
    operatorIndex: ".dx/forge/release/launch-evidence-operator-index.json",
    releasePacket: ".dx/forge/release/launch-evidence-packet.json",
    exportTarget: "dx-cli-zed",
    noExecution: true,
  },
  launchEvidenceArchiveIndex: {
    schema: "dx.launch.evidence_archive_index",
    file: ".dx/forge/release/launch-evidence-archive-index.json",
    command: "dx forge launch-evidence-archive-index --project <path> --write",
    shareManifest: ".dx/forge/release/launch-evidence-share-manifest.json",
    releaseChecklist: ".dx/forge/release/launch-evidence-release-checklist.json",
    handoffDigest: ".dx/forge/release/launch-evidence-handoff-digest.md",
    releasePacket: ".dx/forge/release/launch-evidence-packet.json",
    archiveTarget: "long-term-launch-handoff",
    noExecution: true,
  },
  launchEvidenceArchiveReceipt: {
    schema: "dx.launch.evidence_archive_receipt",
    file: ".dx/forge/release/launch-evidence-archive-receipt.json",
    command: "dx forge launch-evidence-archive-receipt --project <path> --write",
    archiveIndex: ".dx/forge/release/launch-evidence-archive-index.json",
    operatorHandoffTarget: "dx-cli-zed-archive",
    noExecution: true,
  },
  launchEvidenceArchiveLedger: {
    schema: "dx.launch.evidence_archive_ledger",
    file: ".dx/forge/release/launch-evidence-archive-ledger.json",
    command: "dx forge launch-evidence-archive-ledger --project <path> --write",
    archiveReceipt: ".dx/forge/release/launch-evidence-archive-receipt.json",
    archiveIndex: ".dx/forge/release/launch-evidence-archive-index.json",
    shareManifest: ".dx/forge/release/launch-evidence-share-manifest.json",
    releaseChecklist: ".dx/forge/release/launch-evidence-release-checklist.json",
    handoffDigest: ".dx/forge/release/launch-evidence-handoff-digest.md",
    releasePacket: ".dx/forge/release/launch-evidence-packet.json",
    noExecution: true,
  },
  launchEvidenceRetentionPolicy: {
    schema: "dx.launch.evidence_retention_policy",
    file: ".dx/forge/release/launch-evidence-retention-policy.json",
    command: "dx forge launch-evidence-retention-policy --project <path> --write",
    archiveLedger: ".dx/forge/release/launch-evidence-archive-ledger.json",
    policyTarget: "release-evidence-retention",
    noExecution: true,
  },
  launchEvidenceRetentionReview: {
    schema: "dx.launch.evidence_retention_review",
    file: ".dx/forge/release/launch-evidence-retention-review.json",
    command: "dx forge launch-evidence-retention-review --project <path> --write",
    retentionPolicy: ".dx/forge/release/launch-evidence-retention-policy.json",
    archiveLedger: ".dx/forge/release/launch-evidence-archive-ledger.json",
    reviewTarget: "post-retention-release-evidence",
    noExecution: true,
  },
  launchEvidenceReleaseSeal: {
    schema: "dx.launch.evidence_release_seal",
    file: ".dx/forge/release/launch-evidence-release-seal.json",
    command: "dx forge launch-evidence-release-seal --project <path> --write",
    retentionReview: ".dx/forge/release/launch-evidence-retention-review.json",
    retentionPolicy: ".dx/forge/release/launch-evidence-retention-policy.json",
    archiveLedger: ".dx/forge/release/launch-evidence-archive-ledger.json",
    releasePacket: ".dx/forge/release/launch-evidence-packet.json",
    sealTarget: "final-launch-handoff-seal",
    noExecution: true,
  },
  launchEvidenceOperatorSummary: {
    schema: "dx.launch.evidence_operator_summary",
    file: ".dx/forge/release/launch-evidence-operator-summary.json",
    command: "dx forge launch-evidence-operator-summary --project <path> --write",
    releaseSeal: ".dx/forge/release/launch-evidence-release-seal.json",
    retentionReview: ".dx/forge/release/launch-evidence-retention-review.json",
    releasePacket: ".dx/forge/release/launch-evidence-packet.json",
    finalRuntimeReview: ".dx/forge/runtime/final-launch-evidence-review.json",
    summaryTarget: "terminal-friendly-launch-handoff",
    noExecution: true,
  },
  launchEvidenceCompletionLedger: {
    schema: "dx.launch.evidence_completion_ledger",
    file: ".dx/forge/release/launch-evidence-completion-ledger.json",
    command: "dx forge launch-evidence-completion-ledger --project <path> --write",
    operatorSummary: ".dx/forge/release/launch-evidence-operator-summary.json",
    releaseSeal: ".dx/forge/release/launch-evidence-release-seal.json",
    retentionReview: ".dx/forge/release/launch-evidence-retention-review.json",
    finalRuntimeReview: ".dx/forge/runtime/final-launch-evidence-review.json",
    completionTarget: "final-launch-evidence-completion-map",
    noExecution: true,
  },
  launchEvidenceClosureMemo: {
    schema: "dx.launch.evidence_closure_memo",
    file: ".dx/forge/release/launch-evidence-closure-memo.md",
    command: "dx forge launch-evidence-closure-memo --project <path> --write",
    completionLedger: ".dx/forge/release/launch-evidence-completion-ledger.json",
    operatorSummary: ".dx/forge/release/launch-evidence-operator-summary.json",
    releaseSeal: ".dx/forge/release/launch-evidence-release-seal.json",
    finalRuntimeReview: ".dx/forge/runtime/final-launch-evidence-review.json",
    memoTarget: "human-readable-launch-release-closeout",
    format: "markdown",
    zedOpenable: true,
    noExecution: true,
  },
  launchEvidenceFinalBrief: {
    schema: "dx.launch.evidence_final_brief",
    file: ".dx/forge/release/launch-evidence-final-brief.json",
    command: "dx forge launch-evidence-final-brief --project <path> --write",
    closureMemo: ".dx/forge/release/launch-evidence-closure-memo.md",
    completionLedger: ".dx/forge/release/launch-evidence-completion-ledger.json",
    operatorSummary: ".dx/forge/release/launch-evidence-operator-summary.json",
    releaseSeal: ".dx/forge/release/launch-evidence-release-seal.json",
    briefTarget: "dx-cli-zed-launch-closeout-pointer",
    noExecution: true,
  },
  launchEvidenceOperatorRunbook: {
    schema: "dx.launch.evidence_operator_runbook",
    file: ".dx/forge/release/launch-evidence-operator-runbook.json",
    command: "dx forge launch-evidence-operator-runbook --project <path> --write",
    finalBrief: ".dx/forge/release/launch-evidence-final-brief.json",
    closureMemo: ".dx/forge/release/launch-evidence-closure-memo.md",
    completionLedger: ".dx/forge/release/launch-evidence-completion-ledger.json",
    operatorSummary: ".dx/forge/release/launch-evidence-operator-summary.json",
    releaseSeal: ".dx/forge/release/launch-evidence-release-seal.json",
    runbookTarget: "restartable-dx-worker-checklist",
    noExecution: true,
  },
  launchEvidenceHandoffCapsule: {
    schema: "dx.launch.evidence_handoff_capsule",
    file: ".dx/forge/release/launch-evidence-handoff-capsule.json",
    command: "dx forge launch-evidence-handoff-capsule --project <path> --write",
    operatorRunbook: ".dx/forge/release/launch-evidence-operator-runbook.json",
    finalBrief: ".dx/forge/release/launch-evidence-final-brief.json",
    closureMemo: ".dx/forge/release/launch-evidence-closure-memo.md",
    completionLedger: ".dx/forge/release/launch-evidence-completion-ledger.json",
    capsuleTarget: "dx-cli-zed-restart-artifact",
    noExecution: true,
  },
  launchEvidenceResumptionIndex: {
    schema: "dx.launch.evidence_resumption_index",
    file: ".dx/forge/release/launch-evidence-resumption-index.json",
    command: "dx forge launch-evidence-resumption-index --project <path> --write",
    handoffCapsule: ".dx/forge/release/launch-evidence-handoff-capsule.json",
    lanes: ["source-only", "runtime-approved", "release-closeout"],
    resumptionTarget: "ordered-dx-cli-zed-restart-lanes",
    noExecution: true,
  },
  launchEvidenceRecoveryBrief: {
    schema: "dx.launch.evidence_recovery_brief",
    file: ".dx/forge/release/launch-evidence-recovery-brief.md",
    command: "dx forge launch-evidence-recovery-brief --project <path> --write",
    resumptionIndex: ".dx/forge/release/launch-evidence-resumption-index.json",
    handoffCapsule: ".dx/forge/release/launch-evidence-handoff-capsule.json",
    operatorRunbook: ".dx/forge/release/launch-evidence-operator-runbook.json",
    finalBrief: ".dx/forge/release/launch-evidence-final-brief.json",
    recoveryTarget: "human-readable-dx-worker-restart-brief",
    format: "markdown",
    zedOpenable: true,
    noExecution: true,
  },
  launchEvidenceContinuationPacket: {
    schema: "dx.launch.evidence_continuation_packet",
    file: ".dx/forge/release/launch-evidence-continuation-packet.json",
    command: "dx forge launch-evidence-continuation-packet --project <path> --write",
    recoveryBrief: ".dx/forge/release/launch-evidence-recovery-brief.md",
    resumptionIndex: ".dx/forge/release/launch-evidence-resumption-index.json",
    handoffCapsule: ".dx/forge/release/launch-evidence-handoff-capsule.json",
    operatorRunbook: ".dx/forge/release/launch-evidence-operator-runbook.json",
    continuationTarget: "dx-cli-zed-continuation-packet",
    noExecution: true,
  },
  launchEvidenceOperatorResumeCard: {
    schema: "dx.launch.evidence_operator_resume_card",
    file: ".dx/forge/release/launch-evidence-operator-resume-card.json",
    command: "dx forge launch-evidence-operator-resume-card --project <path> --write",
    continuationPacket: ".dx/forge/release/launch-evidence-continuation-packet.json",
    recoveryBrief: ".dx/forge/release/launch-evidence-recovery-brief.md",
    resumeTarget: "terminal-first-dx-resume-card",
    displayMode: "terminal-first",
    noExecution: true,
  },
  launchEvidenceRestartLedger: {
    schema: "dx.launch.evidence_restart_ledger",
    file: ".dx/forge/release/launch-evidence-restart-ledger.json",
    command: "dx forge launch-evidence-restart-ledger --project <path> --write",
    operatorResumeCard: ".dx/forge/release/launch-evidence-operator-resume-card.json",
    continuationPacket: ".dx/forge/release/launch-evidence-continuation-packet.json",
    recoveryBrief: ".dx/forge/release/launch-evidence-recovery-brief.md",
    resumptionIndex: ".dx/forge/release/launch-evidence-resumption-index.json",
    ledgerTarget: "durable-dx-restart-ledger",
    displayMode: "terminal-first",
    noExecution: true,
  },
  launchEvidenceRestartChecklist: {
    schema: "dx.launch.evidence_restart_checklist",
    file: ".dx/forge/release/launch-evidence-restart-checklist.json",
    command: "dx forge launch-evidence-restart-checklist --project <path> --write",
    restartLedger: ".dx/forge/release/launch-evidence-restart-ledger.json",
    checklistTarget: "dx-cli-zed-restart-next-actions",
    lanes: ["source-only", "runtime-approved", "release-closeout"],
    displayMode: "terminal-first",
    noExecution: true,
  },
  launchEvidenceRestartBrief: {
    schema: "dx.launch.evidence_restart_brief",
    file: ".dx/forge/release/launch-evidence-restart-brief.md",
    command: "dx forge launch-evidence-restart-brief --project <path> --write",
    restartChecklist: ".dx/forge/release/launch-evidence-restart-checklist.json",
    restartLedger: ".dx/forge/release/launch-evidence-restart-ledger.json",
    briefTarget: "zed-openable-dx-restart-brief",
    format: "markdown",
    zedOpenable: true,
    noExecution: true,
  },
  launchEvidenceRestartManifest: {
    schema: "dx.launch.evidence_restart_manifest",
    file: ".dx/forge/release/launch-evidence-restart-manifest.json",
    command: "dx forge launch-evidence-restart-manifest --project <path> --write",
    restartBrief: ".dx/forge/release/launch-evidence-restart-brief.md",
    restartChecklist: ".dx/forge/release/launch-evidence-restart-checklist.json",
    restartLedger: ".dx/forge/release/launch-evidence-restart-ledger.json",
    operatorResumeCard: ".dx/forge/release/launch-evidence-operator-resume-card.json",
    manifestTarget: "dx-cli-zed-indexable-restart-manifest",
    noExecution: true,
  },
  launchEvidenceRestartReceipt: {
    schema: "dx.launch.evidence_restart_receipt",
    file: ".dx/forge/release/launch-evidence-restart-receipt.json",
    command: "dx forge launch-evidence-restart-receipt --project <path> --write",
    restartManifest: ".dx/forge/release/launch-evidence-restart-manifest.json",
    receiptTarget: "latest-resumable-dx-zed-handoff",
    noExecution: true,
  },
  launchEvidenceRestartSummary: {
    schema: "dx.launch.evidence_restart_summary",
    file: ".dx/forge/release/launch-evidence-restart-summary.json",
    command: "dx forge launch-evidence-restart-summary --project <path> --write",
    restartReceipt: ".dx/forge/release/launch-evidence-restart-receipt.json",
    restartManifest: ".dx/forge/release/launch-evidence-restart-manifest.json",
    restartBrief: ".dx/forge/release/launch-evidence-restart-brief.md",
    restartChecklist: ".dx/forge/release/launch-evidence-restart-checklist.json",
    summaryTarget: "terminal-friendly-dx-zed-restart-handoff",
    displayMode: "terminal-first",
    noExecution: true,
  },
  launchEvidenceRestartSnapshot: {
    schema: "dx.launch.evidence_restart_snapshot",
    file: ".dx/forge/release/launch-evidence-restart-snapshot.json",
    command: "dx forge launch-evidence-restart-snapshot --project <path> --write",
    restartSummary: ".dx/forge/release/launch-evidence-restart-summary.json",
    restartReceipt: ".dx/forge/release/launch-evidence-restart-receipt.json",
    restartManifest: ".dx/forge/release/launch-evidence-restart-manifest.json",
    restartBrief: ".dx/forge/release/launch-evidence-restart-brief.md",
    snapshotTarget: "latest-openable-dx-zed-restart-file",
    displayMode: "openable-json",
    noExecution: true,
  },
  launchEvidenceRestartDispatch: {
    schema: "dx.launch.evidence_restart_dispatch",
    file: ".dx/forge/release/launch-evidence-restart-dispatch.json",
    command: "dx forge launch-evidence-restart-dispatch --project <path> --write",
    restartSnapshot: ".dx/forge/release/launch-evidence-restart-snapshot.json",
    restartSummary: ".dx/forge/release/launch-evidence-restart-summary.json",
    restartReceipt: ".dx/forge/release/launch-evidence-restart-receipt.json",
    restartManifest: ".dx/forge/release/launch-evidence-restart-manifest.json",
    dispatchTarget: "one-command-next-worker-dispatch-card",
    displayMode: "next-worker-card",
    noExecution: true,
  },
  launchEvidenceRestartCloseout: {
    schema: "dx.launch.evidence_restart_closeout",
    file: ".dx/forge/release/launch-evidence-restart-closeout.md",
    command: "dx forge launch-evidence-restart-closeout --project <path> --write",
    restartDispatch: ".dx/forge/release/launch-evidence-restart-dispatch.json",
    closeoutTarget: "final-friday-essencefromexistence-closeout-actions",
    format: "markdown",
    zedOpenable: true,
    noExecution: true,
  },
  launchEvidenceRestartSignoff: {
    schema: "dx.launch.evidence_restart_signoff",
    file: ".dx/forge/release/launch-evidence-restart-signoff.json",
    command: "dx forge launch-evidence-restart-signoff --project <path> --write",
    restartCloseout: ".dx/forge/release/launch-evidence-restart-closeout.md",
    signoffTarget: "friday-essencefromexistence-acceptance-receipt",
    acceptanceStatus: "reviewable",
    noExecution: true,
  },
  launchEvidenceAcceptanceIndex: {
    schema: "dx.launch.evidence_acceptance_index",
    file: ".dx/forge/release/launch-evidence-acceptance-index.md",
    command: "dx forge launch-evidence-acceptance-index --project <path> --write",
    restartSignoff: ".dx/forge/release/launch-evidence-restart-signoff.json",
    restartCloseout: ".dx/forge/release/launch-evidence-restart-closeout.md",
    restartDispatch: ".dx/forge/release/launch-evidence-restart-dispatch.json",
    restartSnapshot: ".dx/forge/release/launch-evidence-restart-snapshot.json",
    acceptanceTarget: "friday-final-handoff-index",
    format: "markdown",
    zedOpenable: true,
    noExecution: true,
  },
  launchEvidenceAcceptanceDigest: {
    schema: "dx.launch.evidence_acceptance_digest",
    file: ".dx/forge/release/launch-evidence-acceptance-digest.json",
    command: "dx forge launch-evidence-acceptance-digest --project <path> --write",
    acceptanceIndex: ".dx/forge/release/launch-evidence-acceptance-index.md",
    digestTarget: "friday-terminal-final-status-line",
    format: "json",
    displayMode: "terminal-first-final-status",
    zedOpenable: true,
    noExecution: true,
  },
  launchEvidenceFridayBaton: {
    schema: "dx.launch.evidence_friday_baton",
    file: ".dx/forge/release/launch-evidence-friday-baton.md",
    command: "dx forge launch-evidence-friday-baton --project <path> --write",
    acceptanceDigest: ".dx/forge/release/launch-evidence-acceptance-digest.json",
    acceptanceIndex: ".dx/forge/release/launch-evidence-acceptance-index.md",
    restartSignoff: ".dx/forge/release/launch-evidence-restart-signoff.json",
    launchVerificationLane: ".dx/forge/template-readiness/launch-verification-lane.json",
    batonTarget: "friday-orchestrator-final-handoff",
    format: "markdown",
    zedOpenable: true,
    noExecution: true,
  },
  noExecution: true,
  materializedFiles: launchRouteMaterializedFiles,
} as const;

export function launchRoutePackageIds() {
  return launchPackageCatalog.map((item) => item.packageId);
}
export function launchRouteRuntimeInputs() {
  return {
    requiredEnv: requiredLaunchEnv(),
    catalog: templateCatalogSummary(),
  };
}
export function launchRouteReadinessSummary() {
  return {
    requiredPackageCount: launchPackageCatalog.length,
    materializedFileCount: launchRouteMaterializedFiles.length,
    readinessBundleFile: templateRouteContract.launchReadinessBundle.file,
    evidencePacketFile: templateRouteContract.launchEvidencePacket.file,
    operatorIndexFile: templateRouteContract.launchEvidenceOperatorIndex.file,
    statusTimelineFile: templateRouteContract.launchEvidenceStatusTimeline.file,
    handoffDigestFile: templateRouteContract.launchEvidenceHandoffDigest.file,
    releaseChecklistFile: templateRouteContract.launchEvidenceReleaseChecklist.file,
    shareManifestFile: templateRouteContract.launchEvidenceShareManifest.file,
    archiveIndexFile: templateRouteContract.launchEvidenceArchiveIndex.file,
    archiveReceiptFile: templateRouteContract.launchEvidenceArchiveReceipt.file,
    archiveLedgerFile: templateRouteContract.launchEvidenceArchiveLedger.file,
    retentionPolicyFile: templateRouteContract.launchEvidenceRetentionPolicy.file,
    retentionReviewFile: templateRouteContract.launchEvidenceRetentionReview.file,
    releaseSealFile: templateRouteContract.launchEvidenceReleaseSeal.file,
    operatorSummaryFile: templateRouteContract.launchEvidenceOperatorSummary.file,
    completionLedgerFile: templateRouteContract.launchEvidenceCompletionLedger.file,
    closureMemoFile: templateRouteContract.launchEvidenceClosureMemo.file,
    finalBriefFile: templateRouteContract.launchEvidenceFinalBrief.file,
    operatorRunbookFile: templateRouteContract.launchEvidenceOperatorRunbook.file,
    handoffCapsuleFile: templateRouteContract.launchEvidenceHandoffCapsule.file,
    resumptionIndexFile: templateRouteContract.launchEvidenceResumptionIndex.file,
    recoveryBriefFile: templateRouteContract.launchEvidenceRecoveryBrief.file,
    continuationPacketFile: templateRouteContract.launchEvidenceContinuationPacket.file,
    operatorResumeCardFile: templateRouteContract.launchEvidenceOperatorResumeCard.file,
    restartLedgerFile: templateRouteContract.launchEvidenceRestartLedger.file,
    restartChecklistFile: templateRouteContract.launchEvidenceRestartChecklist.file,
    restartBriefFile: templateRouteContract.launchEvidenceRestartBrief.file,
    restartManifestFile: templateRouteContract.launchEvidenceRestartManifest.file,
    restartReceiptFile: templateRouteContract.launchEvidenceRestartReceipt.file,
    restartSummaryFile: templateRouteContract.launchEvidenceRestartSummary.file,
    restartSnapshotFile: templateRouteContract.launchEvidenceRestartSnapshot.file,
    restartDispatchFile: templateRouteContract.launchEvidenceRestartDispatch.file,
    restartCloseoutFile: templateRouteContract.launchEvidenceRestartCloseout.file,
    restartSignoffFile: templateRouteContract.launchEvidenceRestartSignoff.file,
    acceptanceIndexFile: templateRouteContract.launchEvidenceAcceptanceIndex.file,
    acceptanceDigestFile: templateRouteContract.launchEvidenceAcceptanceDigest.file,
    fridayBatonFile: templateRouteContract.launchEvidenceFridayBaton.file,
    checksPassed: 1,
    checksPending: 1,
    runtimeGate: templateRouteContract.runtimeVerification,
  };
}
