/* Generated by dx imports sync. */
/* Keep source files editable; regenerate after moves or export changes. */

export const dxAutoImportMap = {
  "components": [
    {
      "kind": "dx-icon",
      "name": "Icon",
      "source": "components/icons/icon.tsx",
      "import_path": "@/components/icons/icon",
      "barrel_export": null,
      "exports": [
        "Icon",
        "IconProps"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "Icon",
        "IconProps"
      ],
      "type_exports": [
        "IconProps"
      ]
    }
  ],
  "composables": [],
  "utilities": [],
  "forgePackages": [
    {
      "packageId": "cargo/serde",
      "source": "forge/cargo/serde",
      "importPath": "@/forge/cargo/serde",
      "exports": []
    },
    {
      "packageId": "go/quote",
      "source": "forge/go/quote",
      "importPath": "@/forge/go/quote",
      "exports": []
    },
    {
      "packageId": "npm/clsx",
      "source": "forge/npm/clsx",
      "importPath": "@/forge/npm/clsx",
      "exports": []
    },
    {
      "packageId": "npm/lodash",
      "source": "forge/npm/lodash",
      "importPath": "@/forge/npm/lodash",
      "exports": []
    },
    {
      "packageId": "pip/requests",
      "source": "forge/pip/requests",
      "importPath": "@/forge/pip/requests",
      "exports": []
    },
    {
      "packageId": "www/minimal-starter",
      "source": "forge/www/minimal-starter",
      "importPath": "@/forge/www/minimal-starter",
      "exports": []
    }
  ],
  "styleHelpers": [
    {
      "name": "generated.css",
      "source": "styles/generated.css",
      "importPath": "@/styles/generated.css"
    },
    {
      "name": "theme.css",
      "source": "styles/theme.css",
      "importPath": "@/styles/theme.css"
    }
  ],
  "sourceHash": "blake3:26ae3c984185a2a8596ff3ac773ca0a3027e6606fccba3605aec9cf84755f85c"
} as const;

export type DxAutoImportComponent = typeof dxAutoImportMap.components[number]["name"];
export type DxAutoImportComposable = typeof dxAutoImportMap.composables[number]["name"];
export type DxAutoImportUtility = typeof dxAutoImportMap.utilities[number]["name"];
export type DxAutoImportForgePackage = typeof dxAutoImportMap.forgePackages[number]["packageId"];
export type DxAutoImportStyleHelper = typeof dxAutoImportMap.styleHelpers[number]["name"];
