export const dxMobileCompanionContract = {
  appName: "DX Mobile App",
  purpose: "Zed and DX Agents native companion",
  wwwRuntime: "DX WWW App Router",
  nativeRuntime: "DX Native",
  bridge: "dx-native-mobile-companion",
  nativeShell: "tauri-webview",
  nativeConfig: "src-tauri/tauri.conf.json",
  nativeShellReceipt: ".dx/native/native-shell-receipt.json",
  nativeArtifacts: {
    wwwOutputDirectory: ".dx/www/output",
    sourceRuntime: "public/mobile-companion-runtime.js",
    packagedRuntime: ".dx/www/output/public/mobile-companion-runtime.js",
    nativeEntrypoint: ".dx/www/output/index.html",
    androidBuildReceipt: ".dx/native/android-build-receipt.json",
    androidDebugApk: "src-tauri/gen/android/app/build/outputs/apk/arm64/debug/app-arm64-debug.apk",
    refreshCommand: "dx www build --target android",
    currentProofRequired: true,
  },
  nativeBundleId: "com.essencefromexistence.dx.mobile",
  styleSurface: "dx-mobile-companion-screen",
  checkSurface: "dx-mobile-companion",
  pairingContract: "dx.mobile.pairing",
  chatContract: "dx.mobile.chat_handoff",
  forgePackages: ["auth/better-auth"],
  gatewayRuntime: "dx-agents",
  runtimeStatus: "source-ready",
  gateway: {
    healthEndpoint: "/health",
    gatewayPairEndpoint: "/pair",
    deviceRegistryPairEndpoint: "/api/pair",
    deviceListEndpoint: "/api/devices",
    deviceCapabilitiesEndpoint: "/api/devices/me/capabilities",
    sessionsEndpoint: "/api/sessions",
    sessionMessagesEndpoint: "/api/sessions/:session_key/messages",
    eventsEndpoint: "/api/events",
    chatWebSocket: "/ws/chat",
    chatWebSocketRequiredQuery: ["agent", "session_id"],
    acpWebSocket: "/acp",
  },
  gatewayOriginPolicy: {
    httpsRequiredForRemote: true,
    httpLoopbackOnly: true,
    forbidCredentials: true,
  },
  credentialTokenPolicy: {
    acceptedAuthorizationScheme: "Bearer",
    storageShape: "raw-bearer-token",
    trimEdgeWhitespace: true,
    stripSingleAuthorizationScheme: true,
    rejectEmptyToken: true,
    rejectWhitespaceOrControlCharacters: true,
    rejectNestedAuthorizationScheme: true,
    allowedTransports: ["Authorization", "Sec-WebSocket-Protocol"],
    forbiddenTransports: ["URL query", "DOM attributes", "sessionStorage", "localStorage"],
  },
  identityValidationPolicy: {
    pairingCode: {
      required: true,
      maxLength: 128,
      trimEdgeWhitespace: true,
      rejectWhitespaceOrControlCharacters: true,
    },
    sessionId: {
      maxLength: 128,
      stripGatewayPrefix: "gw_",
      rejectWhitespaceOrControlCharacters: true,
      transports: ["pairing-request", "websocket-query", "gateway-connect-frame"],
    },
    sessionKey: {
      maxLength: 256,
      rejectWhitespaceOrControlCharacters: true,
      transports: ["pairing-request", "message-history-path"],
    },
    agentAlias: {
      maxLength: 64,
      defaultValue: "friday",
      rejectWhitespaceOrControlCharacters: true,
      transports: ["websocket-query"],
    },
    domDisclosure: "field-names-only-no-live-identifiers",
  },
  suggestedAgentAlias: "friday",
  sessionIdentity: {
    canonicalSessionKey: "session_key",
    zedThreadMetadataKey: "session_id",
    gatewaySessionKey: "session_key",
    acpSessionKey: "session_id",
  },
  nativeCommands: {
    contract: "dx_mobile_companion_contract",
    credentialStoreStatus: "dx_mobile_credential_store_status",
    parsePairingPayload: "dx_mobile_parse_pairing_payload",
    storeDeviceCredential: "dx_mobile_store_device_credential",
    loadDeviceCredential: "dx_mobile_load_device_credential",
    clearDeviceCredential: "dx_mobile_clear_device_credential",
    scanPairingQr: "dx_mobile_scan_pairing_qr",
  },
  pairingPayload: {
    preferredScheme: "dxmobile://pair",
    allowedSchemes: ["dxmobile", "https", "http"],
    challengeTtlSeconds: 300,
    requiredFields: ["gateway", "code"],
    rejectConflictingAliases: true,
    rejectRepeatedQueryFields: true,
    aliasGroups: {
      gateway: ["gateway", "gateway_origin", "origin"],
      code: ["code", "pairing_code"],
      agent: ["agent_alias", "agent"],
    },
    forbiddenFields: [
      "token",
      "bearer",
      "authorization",
      "access_token",
      "refresh_token",
      "id_token",
      "client_secret",
      "api_key",
      "x_api_key",
    ],
  },
  mobileCapabilities: [
    "mobile.pairing.scan_qr",
    "mobile.chat.read",
    "mobile.chat.send",
    "mobile.approvals.respond",
    "mobile.context.preview",
  ],
  securityBoundaries: [
    "Never encode bearer tokens in QR payloads",
    "Store durable credentials through native secure storage only",
    "Use Authorization or WebSocket bearer subprotocols, never query-string tokens",
    "Keep concrete session_id and session_key values out of public DOM attributes and visible labels",
    "Route live chat through gateway WebSocket or ACP, not receipt polling",
    "Render approval summaries only after gateway redaction",
  ],
} as const;

export type DxMobileCompanionContract = typeof dxMobileCompanionContract;
