/* Generated by dx imports sync. */
/* Keep source files editable; regenerate after moves or export changes. */
export * from "./docs/components-index";
export * from "./gallery/primitive-gallery";
export * from "./gallery/primitive-preview";
export * from "./home/ui-components-home";
export * from "./site/dependency-replacement";
export * from "./site/registry-map";
export * from "./site/site-header";
export * from "./site/site-shell";
export * from "./ui/accordion";
export * from "./ui/alert";
export * from "./ui/badge";
export * from "./ui/button";
export * from "./ui/calendar";
export * from "./ui/carousel";
export * from "./ui/checkbox";
export * from "./ui/collapsible";
export * from "./ui/input";
export * from "./ui/kbd";
export * from "./ui/label";
export * from "./ui/progress";
export * from "./ui/separator";
export * from "./ui/skeleton";
export * from "./ui/slider";
export * from "./ui/slot";
export * from "./ui/sonner";
export * from "./ui/spinner";
export * from "./ui/switch";
export * from "./ui/tabs";
export * from "./ui/textarea";
export * from "./ui/toggle";
export * from "./ui/tooltip";
export * from "./ui/types";
export * from "./icons/icon";

export const dxAutoImportMap = {
  "components": [
    {
      "kind": "component",
      "name": "ComponentsIndex",
      "source": "components/docs/components-index.tsx",
      "import_path": "@/components/docs/components-index",
      "barrel_export": "./docs/components-index",
      "exports": [
        "ComponentsIndex"
      ],
      "default_export_name": null,
      "used_exports": [
        "ComponentsIndex"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "ComponentGallery",
      "source": "components/gallery/primitive-gallery.tsx",
      "import_path": "@/components/gallery/primitive-gallery",
      "barrel_export": "./gallery/primitive-gallery",
      "exports": [
        "ComponentGallery"
      ],
      "default_export_name": null,
      "used_exports": [
        "ComponentGallery"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "PrimitivePreview",
      "source": "components/gallery/primitive-preview.tsx",
      "import_path": "@/components/gallery/primitive-preview",
      "barrel_export": "./gallery/primitive-preview",
      "exports": [
        "PrimitivePreview"
      ],
      "default_export_name": null,
      "used_exports": [
        "PrimitivePreview"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "UiComponentsHome",
      "source": "components/home/ui-components-home.tsx",
      "import_path": "@/components/home/ui-components-home",
      "barrel_export": "./home/ui-components-home",
      "exports": [
        "UiComponentsHome"
      ],
      "default_export_name": null,
      "used_exports": [
        "UiComponentsHome"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "DependencyReplacement",
      "source": "components/site/dependency-replacement.tsx",
      "import_path": "@/components/site/dependency-replacement",
      "barrel_export": "./site/dependency-replacement",
      "exports": [
        "DependencyReplacement"
      ],
      "default_export_name": null,
      "used_exports": [
        "DependencyReplacement"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "RegistryMap",
      "source": "components/site/registry-map.tsx",
      "import_path": "@/components/site/registry-map",
      "barrel_export": "./site/registry-map",
      "exports": [
        "RegistryMap"
      ],
      "default_export_name": null,
      "used_exports": [
        "RegistryMap"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "SiteHeader",
      "source": "components/site/site-header.tsx",
      "import_path": "@/components/site/site-header",
      "barrel_export": "./site/site-header",
      "exports": [
        "SiteHeader"
      ],
      "default_export_name": null,
      "used_exports": [
        "SiteHeader"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "SiteShell",
      "source": "components/site/site-shell.tsx",
      "import_path": "@/components/site/site-shell",
      "barrel_export": "./site/site-shell",
      "exports": [
        "SiteShell"
      ],
      "default_export_name": null,
      "used_exports": [
        "SiteShell"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Accordion",
      "source": "components/ui/accordion.tsx",
      "import_path": "@/components/ui/accordion",
      "barrel_export": "./ui/accordion",
      "exports": [
        "Accordion",
        "AccordionContent",
        "AccordionItem",
        "AccordionTrigger"
      ],
      "default_export_name": null,
      "used_exports": [
        "Accordion"
      ],
      "unused_exports": [
        "AccordionContent",
        "AccordionItem",
        "AccordionTrigger"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "AdapterBoundary",
      "source": "components/ui/adapter-boundary.tsx",
      "import_path": "@/components/ui/adapter-boundary",
      "barrel_export": null,
      "exports": [
        "AdapterBoundary",
        "AdapterBoundaryProps"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "AdapterBoundary",
        "AdapterBoundaryProps"
      ],
      "type_exports": [
        "AdapterBoundaryProps"
      ]
    },
    {
      "kind": "component",
      "name": "Alert",
      "source": "components/ui/alert.tsx",
      "import_path": "@/components/ui/alert",
      "barrel_export": "./ui/alert",
      "exports": [
        "Alert",
        "AlertDescription",
        "AlertTitle"
      ],
      "default_export_name": null,
      "used_exports": [
        "Alert"
      ],
      "unused_exports": [
        "AlertDescription",
        "AlertTitle"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "AspectRatio",
      "source": "components/ui/aspect-ratio.tsx",
      "import_path": "@/components/ui/aspect-ratio",
      "barrel_export": null,
      "exports": [
        "AspectRatio"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "AspectRatio"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Badge",
      "source": "components/ui/badge.tsx",
      "import_path": "@/components/ui/badge",
      "barrel_export": "./ui/badge",
      "exports": [
        "Badge",
        "BadgeProps",
        "badgeVariants"
      ],
      "default_export_name": null,
      "used_exports": [
        "Badge"
      ],
      "unused_exports": [
        "BadgeProps",
        "badgeVariants"
      ],
      "type_exports": [
        "BadgeProps"
      ]
    },
    {
      "kind": "component",
      "name": "Button",
      "source": "components/ui/button.tsx",
      "import_path": "@/components/ui/button",
      "barrel_export": "./ui/button",
      "exports": [
        "Button",
        "ButtonProps",
        "buttonVariants"
      ],
      "default_export_name": null,
      "used_exports": [
        "Button",
        "ButtonProps",
        "buttonVariants"
      ],
      "unused_exports": [],
      "type_exports": [
        "ButtonProps"
      ]
    },
    {
      "kind": "component",
      "name": "Calendar",
      "source": "components/ui/calendar.tsx",
      "import_path": "@/components/ui/calendar",
      "barrel_export": "./ui/calendar",
      "exports": [
        "Calendar",
        "CalendarDayButton"
      ],
      "default_export_name": null,
      "used_exports": [
        "Calendar"
      ],
      "unused_exports": [
        "CalendarDayButton"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Carousel",
      "source": "components/ui/carousel.tsx",
      "import_path": "@/components/ui/carousel",
      "barrel_export": "./ui/carousel",
      "exports": [
        "Carousel",
        "CarouselApi",
        "CarouselContent",
        "CarouselItem",
        "CarouselNext",
        "CarouselPrevious"
      ],
      "default_export_name": null,
      "used_exports": [
        "Carousel"
      ],
      "unused_exports": [
        "CarouselApi",
        "CarouselContent",
        "CarouselItem",
        "CarouselNext",
        "CarouselPrevious"
      ],
      "type_exports": [
        "CarouselApi"
      ]
    },
    {
      "kind": "component",
      "name": "Checkbox",
      "source": "components/ui/checkbox.tsx",
      "import_path": "@/components/ui/checkbox",
      "barrel_export": "./ui/checkbox",
      "exports": [
        "Checkbox"
      ],
      "default_export_name": null,
      "used_exports": [
        "Checkbox"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Collapsible",
      "source": "components/ui/collapsible.tsx",
      "import_path": "@/components/ui/collapsible",
      "barrel_export": "./ui/collapsible",
      "exports": [
        "Collapsible",
        "CollapsibleContent",
        "CollapsibleTrigger"
      ],
      "default_export_name": null,
      "used_exports": [
        "Collapsible"
      ],
      "unused_exports": [
        "CollapsibleContent",
        "CollapsibleTrigger"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "DirectionProvider",
      "source": "components/ui/direction.tsx",
      "import_path": "@/components/ui/direction",
      "barrel_export": null,
      "exports": [
        "DirectionProvider",
        "useDirection"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "DirectionProvider",
        "useDirection"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "FieldOrientation",
      "source": "components/ui/field.tsx",
      "import_path": "@/components/ui/field",
      "barrel_export": null,
      "exports": [
        "FieldOrientation",
        "FieldVariantOptions"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "FieldOrientation",
        "FieldVariantOptions"
      ],
      "type_exports": [
        "FieldOrientation",
        "FieldVariantOptions"
      ]
    },
    {
      "kind": "component",
      "name": "HoverCard",
      "source": "components/ui/hover-card.tsx",
      "import_path": "@/components/ui/hover-card",
      "barrel_export": null,
      "exports": [
        "HoverCard",
        "HoverCardContent",
        "HoverCardTrigger"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "HoverCard",
        "HoverCardContent",
        "HoverCardTrigger"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "InputOTP",
      "source": "components/ui/input-otp.tsx",
      "import_path": "@/components/ui/input-otp",
      "barrel_export": null,
      "exports": [
        "InputOTP",
        "InputOTPGroup",
        "InputOTPSeparator",
        "InputOTPSlot"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "InputOTP",
        "InputOTPGroup",
        "InputOTPSeparator",
        "InputOTPSlot"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Input",
      "source": "components/ui/input.tsx",
      "import_path": "@/components/ui/input",
      "barrel_export": "./ui/input",
      "exports": [
        "Input"
      ],
      "default_export_name": null,
      "used_exports": [
        "Input"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Kbd",
      "source": "components/ui/kbd.tsx",
      "import_path": "@/components/ui/kbd",
      "barrel_export": "./ui/kbd",
      "exports": [
        "Kbd",
        "KbdGroup"
      ],
      "default_export_name": null,
      "used_exports": [
        "Kbd"
      ],
      "unused_exports": [
        "KbdGroup"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Label",
      "source": "components/ui/label.tsx",
      "import_path": "@/components/ui/label",
      "barrel_export": "./ui/label",
      "exports": [
        "Label",
        "LabelProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "Label",
        "LabelProps"
      ],
      "unused_exports": [],
      "type_exports": [
        "LabelProps"
      ]
    },
    {
      "kind": "component",
      "name": "NativeSelect",
      "source": "components/ui/native-select.tsx",
      "import_path": "@/components/ui/native-select",
      "barrel_export": null,
      "exports": [
        "NativeSelect",
        "NativeSelectOptGroup",
        "NativeSelectOption"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "NativeSelect",
        "NativeSelectOptGroup",
        "NativeSelectOption"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Progress",
      "source": "components/ui/progress.tsx",
      "import_path": "@/components/ui/progress",
      "barrel_export": "./ui/progress",
      "exports": [
        "Progress"
      ],
      "default_export_name": null,
      "used_exports": [
        "Progress"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "RadioGroup",
      "source": "components/ui/radio-group.tsx",
      "import_path": "@/components/ui/radio-group",
      "barrel_export": null,
      "exports": [
        "RadioGroup",
        "RadioGroupItem"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "RadioGroup",
        "RadioGroupItem"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "ResizableHandle",
      "source": "components/ui/resizable.tsx",
      "import_path": "@/components/ui/resizable",
      "barrel_export": null,
      "exports": [
        "ResizableHandle",
        "ResizablePanel",
        "ResizablePanelGroup"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ResizableHandle",
        "ResizablePanel",
        "ResizablePanelGroup"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "ScrollArea",
      "source": "components/ui/scroll-area.tsx",
      "import_path": "@/components/ui/scroll-area",
      "barrel_export": null,
      "exports": [
        "ScrollArea",
        "ScrollBar"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ScrollArea",
        "ScrollBar"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Separator",
      "source": "components/ui/separator.tsx",
      "import_path": "@/components/ui/separator",
      "barrel_export": "./ui/separator",
      "exports": [
        "Separator",
        "SeparatorOrientation",
        "SeparatorProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "Separator",
        "SeparatorProps"
      ],
      "unused_exports": [
        "SeparatorOrientation"
      ],
      "type_exports": [
        "SeparatorOrientation",
        "SeparatorProps"
      ]
    },
    {
      "kind": "component",
      "name": "Skeleton",
      "source": "components/ui/skeleton.tsx",
      "import_path": "@/components/ui/skeleton",
      "barrel_export": "./ui/skeleton",
      "exports": [
        "Skeleton"
      ],
      "default_export_name": null,
      "used_exports": [
        "Skeleton"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Slider",
      "source": "components/ui/slider.tsx",
      "import_path": "@/components/ui/slider",
      "barrel_export": "./ui/slider",
      "exports": [
        "Slider"
      ],
      "default_export_name": null,
      "used_exports": [
        "Slider"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Slot",
      "source": "components/ui/slot.tsx",
      "import_path": "@/components/ui/slot",
      "barrel_export": "./ui/slot",
      "exports": [
        "Slot",
        "SlotProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "Slot"
      ],
      "unused_exports": [
        "SlotProps"
      ],
      "type_exports": [
        "SlotProps"
      ]
    },
    {
      "kind": "component",
      "name": "Toaster",
      "source": "components/ui/sonner.tsx",
      "import_path": "@/components/ui/sonner",
      "barrel_export": "./ui/sonner",
      "exports": [
        "Toaster"
      ],
      "default_export_name": null,
      "used_exports": [
        "Toaster"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Spinner",
      "source": "components/ui/spinner.tsx",
      "import_path": "@/components/ui/spinner",
      "barrel_export": "./ui/spinner",
      "exports": [
        "Spinner"
      ],
      "default_export_name": null,
      "used_exports": [
        "Spinner"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Switch",
      "source": "components/ui/switch.tsx",
      "import_path": "@/components/ui/switch",
      "barrel_export": "./ui/switch",
      "exports": [
        "Switch"
      ],
      "default_export_name": null,
      "used_exports": [
        "Switch"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Tabs",
      "source": "components/ui/tabs.tsx",
      "import_path": "@/components/ui/tabs",
      "barrel_export": "./ui/tabs",
      "exports": [
        "Tabs",
        "TabsContent",
        "TabsList",
        "TabsTrigger",
        "tabsListVariants"
      ],
      "default_export_name": null,
      "used_exports": [
        "Tabs"
      ],
      "unused_exports": [
        "TabsContent",
        "TabsList",
        "TabsTrigger",
        "tabsListVariants"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Textarea",
      "source": "components/ui/textarea.tsx",
      "import_path": "@/components/ui/textarea",
      "barrel_export": "./ui/textarea",
      "exports": [
        "Textarea"
      ],
      "default_export_name": null,
      "used_exports": [
        "Textarea"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "ToggleGroup",
      "source": "components/ui/toggle-group.tsx",
      "import_path": "@/components/ui/toggle-group",
      "barrel_export": null,
      "exports": [
        "ToggleGroup",
        "ToggleGroupItem"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ToggleGroup",
        "ToggleGroupItem"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Toggle",
      "source": "components/ui/toggle.tsx",
      "import_path": "@/components/ui/toggle",
      "barrel_export": "./ui/toggle",
      "exports": [
        "Toggle",
        "ToggleProps",
        "toggleVariants"
      ],
      "default_export_name": null,
      "used_exports": [
        "Toggle",
        "ToggleProps"
      ],
      "unused_exports": [
        "toggleVariants"
      ],
      "type_exports": [
        "ToggleProps"
      ]
    },
    {
      "kind": "component",
      "name": "Tooltip",
      "source": "components/ui/tooltip.tsx",
      "import_path": "@/components/ui/tooltip",
      "barrel_export": "./ui/tooltip",
      "exports": [
        "Tooltip",
        "TooltipContent",
        "TooltipProvider",
        "TooltipTrigger"
      ],
      "default_export_name": null,
      "used_exports": [
        "Tooltip"
      ],
      "unused_exports": [
        "TooltipContent",
        "TooltipProvider",
        "TooltipTrigger"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "DxElementProps",
      "source": "components/ui/types.ts",
      "import_path": "@/components/ui/types",
      "barrel_export": "./ui/types",
      "exports": [
        "DxElementProps",
        "DxInputProps",
        "DxTextareaProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "DxElementProps",
        "DxInputProps",
        "DxTextareaProps"
      ],
      "unused_exports": [],
      "type_exports": [
        "DxElementProps",
        "DxInputProps",
        "DxTextareaProps"
      ]
    },
    {
      "kind": "dx-icon",
      "name": "Icon",
      "source": "components/icons/icon.tsx",
      "import_path": "@/components/icons/icon",
      "barrel_export": "./icons/icon",
      "exports": [
        "Icon",
        "IconProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "Icon",
        "IconProps"
      ],
      "unused_exports": [],
      "type_exports": [
        "IconProps"
      ]
    },
    {
      "kind": "dx-icon",
      "name": "PackArrowLeftIcon",
      "source": "components/icons/pack-arrow-left.tsx",
      "import_path": "@/components/icons/pack-arrow-left",
      "barrel_export": null,
      "exports": [
        "PackArrowLeftIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackArrowLeftIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackArrowRightIcon",
      "source": "components/icons/pack-arrow-right.tsx",
      "import_path": "@/components/icons/pack-arrow-right",
      "barrel_export": null,
      "exports": [
        "PackArrowRightIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackArrowRightIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackCheckIcon",
      "source": "components/icons/pack-check.tsx",
      "import_path": "@/components/icons/pack-check",
      "barrel_export": null,
      "exports": [
        "PackCheckIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackCheckIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackChevronDownIcon",
      "source": "components/icons/pack-chevron-down.tsx",
      "import_path": "@/components/icons/pack-chevron-down",
      "barrel_export": null,
      "exports": [
        "PackChevronDownIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackChevronDownIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackChevronLeftIcon",
      "source": "components/icons/pack-chevron-left.tsx",
      "import_path": "@/components/icons/pack-chevron-left",
      "barrel_export": null,
      "exports": [
        "PackChevronLeftIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackChevronLeftIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackChevronRightIcon",
      "source": "components/icons/pack-chevron-right.tsx",
      "import_path": "@/components/icons/pack-chevron-right",
      "barrel_export": null,
      "exports": [
        "PackChevronRightIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackChevronRightIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackChevronUpIcon",
      "source": "components/icons/pack-chevron-up.tsx",
      "import_path": "@/components/icons/pack-chevron-up",
      "barrel_export": null,
      "exports": [
        "PackChevronUpIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackChevronUpIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackGripVerticalIcon",
      "source": "components/icons/pack-grip-vertical.tsx",
      "import_path": "@/components/icons/pack-grip-vertical",
      "barrel_export": null,
      "exports": [
        "PackGripVerticalIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackGripVerticalIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackLoaderIcon",
      "source": "components/icons/pack-loader.tsx",
      "import_path": "@/components/icons/pack-loader",
      "barrel_export": null,
      "exports": [
        "PackLoaderIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackLoaderIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackMoreHorizontalIcon",
      "source": "components/icons/pack-more-horizontal.tsx",
      "import_path": "@/components/icons/pack-more-horizontal",
      "barrel_export": null,
      "exports": [
        "PackMoreHorizontalIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackMoreHorizontalIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackPanelLeftIcon",
      "source": "components/icons/pack-panel-left.tsx",
      "import_path": "@/components/icons/pack-panel-left",
      "barrel_export": null,
      "exports": [
        "PackPanelLeftIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackPanelLeftIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackSearchIcon",
      "source": "components/icons/pack-search.tsx",
      "import_path": "@/components/icons/pack-search",
      "barrel_export": null,
      "exports": [
        "PackSearchIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackSearchIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackXIcon",
      "source": "components/icons/pack-x.tsx",
      "import_path": "@/components/icons/pack-x",
      "barrel_export": null,
      "exports": [
        "PackXIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackXIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "SearchIcon",
      "source": "components/icons/search.tsx",
      "import_path": "@/components/icons/search",
      "barrel_export": null,
      "exports": [
        "SearchIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "SearchIcon"
      ],
      "type_exports": []
    }
  ],
  "composables": [],
  "utilities": [],
  "forgePackages": [
    {
      "packageId": "dx/icon/search",
      "source": "forge/dx/icon/search",
      "importPath": "@/forge/dx/icon/search",
      "exports": []
    },
    {
      "packageId": "shadcn/ui/badge",
      "source": "forge/shadcn/ui/badge",
      "importPath": "@/forge/shadcn/ui/badge",
      "exports": []
    },
    {
      "packageId": "shadcn/ui/button",
      "source": "forge/shadcn/ui/button",
      "importPath": "@/forge/shadcn/ui/button",
      "exports": []
    },
    {
      "packageId": "shadcn/ui/card",
      "source": "forge/shadcn/ui/card",
      "importPath": "@/forge/shadcn/ui/card",
      "exports": []
    },
    {
      "packageId": "shadcn/ui/field",
      "source": "forge/shadcn/ui/field",
      "importPath": "@/forge/shadcn/ui/field",
      "exports": []
    },
    {
      "packageId": "shadcn/ui/input",
      "source": "forge/shadcn/ui/input",
      "importPath": "@/forge/shadcn/ui/input",
      "exports": []
    },
    {
      "packageId": "shadcn/ui/item",
      "source": "forge/shadcn/ui/item",
      "importPath": "@/forge/shadcn/ui/item",
      "exports": []
    },
    {
      "packageId": "shadcn/ui/label",
      "source": "forge/shadcn/ui/label",
      "importPath": "@/forge/shadcn/ui/label",
      "exports": []
    },
    {
      "packageId": "shadcn/ui/separator",
      "source": "forge/shadcn/ui/separator",
      "importPath": "@/forge/shadcn/ui/separator",
      "exports": []
    },
    {
      "packageId": "shadcn/ui/textarea",
      "source": "forge/shadcn/ui/textarea",
      "importPath": "@/forge/shadcn/ui/textarea",
      "exports": []
    },
    {
      "packageId": "www/minimal-starter",
      "source": "forge/www/minimal-starter",
      "importPath": "@/forge/www/minimal-starter",
      "exports": []
    }
  ],
  "styleHelpers": [
    {
      "name": "generated.css",
      "source": "styles/generated.css",
      "importPath": "@/styles/generated.css"
    },
    {
      "name": "theme.css",
      "source": "styles/theme.css",
      "importPath": "@/styles/theme.css"
    }
  ],
  "sourceHash": "blake3:6e475aa7ad6e1c71f5a365c137a3d4edb00712161c84134383be8ef46f7a4290"
} as const;

export type DxAutoImportComponent = typeof dxAutoImportMap.components[number]["name"];
export type DxAutoImportComposable = typeof dxAutoImportMap.composables[number]["name"];
export type DxAutoImportUtility = typeof dxAutoImportMap.utilities[number]["name"];
export type DxAutoImportForgePackage = typeof dxAutoImportMap.forgePackages[number]["packageId"];
export type DxAutoImportStyleHelper = typeof dxAutoImportMap.styleHelpers[number]["name"];
