import { category } from "../lane-utils";
import type { WorldCategory } from "../contracts";

export const aiRealtimeWorkflowCategories: readonly WorldCategory[] = [
  category("ai", "AI, LLM, agents, and structured output", "Model providers with streaming, structured output, tool calls, and redaction boundaries.", [
    {
      id: "openai",
      name: "OpenAI",
      reason: "Primary model provider for structured output, tools, and agents.",
      runtime: "server",
      surface: "route handlers and server actions",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [{ name: "OPENAI_API_KEY", scope: "server", required: true, capability: "ai:generate" }],
      receipts: ["text-generation", "structured-output", "tool-call"],
    },
    {
      id: "anthropic",
      name: "Anthropic",
      reason: "Major model provider for coding and reasoning workflows.",
      runtime: "server",
      surface: "route handlers and server actions",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [{ name: "ANTHROPIC_API_KEY", scope: "server", required: true, capability: "ai:generate" }],
      receipts: ["text-generation", "structured-output", "tool-call"],
    },
    {
      id: "google-gemini",
      name: "Google Gemini",
      reason: "Major model provider with multimodal and workspace-adjacent use cases.",
      runtime: "server",
      surface: "route handlers and server actions",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [{ name: "GOOGLE_GENERATIVE_AI_API_KEY", scope: "server", required: true, capability: "ai:generate" }],
      receipts: ["text-generation", "structured-output", "multimodal"],
    },
  ]),
  category("realtime", "Realtime, collaboration, and presence", "Native and hosted realtime systems for presence, sync, and event streams.", [
    {
      id: "websocket-sse",
      name: "WebSocket/SSE",
      reason: "Native web protocol baseline with no provider dependency.",
      runtime: "server-and-browser",
      surface: "route handlers and browser event streams",
      adapter: "web-standard",
      validation: "preview-only",
      env: [],
      receipts: ["connection", "message-roundtrip", "disconnect"],
      frameworkSuggestion: "Add first-class SSE and WebSocket receipts for WWW route handlers.",
    },
    {
      id: "supabase-realtime",
      name: "Supabase Realtime",
      reason: "Database-driven realtime channel used widely in app stacks.",
      runtime: "server-and-browser",
      surface: "browser subscription and server auth token boundary",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "SUPABASE_URL", scope: "server", required: true, capability: "realtime:connect" },
        { name: "SUPABASE_SERVICE_ROLE_KEY", scope: "server", required: true, capability: "realtime:server" },
        { name: "NEXT_PUBLIC_SUPABASE_ANON_KEY", scope: "browser-public", required: false, capability: "realtime:browser" },
      ],
      receipts: ["channel-subscribe", "broadcast", "secret-boundary"],
    },
    {
      id: "ably",
      name: "Ably",
      reason: "Hosted realtime infrastructure for presence and pub/sub.",
      runtime: "server-and-browser",
      surface: "token route handler and browser client",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [{ name: "ABLY_API_KEY", scope: "server", required: true, capability: "realtime:token" }],
      receipts: ["token-request", "presence", "message-roundtrip"],
    },
    {
      id: "pusher",
      name: "Pusher",
      reason: "Hosted channels infrastructure with signed read-only channel and presence boundaries.",
      runtime: "server-and-browser",
      surface: "signed channel readiness route and browser client",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "PUSHER_APP_ID", scope: "server", required: true, capability: "realtime:read" },
        { name: "PUSHER_KEY", scope: "server", required: true, capability: "realtime:sign" },
        { name: "PUSHER_SECRET", scope: "server", required: true, capability: "realtime:sign" },
        { name: "PUSHER_CLUSTER", scope: "server", required: true, capability: "realtime:connect" },
      ],
      receipts: ["channel-list", "presence", "secret-boundary"],
    },
  ]),
  category("workflows", "Queues, jobs, cron, and workflows", "Async work systems that prove delivery, retries, signing, and replay.", [
    {
      id: "cloudflare-queues",
      name: "Cloudflare Queues",
      reason: "Edge queue baseline for Cloudflare-hosted workloads.",
      runtime: "edge",
      surface: "provider adapter and deployment manifest",
      adapter: "provider-platform",
      validation: "live-if-env-present",
      env: [{ name: "CLOUDFLARE_API_TOKEN", scope: "ci", required: true, capability: "queue:deploy" }],
      receipts: ["enqueue", "consume", "retry-policy"],
    },
    {
      id: "upstash-qstash",
      name: "Upstash QStash",
      reason: "HTTP task delivery fits route handlers and webhooks.",
      runtime: "server",
      surface: "route handlers and signed delivery",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "QSTASH_TOKEN", scope: "server", required: true, capability: "queue:send" },
        { name: "QSTASH_CURRENT_SIGNING_KEY", scope: "server", required: true, capability: "queue:verify" },
      ],
      receipts: ["publish", "signature-verify", "retry-policy"],
    },
    {
      id: "temporal",
      name: "Temporal",
      reason: "Durable workflow orchestration for complex product operations.",
      runtime: "server",
      surface: "server worker and workflow client",
      adapter: "provider-or-self-hosted",
      validation: "live-if-env-present",
      env: [
        { name: "TEMPORAL_ADDRESS", scope: "server", required: true, capability: "workflow:connect" },
        { name: "TEMPORAL_NAMESPACE", scope: "server", required: true, capability: "workflow:namespace" },
      ],
      receipts: ["workflow-start", "activity-complete", "cancellation"],
    },
  ]),
];
