import { category } from "../lane-utils";
import type { WorldCategory } from "../contracts";

export const commerceMediaSearchCategories: readonly WorldCategory[] = [
  category("payments", "Payments, billing, and commerce", "Payment providers with webhook, idempotency, and secret verification.", [
    {
      id: "stripe",
      name: "Stripe",
      reason: "Global payments baseline for checkout, subscriptions, and webhooks.",
      runtime: "server-and-browser",
      surface: "route handlers, checkout redirects, webhook handlers",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "STRIPE_SECRET_KEY", scope: "server", required: true, capability: "payments:charge" },
        { name: "STRIPE_WEBHOOK_SECRET", scope: "server", required: true, capability: "payments:webhook" },
        { name: "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY", scope: "browser-public", required: false, capability: "payments:browser" },
      ],
      receipts: ["webhook-signature", "checkout-smoke", "idempotency"],
    },
    {
      id: "lemon-squeezy",
      name: "Lemon Squeezy",
      reason: "Indie software commerce and merchant-of-record workflow.",
      runtime: "server-and-browser",
      surface: "checkout links and webhook handlers",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "LEMON_SQUEEZY_API_KEY", scope: "server", required: true, capability: "commerce:manage" },
        { name: "LEMON_SQUEEZY_WEBHOOK_SECRET", scope: "server", required: true, capability: "commerce:webhook" },
      ],
      receipts: ["checkout-link", "webhook-signature", "order-event"],
    },
    {
      id: "paddle",
      name: "Paddle",
      reason: "Merchant-of-record billing path for global SaaS.",
      runtime: "server-and-browser",
      surface: "checkout, customer portal, webhook handlers",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "PADDLE_API_KEY", scope: "server", required: true, capability: "commerce:manage" },
        { name: "PADDLE_WEBHOOK_SECRET", scope: "server", required: true, capability: "commerce:webhook" },
        { name: "NEXT_PUBLIC_PADDLE_CLIENT_TOKEN", scope: "browser-public", required: false, capability: "commerce:browser" },
      ],
      receipts: ["checkout", "webhook-signature", "portal"],
    },
  ]),
  category("storage", "Object storage, uploads, media, and CDN", "Upload and asset providers with signed URLs, cache policy, and privacy checks.", [
    {
      id: "aws-s3",
      name: "AWS S3",
      reason: "Industry baseline for object storage and signed uploads.",
      runtime: "server",
      surface: "route handlers and signed URL helpers",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "AWS_ACCESS_KEY_ID", scope: "server", required: true, capability: "storage:sign" },
        { name: "AWS_SECRET_ACCESS_KEY", scope: "server", required: true, capability: "storage:sign" },
        { name: "S3_BUCKET", scope: "server", required: true, capability: "storage:bucket" },
      ],
      receipts: ["signed-upload", "object-read", "cache-policy"],
    },
    {
      id: "cloudflare-r2",
      name: "Cloudflare R2",
      reason: "Low-egress object storage with S3-compatible behavior.",
      runtime: "server-or-edge",
      surface: "route handlers and signed URL helpers",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "R2_ACCOUNT_ID", scope: "server", required: true, capability: "storage:account" },
        { name: "R2_ACCESS_KEY_ID", scope: "server", required: true, capability: "storage:sign" },
        { name: "R2_SECRET_ACCESS_KEY", scope: "server", required: true, capability: "storage:sign" },
        { name: "R2_BUCKET", scope: "server", required: true, capability: "storage:bucket" },
      ],
      receipts: ["signed-upload", "object-read", "egress-policy"],
    },
    {
      id: "vercel-blob",
      name: "Vercel Blob",
      reason: "Deployment-platform storage path for Vercel-hosted projects.",
      runtime: "server-and-browser",
      surface: "route handlers and client upload tokens",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [{ name: "BLOB_READ_WRITE_TOKEN", scope: "server", required: true, capability: "storage:write" }],
      receipts: ["upload-token", "object-read", "cdn-header"],
    },
  ]),
  category("search", "Search and discovery", "Search providers with index, query, and relevance validation.", [
    {
      id: "meilisearch",
      name: "Meilisearch",
      reason: "Self-hosted search that proves local and hosted index workflows.",
      runtime: "server",
      surface: "server search adapter",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "MEILISEARCH_HOST", scope: "server", required: true, capability: "search:query" },
        { name: "MEILISEARCH_API_KEY", scope: "server", required: true, capability: "search:manage" },
      ],
      receipts: ["index-create", "query-smoke", "relevance-snapshot"],
    },
    {
      id: "typesense",
      name: "Typesense",
      reason: "Fast open-source search with strict collection schema.",
      runtime: "server",
      surface: "server search adapter",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "TYPESENSE_HOST", scope: "server", required: true, capability: "search:query" },
        { name: "TYPESENSE_API_KEY", scope: "server", required: true, capability: "search:manage" },
      ],
      receipts: ["collection-schema", "query-smoke", "relevance-snapshot"],
    },
    {
      id: "algolia",
      name: "Algolia",
      reason: "Hosted commercial search many teams already use.",
      runtime: "server-and-browser",
      surface: "server indexing and browser search keys",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "ALGOLIA_APP_ID", scope: "server", required: true, capability: "search:app" },
        { name: "ALGOLIA_ADMIN_API_KEY", scope: "server", required: true, capability: "search:manage" },
        { name: "NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY", scope: "browser-public", required: false, capability: "search:browser" },
      ],
      receipts: ["index-write", "secured-api-key", "query-smoke"],
    },
  ]),
  category("vector-search", "Vector search and AI data", "Embedding stores that prove index creation, query similarity, and tenant safety.", [
    {
      id: "pgvector",
      name: "pgvector",
      reason: "Postgres-native vector path for teams that want one database.",
      runtime: "server",
      surface: "database migrations and vector query helpers",
      adapter: "database-extension",
      validation: "live-if-env-present",
      env: [{ name: "DATABASE_URL", scope: "server", required: true, capability: "database:vector" }],
      receipts: ["extension-check", "embedding-write", "similarity-query"],
    },
    {
      id: "pinecone",
      name: "Pinecone",
      reason: "Dedicated hosted vector infrastructure.",
      runtime: "server",
      surface: "server vector adapter",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "PINECONE_API_KEY", scope: "server", required: true, capability: "vector:query" },
        { name: "PINECONE_INDEX", scope: "server", required: true, capability: "vector:index" },
      ],
      receipts: ["index-describe", "embedding-write", "similarity-query"],
    },
    {
      id: "mongodb-atlas-vector-search",
      name: "MongoDB Atlas Vector Search",
      reason: "Document and vector hybrid search in a mainstream database.",
      runtime: "server",
      surface: "server vector adapter",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "MONGODB_URI", scope: "server", required: true, capability: "database:connect" },
        { name: "MONGODB_VECTOR_INDEX", scope: "server", required: true, capability: "vector:index" },
      ],
      receipts: ["index-describe", "embedding-write", "hybrid-query"],
    },
  ]),
];
