import { category } from "../lane-utils";
import type { WorldCategory } from "../contracts";

export const contentDeployCategories: readonly WorldCategory[] = [
  category("content", "CMS, content, docs, and marketing sites", "Content systems that prove source ownership, preview, and publishing flows.", [
    {
      id: "content-collections-mdx",
      name: "Content collections/MDX",
      reason: "Source-owned content path for docs and marketing pages.",
      runtime: "server",
      surface: "content files and route generation",
      adapter: "source-owned",
      validation: "preview-only",
      env: [],
      receipts: ["content-index", "frontmatter-schema", "route-generation"],
      frameworkSuggestion: "Add first-class content collection checks that also work in plain HTML projects.",
    },
    {
      id: "sanity",
      name: "Sanity",
      reason: "Hosted structured content platform with preview expectations.",
      runtime: "server-and-browser",
      surface: "server fetch, preview route, browser preview token boundary",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "SANITY_PROJECT_ID", scope: "server", required: true, capability: "cms:project" },
        { name: "SANITY_DATASET", scope: "server", required: true, capability: "cms:dataset" },
        { name: "SANITY_API_TOKEN", scope: "server", required: false, capability: "cms:preview" },
      ],
      receipts: ["fetch", "preview-mode", "schema"],
    },
    {
      id: "strapi",
      name: "Strapi",
      reason: "Self-hosted CMS path for teams that want more ownership.",
      runtime: "server",
      surface: "server fetch and webhook route",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "STRAPI_URL", scope: "server", required: true, capability: "cms:fetch" },
        { name: "STRAPI_API_TOKEN", scope: "server", required: true, capability: "cms:auth" },
      ],
      receipts: ["fetch", "webhook-signature", "schema"],
    },
    {
      id: "contentful",
      name: "Contentful",
      reason: "Hosted content platform with stable delivery and preview API boundaries.",
      runtime: "server",
      surface: "server fetch, content-type schema, preview token boundary",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "CONTENTFUL_SPACE_ID", scope: "server", required: true, capability: "cms:space" },
        { name: "CONTENTFUL_ENVIRONMENT", scope: "server", required: true, capability: "cms:environment" },
        { name: "CONTENTFUL_DELIVERY_TOKEN", scope: "server", required: true, capability: "cms:delivery" },
        { name: "CONTENTFUL_PREVIEW_TOKEN", scope: "server", required: false, capability: "cms:preview" },
      ],
      receipts: ["content-types", "preview-mode", "webhook-signature"],
    },
  ]),
  category("notifications", "Email, SMS, push, and notifications", "Messaging providers with sender, webhook, and delivery validation.", [
    {
      id: "resend",
      name: "Resend",
      reason: "Modern transactional email platform with developer-friendly APIs.",
      runtime: "server",
      surface: "server action and route handler email sends",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "RESEND_API_KEY", scope: "server", required: true, capability: "email:send" },
        { name: "RESEND_FROM_EMAIL", scope: "server", required: true, capability: "email:sender" },
      ],
      receipts: ["sender-domain", "send-smoke", "delivery-event"],
    },
    {
      id: "twilio",
      name: "Twilio",
      reason: "SMS and phone messaging baseline.",
      runtime: "server",
      surface: "route handlers and webhook validators",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "TWILIO_ACCOUNT_SID", scope: "server", required: true, capability: "sms:account" },
        { name: "TWILIO_AUTH_TOKEN", scope: "server", required: true, capability: "sms:send" },
        { name: "TWILIO_MESSAGING_SERVICE_SID", scope: "server", required: false, capability: "sms:sender" },
        { name: "TWILIO_FROM_NUMBER", scope: "server", required: false, capability: "sms:sender" },
      ],
      receipts: ["send-smoke", "webhook-signature", "delivery-event"],
    },
    {
      id: "firebase-cloud-messaging",
      name: "Firebase Cloud Messaging",
      reason: "Push notification path for web and mobile-adjacent products.",
      runtime: "server-and-browser",
      surface: "server send route and browser service worker contract",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "FCM_PROJECT_ID", scope: "server", required: true, capability: "push:project" },
        { name: "FCM_SERVICE_ACCOUNT_JSON", scope: "server", required: true, capability: "push:send" },
        { name: "NEXT_PUBLIC_FCM_SENDER_ID", scope: "browser-public", required: false, capability: "push:browser" },
      ],
      receipts: ["send-smoke", "browser-registration", "permission-state"],
    },
  ]),
  category("deployment", "Deployment, hosting, edge, and cloud", "Deployment targets that prove preview, production, headers, and adapter behavior.", [
    {
      id: "vercel",
      name: "Vercel",
      reason: "Frontend deployment platform with CLI already available in this workspace.",
      runtime: "ci",
      surface: "deploy adapter and CLI receipts",
      adapter: "provider-cli",
      validation: "live-if-env-present",
      env: [
        { name: "VERCEL_TOKEN", scope: "ci", required: false, capability: "deploy:vercel" },
        { name: "VERCEL_PROJECT_ID", scope: "ci", required: false, capability: "deploy:project" },
        { name: "VERCEL_TEAM_ID", scope: "ci", required: false, capability: "deploy:team" },
      ],
      receipts: ["whoami", "preview-deploy", "headers"],
    },
    {
      id: "cloudflare",
      name: "Cloudflare",
      reason: "Edge runtime, Workers, Pages, KV, Queues, and R2 ecosystem.",
      runtime: "edge",
      surface: "deploy adapter and wrangler receipts",
      adapter: "provider-cli",
      validation: "live-if-env-present",
      env: [
        { name: "CLOUDFLARE_API_TOKEN", scope: "ci", required: true, capability: "deploy:cloudflare" },
        { name: "CLOUDFLARE_ACCOUNT_ID", scope: "ci", required: true, capability: "deploy:account" },
        { name: "CLOUDFLARE_PROJECT_NAME", scope: "ci", required: false, capability: "deploy:project" },
      ],
      receipts: ["whoami", "preview-deploy", "bindings"],
    },
    {
      id: "fly-io",
      name: "Fly.io",
      reason: "Portable server deployment path for Rust-backed WWW apps.",
      runtime: "server",
      surface: "server deploy adapter and machine status",
      adapter: "provider-cli",
      validation: "live-if-env-present",
      env: [
        { name: "FLY_API_TOKEN", scope: "ci", required: true, capability: "deploy:fly" },
        { name: "FLY_APP_NAME", scope: "ci", required: true, capability: "deploy:app" },
      ],
      receipts: ["whoami", "machine-status", "release"],
    },
    {
      id: "netlify",
      name: "Netlify",
      reason: "Portable hosted frontend deployment path with mature preview and forms ecosystem.",
      runtime: "ci",
      surface: "deploy adapter and hosted preview receipts",
      adapter: "provider-cli-or-api",
      validation: "live-if-env-present",
      env: [
        { name: "NETLIFY_AUTH_TOKEN", scope: "ci", required: true, capability: "deploy:netlify" },
        { name: "NETLIFY_SITE_ID", scope: "ci", required: false, capability: "deploy:site" },
      ],
      receipts: ["whoami", "preview-deploy", "headers"],
    },
  ]),
];
