import { category } from "../lane-utils";
import type { WorldCategory } from "../contracts";

export const dataIdentityCategories: readonly WorldCategory[] = [
  category("database", "Database and data platform", "SQL and data platforms that prove connection, schema, migration, and runtime boundaries.", [
    {
      id: "postgresql",
      name: "PostgreSQL",
      reason: "Baseline relational database contract for most production apps.",
      runtime: "server",
      surface: "route handlers, server actions, migrations",
      adapter: "database-url",
      validation: "live-if-env-present",
      env: [{ name: "DATABASE_URL", scope: "server", required: true, capability: "database:connect" }],
      receipts: ["connection", "schema-drift", "query-smoke"],
    },
    {
      id: "neon",
      name: "Neon",
      reason: "Serverless Postgres with branch-aware connection validation.",
      runtime: "server-or-edge",
      surface: "serverless database adapter",
      adapter: "provider-database-url",
      validation: "live-if-env-present",
      env: [
        { name: "NEON_DATABASE_URL", scope: "server", required: true, capability: "database:connect" },
        { name: "NEON_API_KEY", scope: "server", required: false, capability: "database:branch" },
      ],
      receipts: ["connection", "branch", "latency"],
    },
    {
      id: "turso-libsql",
      name: "Turso/libSQL",
      reason: "Local-first and serverless SQLite path already important to the DX ecosystem.",
      runtime: "server-or-edge",
      surface: "libSQL route handler adapter",
      adapter: "turso-cli-or-env",
      validation: "live-if-env-present",
      env: [
        { name: "TURSO_DATABASE_URL", scope: "server", required: true, capability: "database:connect" },
        { name: "TURSO_AUTH_TOKEN", scope: "server", required: true, capability: "database:auth" },
      ],
      receipts: ["connection", "query-smoke", "replica-policy"],
    },
  ]),
  category("orm", "ORM, query builder, and schema tooling", "Schema ownership and typed query workflows for native and external ecosystems.", [
    {
      id: "dx-orm-forge-database",
      name: "DX ORM / Forge database",
      reason: "Native DX data path with source-owned receipts and generated contracts.",
      runtime: "server",
      surface: "Forge package and route handlers",
      adapter: "forge-package",
      validation: "live-if-env-present",
      env: [{ name: "DATABASE_URL", scope: "server", required: true, capability: "database:connect" }],
      receipts: ["migration", "schema-contract", "query-smoke"],
      frameworkSuggestion: "Promote the native database package as the canonical WWW data adapter contract.",
    },
    {
      id: "drizzle",
      name: "Drizzle",
      reason: "Typed SQL ecosystem developers will compare first.",
      runtime: "server",
      surface: "server modules and migrations",
      adapter: "forge-verified-package",
      validation: "live-if-env-present",
      env: [{ name: "DATABASE_URL", scope: "server", required: true, capability: "database:connect" }],
      receipts: ["migration", "schema-drift", "prepared-query"],
    },
    {
      id: "prisma",
      name: "Prisma",
      reason: "Popular ORM with generated client expectations and migration workflows.",
      runtime: "server",
      surface: "server modules and generated client boundary",
      adapter: "forge-verified-package",
      validation: "live-if-env-present",
      env: [{ name: "DATABASE_URL", scope: "server", required: true, capability: "database:connect" }],
      receipts: ["client-generation", "migration", "schema-drift"],
    },
  ]),
  category("authentication", "Authentication and identity", "Identity systems that must prove sessions, callbacks, cookies, and secret boundaries.", [
    {
      id: "dx-auth-forge-auth",
      name: "DX Auth / Forge auth",
      reason: "Native source-owned auth lane with DX receipts.",
      runtime: "server-and-browser",
      surface: "route handlers, cookies, session helpers",
      adapter: "forge-package",
      validation: "live-if-env-present",
      env: [
        { name: "DX_AUTH_SECRET", scope: "server", required: true, capability: "auth:sign" },
        { name: "DX_AUTH_URL", scope: "server", required: true, capability: "auth:callback" },
      ],
      receipts: ["session", "csrf", "cookie-policy"],
      frameworkSuggestion: "Make native auth the default example while keeping external providers adapter-based.",
    },
    {
      id: "better-auth",
      name: "Better Auth",
      reason: "Source-friendly auth ecosystem that fits the Forge direction.",
      runtime: "server-and-browser",
      surface: "route handlers and session helpers",
      adapter: "forge-verified-package",
      validation: "live-if-env-present",
      env: [
        { name: "BETTER_AUTH_SECRET", scope: "server", required: true, capability: "auth:sign" },
        { name: "BETTER_AUTH_URL", scope: "server", required: true, capability: "auth:callback" },
      ],
      receipts: ["session", "csrf", "provider-callback"],
    },
    {
      id: "clerk",
      name: "Clerk",
      reason: "Hosted identity platform many teams expect to evaluate.",
      runtime: "server-and-browser",
      surface: "middleware, route handlers, browser widgets",
      adapter: "provider-sdk-or-cdn",
      validation: "live-if-env-present",
      env: [
        { name: "CLERK_SECRET_KEY", scope: "server", required: true, capability: "auth:verify" },
        { name: "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY", scope: "browser-public", required: true, capability: "auth:browser" },
      ],
      receipts: ["session", "callback-url", "secret-boundary"],
    },
  ]),
  category("authorization", "Authorization and policy", "Policy checks that prove user-to-resource access without leaking secrets.", [
    {
      id: "postgresql-rls",
      name: "PostgreSQL RLS",
      reason: "Database-native policy is the baseline for secure data apps.",
      runtime: "server",
      surface: "database schema and policy receipts",
      adapter: "database-policy",
      validation: "live-if-env-present",
      env: [{ name: "DATABASE_URL", scope: "server", required: true, capability: "database:policy" }],
      receipts: ["rls-policy", "negative-access-test", "migration"],
    },
    {
      id: "openfga",
      name: "OpenFGA",
      reason: "Relationship authorization for collaborative and multi-tenant products.",
      runtime: "server",
      surface: "server policy checks",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "OPENFGA_API_URL", scope: "server", required: true, capability: "authorization:check" },
        { name: "OPENFGA_STORE_ID", scope: "server", required: true, capability: "authorization:store" },
        { name: "OPENFGA_API_TOKEN", scope: "server", required: false, capability: "authorization:auth" },
      ],
      receipts: ["model", "tuple-check", "negative-access-test"],
    },
    {
      id: "casbin",
      name: "Casbin",
      reason: "Embedded policy engine for apps that want local policy evaluation.",
      runtime: "server",
      surface: "server policy modules",
      adapter: "forge-verified-package",
      validation: "preview-only",
      env: [],
      receipts: ["policy-model", "allow-deny-tests", "source-map"],
    },
  ]),
];
