import { category } from "../lane-utils";
import type { WorldCategory } from "../contracts";

export const operationsCategories: readonly WorldCategory[] = [
  category("cache-config", "Cache, config, feature flags, and rate limits", "Low-latency state and configuration systems with scoped access and drift checks.", [
    {
      id: "redis-valkey",
      name: "Redis/Valkey",
      reason: "Baseline cache, pub/sub, rate limit, and session storage path.",
      runtime: "server",
      surface: "server cache adapter",
      adapter: "provider-or-self-hosted",
      validation: "live-if-env-present",
      env: [
        { name: "REDIS_URL", scope: "server", required: true, capability: "cache:connect" },
        { name: "REDIS_READINESS_URL", scope: "server", required: false, capability: "cache:readiness" },
      ],
      receipts: ["ping", "read-only-readiness", "ttl-policy"],
    },
    {
      id: "upstash-redis",
      name: "Upstash Redis",
      reason: "Serverless Redis path for edge and low-maintenance apps.",
      runtime: "server-or-edge",
      surface: "server cache adapter",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "UPSTASH_REDIS_REST_URL", scope: "server", required: true, capability: "cache:connect" },
        { name: "UPSTASH_REDIS_REST_TOKEN", scope: "server", required: true, capability: "cache:auth" },
      ],
      receipts: ["ping", "rest-readiness", "rate-limit-policy"],
    },
    {
      id: "cloudflare-kv",
      name: "Cloudflare KV",
      reason: "Edge key-value config and cache storage.",
      runtime: "edge",
      surface: "provider binding and deployment manifest",
      adapter: "provider-platform",
      validation: "live-if-env-present",
      env: [
        { name: "CLOUDFLARE_ACCOUNT_ID", scope: "server", required: true, capability: "kv:account" },
        { name: "CLOUDFLARE_API_TOKEN", scope: "ci", required: true, capability: "kv:metadata-read" },
        { name: "CLOUDFLARE_KV_NAMESPACE_ID", scope: "server", required: true, capability: "kv:namespace" },
      ],
      receipts: ["binding", "namespace-key-list", "config-drift"],
    },
  ]),
  category("analytics", "Analytics, product data, and experimentation", "Analytics systems that preserve privacy and separate public browser keys from secrets.", [
    {
      id: "posthog",
      name: "PostHog",
      reason: "Product analytics and experimentation platform with self-hosted options.",
      runtime: "server-and-browser",
      surface: "browser script and server capture route",
      adapter: "provider-api-or-cdn",
      validation: "live-if-env-present",
      env: [
        { name: "NEXT_PUBLIC_POSTHOG_KEY", scope: "browser-public", required: true, capability: "analytics:browser" },
        { name: "POSTHOG_HOST", scope: "server", required: false, capability: "analytics:host" },
        { name: "POSTHOG_PERSONAL_API_KEY", scope: "server", required: true, capability: "analytics:metadata-read" },
        { name: "POSTHOG_PROJECT_ID", scope: "server", required: true, capability: "analytics:project" },
      ],
      receipts: ["project-metadata-read", "privacy-mode", "script-boundary"],
    },
    {
      id: "plausible",
      name: "Plausible",
      reason: "Privacy-friendly web analytics with a small browser footprint.",
      runtime: "browser",
      surface: "script primitive and route metadata",
      adapter: "cdn-script",
      validation: "live-if-env-present",
      env: [
        { name: "NEXT_PUBLIC_PLAUSIBLE_DOMAIN", scope: "browser-public", required: true, capability: "analytics:browser" },
        { name: "PLAUSIBLE_API_KEY", scope: "server", required: true, capability: "analytics:stats-read" },
        { name: "PLAUSIBLE_API_HOST", scope: "server", required: false, capability: "analytics:host" },
      ],
      receipts: ["stats-aggregate-read", "domain-config", "no-secret-boundary"],
    },
    {
      id: "vercel-analytics",
      name: "Vercel Analytics",
      reason: "Deployment-native web vitals and analytics path.",
      runtime: "browser",
      surface: "script primitive and deploy adapter",
      adapter: "provider-platform",
      validation: "live-if-env-present",
      env: [
        { name: "VERCEL_PROJECT_ID", scope: "server", required: true, capability: "analytics:project" },
        { name: "VERCEL_TOKEN", scope: "server", required: true, capability: "analytics:project-read" },
      ],
      receipts: ["project-readiness-read", "deploy-link", "web-vitals"],
    },
  ]),
  category("observability", "Observability, logs, errors, and traces", "Diagnostics providers that keep traces useful while redacting secrets.", [
    {
      id: "opentelemetry",
      name: "OpenTelemetry",
      reason: "Open standard for traces, metrics, and logs.",
      runtime: "server-and-browser",
      surface: "server spans and browser web vitals",
      adapter: "standard-protocol",
      validation: "live-if-env-present",
      env: [
        { name: "OTEL_EXPORTER_OTLP_ENDPOINT", scope: "server", required: true, capability: "observability:export" },
        { name: "OTEL_EXPORTER_OTLP_HEADERS", scope: "server", required: false, capability: "observability:auth" },
        { name: "OTEL_HEALTHCHECK_URL", scope: "server", required: false, capability: "observability:health-read" },
      ],
      receipts: ["collector-healthcheck", "redaction", "sampling"],
      frameworkSuggestion: "Add source-owned OpenTelemetry receipts to dx check and devtools diagnostics.",
    },
    {
      id: "sentry",
      name: "Sentry",
      reason: "Error monitoring platform with source map expectations.",
      runtime: "server-and-browser",
      surface: "server errors, browser errors, source maps",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "SENTRY_DSN", scope: "server", required: true, capability: "observability:error" },
        { name: "SENTRY_AUTH_TOKEN", scope: "ci", required: true, capability: "observability:project-read" },
        { name: "SENTRY_ORG", scope: "server", required: true, capability: "observability:organization" },
        { name: "SENTRY_PROJECT", scope: "server", required: true, capability: "observability:project" },
      ],
      receipts: ["project-metadata-read", "source-map-boundary", "redaction"],
    },
    {
      id: "datadog",
      name: "Datadog",
      reason: "Enterprise observability path for logs, traces, and metrics.",
      runtime: "server-and-browser",
      surface: "server exporter and browser RUM",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "DD_API_KEY", scope: "server", required: true, capability: "observability:export" },
        { name: "DD_SITE", scope: "server", required: false, capability: "observability:region" },
        { name: "DATADOG_SITE", scope: "server", required: false, capability: "observability:region" },
      ],
      receipts: ["api-key-validate", "log-export-boundary", "redaction"],
    },
  ]),
];
