import { category } from "../lane-utils";
import type { WorldCategory } from "../contracts";

export const trustProductivityCategories: readonly WorldCategory[] = [
  category("security", "Security, secrets, compliance, and supply chain", "Security systems that keep secrets sealed and provenance auditable.", [
    {
      id: "dx-env-firewall",
      name: "DX Env Firewall",
      reason: "Native typed, scoped, encrypted env safety for WWW and Forge.",
      runtime: "development",
      surface: "dx env commands and generated contracts",
      adapter: "source-owned",
      validation: "live-validated",
      env: [{ name: "DX_ENV_PASSWORD", scope: "agent-safe-name-only", required: false, capability: "env:unlock" }],
      receipts: ["env-lock", "env-check", "agent-context"],
      frameworkSuggestion: "Use Env Firewall as the provider contract entrypoint for all integrations.",
    },
    {
      id: "github-advanced-security",
      name: "GitHub Advanced Security",
      reason: "Code scanning and secret scanning path for teams already using GitHub.",
      runtime: "ci",
      surface: "repository security receipts",
      adapter: "provider-platform",
      validation: "live-if-env-present",
      env: [{ name: "GITHUB_TOKEN", scope: "ci", required: false, capability: "security:read" }],
      receipts: ["secret-scan", "code-scan", "dependency-review"],
    },
    {
      id: "sigstore",
      name: "Sigstore",
      reason: "Signed provenance and transparent supply-chain attestations.",
      runtime: "ci",
      surface: "release receipts and package provenance",
      adapter: "standard-protocol",
      validation: "preview-only",
      env: [],
      receipts: ["artifact-signature", "provenance", "transparency-log"],
    },
  ]),
  category("developer-platforms", "Developer platforms and team tools", "Team tools for code hosting, planning, and workspace documentation.", [
    {
      id: "github",
      name: "GitHub",
      reason: "Code hosting, issues, pull requests, CI, and release provenance.",
      runtime: "ci",
      surface: "CLI and provider API receipts",
      adapter: "provider-cli-or-api",
      validation: "live-if-env-present",
      env: [{ name: "GITHUB_TOKEN", scope: "ci", required: false, capability: "developer-platform:github" }],
      receipts: ["auth-status", "repo-status", "workflow-status"],
    },
    {
      id: "linear",
      name: "Linear",
      reason: "Issue and project operations for product teams.",
      runtime: "server",
      surface: "server API adapter",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [{ name: "LINEAR_API_KEY", scope: "server", required: true, capability: "team:linear" }],
      receipts: ["issue-read", "project-read", "redaction"],
    },
    {
      id: "notion",
      name: "Notion",
      reason: "Workspace documentation and customer knowledge capture.",
      runtime: "server",
      surface: "server API adapter",
      adapter: "provider-api",
      validation: "live-if-env-present",
      env: [
        { name: "NOTION_TOKEN", scope: "server", required: true, capability: "team:notion" },
        { name: "NOTION_DATABASE_ID", scope: "server", required: false, capability: "team:notion-database" },
      ],
      receipts: ["page-read", "database-read", "redaction"],
    },
  ]),
  category("product-surface", "Internationalization, localization, maps, and forms", "Product surface tooling for language, place, and typed user input.", [
    {
      id: "formatjs-intl",
      name: "FormatJS/Intl",
      reason: "Browser-native i18n plus catalog workflows.",
      runtime: "server-and-browser",
      surface: "route metadata, formatting helpers, content catalogs",
      adapter: "web-standard-and-forge-package",
      validation: "preview-only",
      env: [],
      receipts: ["locale-routing", "message-catalog", "fallback"],
      frameworkSuggestion: "Add first-class i18n route receipts and locale-aware static output.",
    },
    {
      id: "google-maps",
      name: "Google Maps",
      reason: "Common maps, geocoding, and place autocomplete expectations.",
      runtime: "server-and-browser",
      surface: "script primitive and server geocoding route",
      adapter: "provider-api-or-cdn",
      validation: "live-if-env-present",
      env: [
        { name: "GOOGLE_MAPS_API_KEY", scope: "server", required: true, capability: "maps:server" },
        { name: "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY", scope: "browser-public", required: false, capability: "maps:browser" },
      ],
      receipts: ["script-emit", "geocode-smoke", "key-boundary"],
    },
    {
      id: "react-hook-form-shape",
      name: "React Hook Form shape",
      reason: "Form validation expectations developers bring from React projects.",
      runtime: "server-and-browser",
      surface: "native WWW forms and validation contracts",
      adapter: "compatibility-shape",
      validation: "preview-only",
      env: [],
      receipts: ["no-js-submit", "client-validation", "server-validation"],
      frameworkSuggestion: "Keep the shape familiar while lowering to WWW-native form state, not a React runtime.",
    },
  ]),
];
