const dxLaunchSceneFiles = [
  "components/scene/launch-scene.tsx",
  "lib/scene/index.ts",
  "lib/scene/types.ts",
  "lib/scene/preset.ts",
  "lib/scene/interaction.ts",
  "lib/scene/dashboard-workflow.ts",
  "lib/scene/dashboard-controls.ts",
  "lib/scene/frame-sample.ts",
  "lib/scene/capability-report.ts",
  "lib/scene/viewport-report.ts",
  "lib/scene/bounds-report.ts",
  "lib/scene/raycast-report.ts",
  "lib/scene/preview-readiness.ts",
  "lib/scene/performance-monitor.ts",
  "lib/scene/renderer-handoff.ts",
  "lib/scene/r3f-renderer-adapter.ts",
  "lib/scene/webgl-runtime.ts",
  "lib/scene/metadata.ts",
  "lib/scene/README.md",
] as const;

export const dxLaunchSceneForgePackage = {
  packageId: "3d/launch-scene",
  officialPackageName: "3D Scene System",
  forgeVersion: "0.184.0-r3f10-dx.0",
  status: "source-owned-lock-backed-web-preview-runtime",
  upstreamPackage: "three + @react-three/fiber + @react-three/drei",
  upstreamVersion:
    "three 0.184.0; @react-three/fiber 9.6.1; @react-three/drei local mirror",
  honestyLabel: "LOCK-BACKED SOURCE-OWNED",
  docsPath: "docs/packages/3d-scene-system.md",
  aliases: [
    "3d-scene-system",
    "three-scene",
    "three/r3f/drei",
    "threejs/scene",
    "@react-three/fiber",
    "@react-three/drei",
    "three",
  ],
  icon: '<dx-icon name="pack:three-scene" />',
  upstreamPackages: [
    { name: "three", version: "0.184.0", license: "MIT" },
    { name: "@react-three/fiber", version: "9.6.1", license: "MIT" },
    { name: "@react-three/drei", version: "local mirror", license: "MIT" },
  ],
  sourceMirrors: [
    {
      package: "three",
      path: "G:/WWW/inspirations/three.js",
      inspectedApis: [
        "THREE.WebGLRenderer",
        "THREE.WebGLRenderer.getContextAttributes",
        "THREE.WebGLRenderer.readRenderTargetPixels",
        "THREE.WebGLRenderer.setPixelRatio",
        "THREE.WebGLRenderer.capabilities",
        "THREE.WebGLRenderer.extensions",
        "THREE.Box3",
        "THREE.Box3.setFromObject",
        "THREE.Raycaster",
        "THREE.Raycaster.intersectObject",
        "THREE.Raycaster.intersectObjects",
        "THREE.Scene",
        "THREE.PerspectiveCamera",
        "THREE.ShaderMaterial",
      ],
    },
    {
      package: "@react-three/fiber",
      path: "G:/WWW/inspirations/react-three-fiber",
      inspectedApis: [
        "@react-three/fiber Canvas",
        "@react-three/fiber createRoot(canvas)",
        "@react-three/fiber frameloop",
        "@react-three/fiber RootState",
        "@react-three/fiber state.raycaster",
        "@react-three/fiber raycaster.setFromCamera",
        "@react-three/fiber calculateDpr",
        "@react-three/fiber setDpr",
      ],
    },
    {
      package: "@react-three/drei",
      path: "G:/WWW/inspirations/drei",
      inspectedApis: [
        "@react-three/drei KeyboardControls",
        "@react-three/drei PerformanceMonitor",
        "@react-three/drei AdaptiveDpr",
        "@react-three/drei viewport.dpr",
        "@react-three/drei OrbitControls",
        "@react-three/drei Bounds",
        "@react-three/drei Bounds.fit",
        "@react-three/drei meshBounds",
      ],
    },
  ],
  inspectedSourceFiles: [
    "three.js/package.json",
    "three.js/src/renderers/WebGLRenderer.js",
    "three.js/src/core/Raycaster.js",
    "three.js/src/math/Box3.js",
    "react-three-fiber/packages/fiber/src/core/renderer.tsx",
    "react-three-fiber/packages/fiber/src/core/store.ts",
    "react-three-fiber/packages/fiber/src/core/events.ts",
    "react-three-fiber/packages/fiber/src/web/Canvas.tsx",
    "drei/src/web/KeyboardControls.tsx",
    "drei/src/core/Bounds.tsx",
    "drei/src/core/PerformanceMonitor.tsx",
    "drei/src/core/AdaptiveDpr.tsx",
    "drei/src/core/meshBounds.tsx",
  ],
  selectedSurfaces: [
    "launch-scene-webgl-proof",
    "launch-scene-dashboard-workflow",
    "renderer-handoff",
    "r3f-renderer-adapter",
    "web-preview-runtime",
  ],
  dxCheckVisibility: {
    schema: "dx.forge.package.dx_check_visibility",
    currentStatus: "present",
    statuses: [
      "present",
      "stale",
      "missing receipt",
      "blocked",
      "unsupported surface",
    ],
    receiptPath:
      "examples/template/.dx/forge/receipts/3d-launch-scene-dashboard-workflow.json",
    monitoredSurfaces: [
      "launch-scene-webgl-proof",
      "launch-scene-dashboard-workflow",
      "renderer-handoff",
      "r3f-renderer-adapter",
    ],
  },
  dxStyleCompatibility: {
    schema: "dx.forge.package.dx_style_compatibility",
    status: "present",
    tokenSource: "examples/template/launch-scene.tsx",
    generatedCss: "examples/template/styles/globals.css",
    visibleSurfaces: [
      "launch-scene-webgl-proof",
      "launch-scene-dashboard-workflow",
    ],
    sourceFiles: [
      "examples/template/launch-scene.tsx",
      "examples/template/styles/globals.css",
    ],
    dataDxMarkers: [
      'data-dx-style-surface="launch-scene"',
      'data-dx-token-scope="3d/launch-scene"',
      'data-dx-edit-id="launch.scene"',
    ],
    runtimeProof: false,
    runtimeLimitations: [
      "LOCK-BACKED SOURCE-OWNED: dx-style compatibility is visible source-marker and generated CSS evidence; no browser/WebGL visual proof is claimed.",
      "ADAPTER-BOUNDARY: final scene theme token review, shader styling, accessibility, and screenshot QA stay app-owned.",
    ],
  },
  provenance: {
    source: "dx-forge-curated-local-mirror",
    licenseBoundary:
      "MIT upstream packages inspected through local mirrors; DX WWW owns this adapter code and does not copy upstream implementation or bundled assets.",
    inspectedApiShape: [
      "THREE.WebGLRenderer",
      "THREE.WebGLRenderer.getContextAttributes",
      "THREE.WebGLRenderer.readRenderTargetPixels",
      "THREE.WebGLRenderer.setPixelRatio",
      "THREE.WebGLRenderer.capabilities/extensions",
      "THREE.Box3",
      "THREE.Box3.setFromObject",
      "THREE.Raycaster",
      "THREE.Raycaster.intersectObject",
      "THREE.Raycaster.intersectObjects",
      "THREE.Scene",
      "THREE.PerspectiveCamera",
      "THREE.ShaderMaterial",
      "@react-three/fiber Canvas/createRoot(canvas)",
      "@react-three/fiber frameloop RootState",
      "@react-three/fiber state.raycaster",
      "@react-three/fiber raycaster.setFromCamera",
      "@react-three/fiber calculateDpr",
      "@react-three/fiber setDpr/viewport.dpr",
      "@react-three/drei KeyboardControls",
      "@react-three/drei PerformanceMonitor",
      "@react-three/drei AdaptiveDpr",
      "@react-three/drei viewport.dpr",
      "@react-three/drei Bounds",
      "@react-three/drei Bounds.fit",
      "@react-three/drei meshBounds",
    ],
  },
  exportedFiles: dxLaunchSceneFiles,
  materializedFiles: dxLaunchSceneFiles,
  requiredEnv: [],
  optionalEnv: [],
  receiptPaths: {
    package: ".dx/forge/receipts/3d-launch-scene.json",
    dashboard: ".dx/forge/docs/launch-scene.md",
    dashboardWorkflow:
      ".dx/forge/receipts/3d-launch-scene-dashboard-workflow.json",
    templateReadiness:
      ".dx/forge/template-readiness/launch-scene-readiness.json",
  },
  webPreview: {
    renderer: "source-owned-webgl",
    requiresPackageInstall: false,
    requiresServer: false,
  },
  realRuntimeApis: [
    "frame-callback-bridge",
    "node-geometry-uniforms",
    "camera-uniforms",
    "material-palettes",
    "material-palette-dashboard-action",
    "quality-profiles",
    "quality-profile-dashboard-action",
    "source-owned-camera-rigs",
    "camera-rig-dashboard-action",
    "dashboard-control-helpers",
    "frame-sample-readback",
    "renderer-capability-report",
    "viewport-dpr-report",
    "bounds-fit-report",
    "raycast-hit-report",
    "performance-monitor",
    "performance-regression-controls",
    "node-interaction-bridge",
    "keyboard-node-navigation",
    "dashboard-workflow",
    "renderer-handoff",
    "r3f-renderer-adapter",
  ],
  publicApis: [
    "createDxLaunchScenePreset",
    "dxSceneQualityProfiles",
    "dxSceneDashboardCameraRigs",
    "resolveDxSceneDashboardCameraRig",
    "createDxSceneDashboardWorkflow",
    "createDxSceneDashboardReceipt",
    "cycleDxSceneQualityProfile",
    "cycleDxSceneMaterialPalette",
    "cycleDxSceneCameraRig",
    "formatDxSceneDashboardReceiptSummary",
    "captureDxSceneFrameSample",
    "createDxSceneCapabilityReport",
    "createDxSceneViewportReport",
    "createDxSceneBoundsReport",
    "createDxSceneRaycastReport",
    "createDxScenePreviewReadiness",
    "mountDxSceneWithRenderer",
  ],
  appOwnedBoundaries: [
    "The template ships a WebGL-safe local adapter first.",
    "Injected Three/R3F/Drei runtimes can replace the renderer without changing the component boundary.",
    "Projection matrices, controls, assets, shader review, and WebXR permissions stay app-owned.",
  ],
} as const;
