/* Generated by dx imports sync. */
/* Keep source files editable; regenerate after moves or export changes. */
export * from "../../components/charts/chart-frame";
export * from "../../components/charts/chart-gallery";
export * from "../../components/charts/chart-home";
export * from "../../components/charts/chart-site-shell";
export * from "../../components/charts/docs-overview";
export * from "../../components/charts/ecosystem-overview";
export * from "../../components/charts/examples-overview";
export * from "../../components/charts/playground-preview";
export * from "../../components/charts/route-boundary";
export * from "../../components/charts/theme-overview";
export * from "../../components/island-runtime-probe";
export * from "../../components/state-runtime-probe";
export * from "../../components/icons/icon";

export const dxAutoImportMap = {
  "components": [
    {
      "kind": "component",
      "name": "ChartFrame",
      "source": "components/charts/chart-frame.tsx",
      "import_path": "@/components/charts/chart-frame",
      "barrel_export": "../../components/charts/chart-frame",
      "exports": [
        "ChartFrame",
        "ChartFrameProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "ChartFrame"
      ],
      "unused_exports": [
        "ChartFrameProps"
      ],
      "type_exports": [
        "ChartFrameProps"
      ]
    },
    {
      "kind": "component",
      "name": "ChartGallery",
      "source": "components/charts/chart-gallery.tsx",
      "import_path": "@/components/charts/chart-gallery",
      "barrel_export": "../../components/charts/chart-gallery",
      "exports": [
        "ChartGallery"
      ],
      "default_export_name": null,
      "used_exports": [
        "ChartGallery"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "ChartHome",
      "source": "components/charts/chart-home.tsx",
      "import_path": "@/components/charts/chart-home",
      "barrel_export": "../../components/charts/chart-home",
      "exports": [
        "ChartHome"
      ],
      "default_export_name": null,
      "used_exports": [
        "ChartHome"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "ChartSiteShell",
      "source": "components/charts/chart-site-shell.tsx",
      "import_path": "@/components/charts/chart-site-shell",
      "barrel_export": "../../components/charts/chart-site-shell",
      "exports": [
        "ChartSiteShell",
        "ChartSiteShellProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "ChartSiteShell"
      ],
      "unused_exports": [
        "ChartSiteShellProps"
      ],
      "type_exports": [
        "ChartSiteShellProps"
      ]
    },
    {
      "kind": "component",
      "name": "DocsOverview",
      "source": "components/charts/docs-overview.tsx",
      "import_path": "@/components/charts/docs-overview",
      "barrel_export": "../../components/charts/docs-overview",
      "exports": [
        "DocsOverview"
      ],
      "default_export_name": null,
      "used_exports": [
        "DocsOverview"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "EcosystemOverview",
      "source": "components/charts/ecosystem-overview.tsx",
      "import_path": "@/components/charts/ecosystem-overview",
      "barrel_export": "../../components/charts/ecosystem-overview",
      "exports": [
        "EcosystemOverview"
      ],
      "default_export_name": null,
      "used_exports": [
        "EcosystemOverview"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "ExamplesOverview",
      "source": "components/charts/examples-overview.tsx",
      "import_path": "@/components/charts/examples-overview",
      "barrel_export": "../../components/charts/examples-overview",
      "exports": [
        "ExamplesOverview"
      ],
      "default_export_name": null,
      "used_exports": [
        "ExamplesOverview"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "PlaygroundPreview",
      "source": "components/charts/playground-preview.tsx",
      "import_path": "@/components/charts/playground-preview",
      "barrel_export": "../../components/charts/playground-preview",
      "exports": [
        "PlaygroundPreview"
      ],
      "default_export_name": null,
      "used_exports": [
        "PlaygroundPreview"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "ChartRouteBoundary",
      "source": "components/charts/route-boundary.tsx",
      "import_path": "@/components/charts/route-boundary",
      "barrel_export": "../../components/charts/route-boundary",
      "exports": [
        "ChartRouteBoundary",
        "ChartRouteBoundaryKind"
      ],
      "default_export_name": null,
      "used_exports": [
        "ChartRouteBoundary"
      ],
      "unused_exports": [
        "ChartRouteBoundaryKind"
      ],
      "type_exports": [
        "ChartRouteBoundaryKind"
      ]
    },
    {
      "kind": "component",
      "name": "ThemeOverview",
      "source": "components/charts/theme-overview.tsx",
      "import_path": "@/components/charts/theme-overview",
      "barrel_export": "../../components/charts/theme-overview",
      "exports": [
        "ThemeOverview"
      ],
      "default_export_name": null,
      "used_exports": [
        "ThemeOverview"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "IslandRuntimeProbe",
      "source": "components/island-runtime-probe.tsx",
      "import_path": "@/components/island-runtime-probe",
      "barrel_export": "../../components/island-runtime-probe",
      "exports": [
        "IslandRuntimeProbe"
      ],
      "default_export_name": null,
      "used_exports": [
        "IslandRuntimeProbe"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "FrameworkCompletenessItem",
      "source": "components/launch/framework-completeness.ts",
      "import_path": "@/components/launch/framework-completeness",
      "barrel_export": null,
      "exports": [
        "FrameworkCompletenessItem",
        "FrameworkCompletenessStatus",
        "dxChartsFrameworkCompleteness",
        "dxChartsFrameworkCompletenessSummary",
        "frameworkCompletenessContract"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "FrameworkCompletenessItem",
        "FrameworkCompletenessStatus",
        "dxChartsFrameworkCompleteness",
        "dxChartsFrameworkCompletenessSummary",
        "frameworkCompletenessContract"
      ],
      "type_exports": [
        "FrameworkCompletenessItem",
        "FrameworkCompletenessStatus"
      ]
    },
    {
      "kind": "component",
      "name": "StateRuntimeProbe",
      "source": "components/state-runtime-probe.tsx",
      "import_path": "@/components/state-runtime-probe",
      "barrel_export": "../../components/state-runtime-probe",
      "exports": [
        "StateRuntimeProbe"
      ],
      "default_export_name": null,
      "used_exports": [
        "StateRuntimeProbe"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "ChartsActivityIcon",
      "source": "components/icons/charts-activity.tsx",
      "import_path": "@/components/icons/charts-activity",
      "barrel_export": null,
      "exports": [
        "ChartsActivityIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ChartsActivityIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "ChartsBarIcon",
      "source": "components/icons/charts-bar.tsx",
      "import_path": "@/components/icons/charts-bar",
      "barrel_export": null,
      "exports": [
        "ChartsBarIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ChartsBarIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "ChartsBookIcon",
      "source": "components/icons/charts-book.tsx",
      "import_path": "@/components/icons/charts-book",
      "barrel_export": null,
      "exports": [
        "ChartsBookIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ChartsBookIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "ChartsCheckIcon",
      "source": "components/icons/charts-check.tsx",
      "import_path": "@/components/icons/charts-check",
      "barrel_export": null,
      "exports": [
        "ChartsCheckIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ChartsCheckIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "ChartsLayersIcon",
      "source": "components/icons/charts-layers.tsx",
      "import_path": "@/components/icons/charts-layers",
      "barrel_export": null,
      "exports": [
        "ChartsLayersIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ChartsLayersIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "ChartsNetworkIcon",
      "source": "components/icons/charts-network.tsx",
      "import_path": "@/components/icons/charts-network",
      "barrel_export": null,
      "exports": [
        "ChartsNetworkIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ChartsNetworkIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "ChartsPackageIcon",
      "source": "components/icons/charts-package.tsx",
      "import_path": "@/components/icons/charts-package",
      "barrel_export": null,
      "exports": [
        "ChartsPackageIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ChartsPackageIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "ChartsPaletteIcon",
      "source": "components/icons/charts-palette.tsx",
      "import_path": "@/components/icons/charts-palette",
      "barrel_export": null,
      "exports": [
        "ChartsPaletteIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ChartsPaletteIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "ChartsSparklineIcon",
      "source": "components/icons/charts-sparkline.tsx",
      "import_path": "@/components/icons/charts-sparkline",
      "barrel_export": null,
      "exports": [
        "ChartsSparklineIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ChartsSparklineIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "ChartsTargetIcon",
      "source": "components/icons/charts-target.tsx",
      "import_path": "@/components/icons/charts-target",
      "barrel_export": null,
      "exports": [
        "ChartsTargetIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ChartsTargetIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "ChartsTerminalIcon",
      "source": "components/icons/charts-terminal.tsx",
      "import_path": "@/components/icons/charts-terminal",
      "barrel_export": null,
      "exports": [
        "ChartsTerminalIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ChartsTerminalIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "Icon",
      "source": "components/icons/icon.tsx",
      "import_path": "@/components/icons/icon",
      "barrel_export": "../../components/icons/icon",
      "exports": [
        "Icon",
        "IconProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "Icon",
        "IconProps"
      ],
      "unused_exports": [],
      "type_exports": [
        "IconProps"
      ]
    }
  ],
  "composables": [],
  "utilities": [],
  "forgePackages": [
    {
      "packageId": "www/minimal-starter",
      "source": "forge/www/minimal-starter",
      "importPath": "@/forge/www/minimal-starter",
      "exports": []
    }
  ],
  "styleHelpers": [
    {
      "name": "generated.css",
      "source": "styles/generated.css",
      "importPath": "@/styles/generated.css"
    },
    {
      "name": "theme.css",
      "source": "styles/theme.css",
      "importPath": "@/styles/theme.css"
    }
  ],
  "sourceHash": "blake3:bd4051e82a5a32e6dab445ce00f47b5a15b2f9e04afd9b53d633ceb39b4953dc"
} as const;

export type DxAutoImportComponent = typeof dxAutoImportMap.components[number]["name"];
export type DxAutoImportComposable = typeof dxAutoImportMap.composables[number]["name"];
export type DxAutoImportUtility = typeof dxAutoImportMap.utilities[number]["name"];
export type DxAutoImportForgePackage = typeof dxAutoImportMap.forgePackages[number]["packageId"];
export type DxAutoImportStyleHelper = typeof dxAutoImportMap.styleHelpers[number]["name"];
