/* Generated by dx imports sync. */
/* Source-owned IDE contract for DX WWW auto-imports. */

declare module "#components" {
  export { ChartFrame } from "../../components/charts/chart-frame";
  export { ChartGallery } from "../../components/charts/chart-gallery";
  export { ChartHome } from "../../components/charts/chart-home";
  export { ChartSiteShell } from "../../components/charts/chart-site-shell";
  export { DocsOverview } from "../../components/charts/docs-overview";
  export { EcosystemOverview } from "../../components/charts/ecosystem-overview";
  export { ExamplesOverview } from "../../components/charts/examples-overview";
  export { PlaygroundPreview } from "../../components/charts/playground-preview";
  export { ChartRouteBoundary } from "../../components/charts/route-boundary";
  export { ThemeOverview } from "../../components/charts/theme-overview";
  export { IslandRuntimeProbe } from "../../components/island-runtime-probe";
  export { StateRuntimeProbe } from "../../components/state-runtime-probe";
  export { Icon } from "../../components/icons/icon";
  export type { IconProps } from "../../components/icons/icon";
}

declare module "#imports" {
  export { ChartFrame } from "../../components/charts/chart-frame";
  export { ChartGallery } from "../../components/charts/chart-gallery";
  export { ChartHome } from "../../components/charts/chart-home";
  export { ChartSiteShell } from "../../components/charts/chart-site-shell";
  export { DocsOverview } from "../../components/charts/docs-overview";
  export { EcosystemOverview } from "../../components/charts/ecosystem-overview";
  export { ExamplesOverview } from "../../components/charts/examples-overview";
  export { PlaygroundPreview } from "../../components/charts/playground-preview";
  export { ChartRouteBoundary } from "../../components/charts/route-boundary";
  export { ThemeOverview } from "../../components/charts/theme-overview";
  export { IslandRuntimeProbe } from "../../components/island-runtime-probe";
  export { StateRuntimeProbe } from "../../components/state-runtime-probe";
  export { Icon } from "../../components/icons/icon";
  export type { IconProps } from "../../components/icons/icon";
}

declare global {
  const ChartFrame: typeof import("../../components/charts/chart-frame")["ChartFrame"];
  const ChartGallery: typeof import("../../components/charts/chart-gallery")["ChartGallery"];
  const ChartHome: typeof import("../../components/charts/chart-home")["ChartHome"];
  const ChartSiteShell: typeof import("../../components/charts/chart-site-shell")["ChartSiteShell"];
  const DocsOverview: typeof import("../../components/charts/docs-overview")["DocsOverview"];
  const EcosystemOverview: typeof import("../../components/charts/ecosystem-overview")["EcosystemOverview"];
  const ExamplesOverview: typeof import("../../components/charts/examples-overview")["ExamplesOverview"];
  const PlaygroundPreview: typeof import("../../components/charts/playground-preview")["PlaygroundPreview"];
  const ChartRouteBoundary: typeof import("../../components/charts/route-boundary")["ChartRouteBoundary"];
  const ThemeOverview: typeof import("../../components/charts/theme-overview")["ThemeOverview"];
  const IslandRuntimeProbe: typeof import("../../components/island-runtime-probe")["IslandRuntimeProbe"];
  const StateRuntimeProbe: typeof import("../../components/state-runtime-probe")["StateRuntimeProbe"];
  const Icon: typeof import("../../components/icons/icon")["Icon"];
}

export {};
