/* Generated by dx imports sync. */
/* Keep source files editable; regenerate after moves or export changes. */

export const dxAutoImportMap = {
  "components": [
    {
      "kind": "component",
      "name": "IslandRuntimeProbe",
      "source": "components/island-runtime-probe.tsx",
      "import_path": "@/components/island-runtime-probe",
      "barrel_export": null,
      "exports": [
        "IslandRuntimeProbe"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "IslandRuntimeProbe"
      ],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "StateRuntimeProbe",
      "source": "components/state-runtime-probe.tsx",
      "import_path": "@/components/state-runtime-probe",
      "barrel_export": null,
      "exports": [
        "StateRuntimeProbe"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "StateRuntimeProbe"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "Icon",
      "source": "components/icons/icon.tsx",
      "import_path": "@/components/icons/icon",
      "barrel_export": null,
      "exports": [
        "Icon",
        "IconProps"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "Icon",
        "IconProps"
      ],
      "type_exports": [
        "IconProps"
      ]
    }
  ],
  "composables": [],
  "utilities": [],
  "forgePackages": [],
  "styleHelpers": [
    {
      "name": "generated.css",
      "source": "styles/generated.css",
      "importPath": "@/styles/generated.css"
    },
    {
      "name": "theme.css",
      "source": "styles/theme.css",
      "importPath": "@/styles/theme.css"
    }
  ],
  "sourceHash": "blake3:064fddc20f69c9cb2b9506e01a19c5b53e24d39a33ee2373f4d1740005fefa2b"
} as const;

export type DxAutoImportComponent = typeof dxAutoImportMap.components[number]["name"];
export type DxAutoImportComposable = typeof dxAutoImportMap.composables[number]["name"];
export type DxAutoImportUtility = typeof dxAutoImportMap.utilities[number]["name"];
export type DxAutoImportForgePackage = typeof dxAutoImportMap.forgePackages[number]["packageId"];
export type DxAutoImportStyleHelper = typeof dxAutoImportMap.styleHelpers[number]["name"];
