/* Generated by dx imports sync. */
/* Keep source files editable; regenerate after moves or export changes. */
export * from "./icons/icon";
export * from "../lib/forge/www/landing-page";

export const dxAutoImportMap = {
  "components": [
    {
      "kind": "component",
      "name": "ConversionRouteHeader",
      "source": "components/ConversionRouteHeader.tsx",
      "import_path": "@/components/ConversionRouteHeader",
      "barrel_export": null,
      "exports": [
        "ConversionRouteHeader",
        "ConversionRouteHeaderProps"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "ConversionRouteHeader",
        "ConversionRouteHeaderProps"
      ],
      "type_exports": [
        "ConversionRouteHeaderProps"
      ]
    },
    {
      "kind": "component",
      "name": "RuntimeBoundaryPanel",
      "source": "components/RuntimeBoundaryPanel.tsx",
      "import_path": "@/components/RuntimeBoundaryPanel",
      "barrel_export": null,
      "exports": [
        "RuntimeBoundaryPanel",
        "RuntimeBoundaryPanelProps"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "RuntimeBoundaryPanel",
        "RuntimeBoundaryPanelProps"
      ],
      "type_exports": [
        "RuntimeBoundaryPanelProps"
      ]
    },
    {
      "kind": "component",
      "name": "SourceSurfaceTable",
      "source": "components/SourceSurfaceTable.tsx",
      "import_path": "@/components/SourceSurfaceTable",
      "barrel_export": null,
      "exports": [
        "SourceSurfaceTable",
        "SourceSurfaceTableProps"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "SourceSurfaceTable",
        "SourceSurfaceTableProps"
      ],
      "type_exports": [
        "SourceSurfaceTableProps"
      ]
    },
    {
      "kind": "dx-icon",
      "name": "Icon",
      "source": "components/icons/icon.tsx",
      "import_path": "@/components/icons/icon",
      "barrel_export": "./icons/icon",
      "exports": [
        "Icon",
        "IconProps"
      ],
      "default_export_name": null,
      "used_exports": [
        "Icon",
        "IconProps"
      ],
      "unused_exports": [],
      "type_exports": [
        "IconProps"
      ]
    },
    {
      "kind": "dx-icon",
      "name": "PackMotionIcon",
      "source": "components/icons/pack-motion.tsx",
      "import_path": "@/components/icons/pack-motion",
      "barrel_export": null,
      "exports": [
        "PackMotionIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackMotionIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackPlayIcon",
      "source": "components/icons/pack-play.tsx",
      "import_path": "@/components/icons/pack-play",
      "barrel_export": null,
      "exports": [
        "PackPlayIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackPlayIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackStateIcon",
      "source": "components/icons/pack-state.tsx",
      "import_path": "@/components/icons/pack-state",
      "barrel_export": null,
      "exports": [
        "PackStateIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackStateIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackThreeSceneIcon",
      "source": "components/icons/pack-three-scene.tsx",
      "import_path": "@/components/icons/pack-three-scene",
      "barrel_export": null,
      "exports": [
        "PackThreeSceneIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackThreeSceneIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackUiComponentsIcon",
      "source": "components/icons/pack-ui-components.tsx",
      "import_path": "@/components/icons/pack-ui-components",
      "barrel_export": null,
      "exports": [
        "PackUiComponentsIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackUiComponentsIcon"
      ],
      "type_exports": []
    },
    {
      "kind": "dx-icon",
      "name": "PackWorkspaceIcon",
      "source": "components/icons/pack-workspace.tsx",
      "import_path": "@/components/icons/pack-workspace",
      "barrel_export": null,
      "exports": [
        "PackWorkspaceIcon"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "PackWorkspaceIcon"
      ],
      "type_exports": []
    }
  ],
  "composables": [],
  "utilities": [
    {
      "kind": "utility",
      "name": "LandingIdentityFooter",
      "source": "lib/forge/www/landing-identity.tsx",
      "import_path": "@/lib/forge/www/landing-identity",
      "barrel_export": null,
      "exports": [
        "LandingIdentityFooter",
        "LandingProofGrid"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "LandingIdentityFooter",
        "LandingProofGrid"
      ],
      "type_exports": []
    },
    {
      "kind": "utility",
      "name": "LandingPageContent",
      "source": "lib/forge/www/landing-page.tsx",
      "import_path": "@/lib/forge/www/landing-page",
      "barrel_export": "../lib/forge/www/landing-page",
      "exports": [
        "LandingPageContent"
      ],
      "default_export_name": null,
      "used_exports": [
        "LandingPageContent"
      ],
      "unused_exports": [],
      "type_exports": []
    }
  ],
  "forgePackages": [],
  "styleHelpers": [
    {
      "name": "generated.css",
      "source": "styles/generated.css",
      "importPath": "@/styles/generated.css"
    },
    {
      "name": "theme.css",
      "source": "styles/theme.css",
      "importPath": "@/styles/theme.css"
    }
  ],
  "sourceHash": "blake3:ae3918644a00411ba4946b55075170d8670040f4d0dd06c6349b3c1547a05f7e"
} as const;

export type DxAutoImportComponent = typeof dxAutoImportMap.components[number]["name"];
export type DxAutoImportComposable = typeof dxAutoImportMap.composables[number]["name"];
export type DxAutoImportUtility = typeof dxAutoImportMap.utilities[number]["name"];
export type DxAutoImportForgePackage = typeof dxAutoImportMap.forgePackages[number]["packageId"];
export type DxAutoImportStyleHelper = typeof dxAutoImportMap.styleHelpers[number]["name"];
