/* Generated by dx imports sync. */
/* Keep source files editable; regenerate after moves or export changes. */
export * from "./friday";
export * from "./hello-glow";
export * from "./ui/button";

export const dxAutoImportMap = {
  "components": [
    {
      "kind": "component",
      "name": "Friday",
      "source": "components/friday.tsx",
      "import_path": "@/components/friday",
      "barrel_export": "./friday",
      "exports": [
        "Friday"
      ],
      "default_export_name": null,
      "used_exports": [
        "Friday"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "HelloGlow",
      "source": "components/hello-glow.tsx",
      "import_path": "@/components/hello-glow",
      "barrel_export": "./hello-glow",
      "exports": [
        "HelloGlow"
      ],
      "default_export_name": null,
      "used_exports": [
        "HelloGlow"
      ],
      "unused_exports": [],
      "type_exports": []
    },
    {
      "kind": "component",
      "name": "Button",
      "source": "components/ui/button.tsx",
      "import_path": "@/components/ui/button",
      "barrel_export": "./ui/button",
      "exports": [
        "Button",
        "ButtonProps",
        "buttonVariants"
      ],
      "default_export_name": null,
      "used_exports": [
        "Button"
      ],
      "unused_exports": [
        "ButtonProps",
        "buttonVariants"
      ],
      "type_exports": [
        "ButtonProps"
      ]
    },
    {
      "kind": "dx-icon",
      "name": "Icon",
      "source": "components/icons/icon.tsx",
      "import_path": "@/components/icons/icon",
      "barrel_export": null,
      "exports": [
        "Icon",
        "IconProps"
      ],
      "default_export_name": null,
      "used_exports": [],
      "unused_exports": [
        "Icon",
        "IconProps"
      ],
      "type_exports": [
        "IconProps"
      ]
    }
  ],
  "composables": [],
  "utilities": [],
  "forgePackages": [
    {
      "packageId": "www/minimal-starter",
      "source": "forge/www/minimal-starter",
      "importPath": "@/forge/www/minimal-starter",
      "exports": []
    }
  ],
  "styleHelpers": [
    {
      "name": "generated.css",
      "source": "styles/generated.css",
      "importPath": "@/styles/generated.css"
    },
    {
      "name": "theme.css",
      "source": "styles/theme.css",
      "importPath": "@/styles/theme.css"
    }
  ],
  "sourceHash": "blake3:1e9534ad51f93c879b38067ecda42ea6255563bbf8aa9145fdd5a1b0731a8e92"
} as const;

export type DxAutoImportComponent = typeof dxAutoImportMap.components[number]["name"];
export type DxAutoImportComposable = typeof dxAutoImportMap.composables[number]["name"];
export type DxAutoImportUtility = typeof dxAutoImportMap.utilities[number]["name"];
export type DxAutoImportForgePackage = typeof dxAutoImportMap.forgePackages[number]["packageId"];
export type DxAutoImportStyleHelper = typeof dxAutoImportMap.styleHelpers[number]["name"];
